/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError.js';
import {
    type CompanyList,
    CompanyListFromJSON,
    CompanyListToJSON,
} from '../models/CompanyList.js';

export interface ListCompaniesRequest {
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    offset?: number;
    /**
     * 
     */
    domain?: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    website?: string;
    /**
     * 
     */
    sort?: ListCompaniesSortEnum;
    /**
     * 
     */
    order?: ListCompaniesOrderEnum;
}

/**
 * CompaniesApi - interface
 * 
 * @export
 * @interface CompaniesApiInterface
 */
export interface CompaniesApiInterface {
    /**
     * Creates request options for listCompanies without sending the request
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {string} [domain] 
     * @param {string} [name] 
     * @param {string} [website] 
     * @param {'created_at' | 'name' | 'number_of_employees' | 'founded_on'} [sort] 
     * @param {'asc' | 'desc'} [order] 
     * @throws {RequiredError}
     * @memberof CompaniesApiInterface
     */
    listCompaniesRequestOpts(requestParameters: ListCompaniesRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a bounded company list with optional domain, name, website and sort filters. Pagination uses limit and offset; there is no response cursor.
     * @summary List companies
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {string} [domain] 
     * @param {string} [name] 
     * @param {string} [website] 
     * @param {'created_at' | 'name' | 'number_of_employees' | 'founded_on'} [sort] 
     * @param {'asc' | 'desc'} [order] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompaniesApiInterface
     */
    listCompaniesRaw(requestParameters: ListCompaniesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanyList>>;

    /**
     * Returns a bounded company list with optional domain, name, website and sort filters. Pagination uses limit and offset; there is no response cursor.
     * List companies
     */
    listCompanies(requestParameters: ListCompaniesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanyList>;

}

/**
 * 
 */
export class CompaniesApi extends runtime.BaseAPI implements CompaniesApiInterface {

    /**
     * Creates request options for listCompanies without sending the request
     */
    async listCompaniesRequestOpts(requestParameters: ListCompaniesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['domain'] != null) {
            queryParameters['domain'] = requestParameters['domain'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['website'] != null) {
            queryParameters['website'] = requestParameters['website'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKey authentication
        }


        let urlPath = `/v1/companies`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a bounded company list with optional domain, name, website and sort filters. Pagination uses limit and offset; there is no response cursor.
     * List companies
     */
    async listCompaniesRaw(requestParameters: ListCompaniesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanyList>> {
        const requestOptions = await this.listCompaniesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanyListFromJSON(jsonValue));
    }

    /**
     * Returns a bounded company list with optional domain, name, website and sort filters. Pagination uses limit and offset; there is no response cursor.
     * List companies
     */
    async listCompanies(requestParameters: ListCompaniesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanyList> {
        const response = await this.listCompaniesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListCompaniesSortEnum = {
    CreatedAt: 'created_at',
    Name: 'name',
    NumberOfEmployees: 'number_of_employees',
    FoundedOn: 'founded_on',
} as const;
export type ListCompaniesSortEnum = typeof ListCompaniesSortEnum[keyof typeof ListCompaniesSortEnum];
/**
 * @export
 */
export const ListCompaniesOrderEnum = {
    Asc: 'asc',
    Desc: 'desc',
} as const;
export type ListCompaniesOrderEnum = typeof ListCompaniesOrderEnum[keyof typeof ListCompaniesOrderEnum];
