/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError.js';
import {
    type PublicStats,
    PublicStatsFromJSON,
    PublicStatsToJSON,
} from '../models/PublicStats.js';

/**
 * StatsApi - interface
 * 
 * @export
 * @interface StatsApiInterface
 */
export interface StatsApiInterface {
    /**
     * Creates request options for getStats without sending the request
     * @throws {RequiredError}
     * @memberof StatsApiInterface
     */
    getStatsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns email and mention counts plus the actions version. This endpoint does not require authentication.
     * @summary Get public dataset statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApiInterface
     */
    getStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicStats>>;

    /**
     * Returns email and mention counts plus the actions version. This endpoint does not require authentication.
     * Get public dataset statistics
     */
    getStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicStats>;

}

/**
 * 
 */
export class StatsApi extends runtime.BaseAPI implements StatsApiInterface {

    /**
     * Creates request options for getStats without sending the request
     */
    async getStatsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/stats`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns email and mention counts plus the actions version. This endpoint does not require authentication.
     * Get public dataset statistics
     */
    async getStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicStats>> {
        const requestOptions = await this.getStatsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicStatsFromJSON(jsonValue));
    }

    /**
     * Returns email and mention counts plus the actions version. This endpoint does not require authentication.
     * Get public dataset statistics
     */
    async getStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicStats> {
        const response = await this.getStatsRaw(initOverrides);
        return await response.value();
    }

}
