/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError.js';
import {
    type BatchVerificationRequest,
    BatchVerificationRequestFromJSON,
    BatchVerificationRequestToJSON,
} from '../models/BatchVerificationRequest.js';
import {
    type BatchVerificationResponse,
    BatchVerificationResponseFromJSON,
    BatchVerificationResponseToJSON,
} from '../models/BatchVerificationResponse.js';
import {
    type VerificationResponse,
    VerificationResponseFromJSON,
    VerificationResponseToJSON,
} from '../models/VerificationResponse.js';

export interface VerifyBatchRequest {
    /**
     * 
     */
    batchVerificationRequest: BatchVerificationRequest;
}

export interface VerifyEmailRequest {
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    cacheMaxAge?: VerifyEmailCacheMaxAgeEnum;
    /**
     * 
     */
    onlyIfFree?: VerifyEmailOnlyIfFreeEnum;
}

/**
 * VerificationApi - interface
 * 
 * @export
 * @interface VerificationApiInterface
 */
export interface VerificationApiInterface {
    /**
     * Creates request options for verifyBatch without sending the request
     * @param {BatchVerificationRequest} batchVerificationRequest 
     * @throws {RequiredError}
     * @memberof VerificationApiInterface
     */
    verifyBatchRequestOpts(requestParameters: VerifyBatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Processes email addresses sequentially. A successful HTTP 200 response contains per-item results or errors. Do not replay the whole batch when only one item fails. This operation may consume credits.
     * @summary Verify a batch of email addresses
     * @param {BatchVerificationRequest} batchVerificationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VerificationApiInterface
     */
    verifyBatchRaw(requestParameters: VerifyBatchRequest, initOverrides?: runtime.RequestOptions | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchVerificationResponse>>;

    /**
     * Processes email addresses sequentially. A successful HTTP 200 response contains per-item results or errors. Do not replay the whole batch when only one item fails. This operation may consume credits.
     * Verify a batch of email addresses
     */
    verifyBatch(requestParameters: VerifyBatchRequest, initOverrides?: runtime.RequestOptions | runtime.InitOverrideFunction): Promise<BatchVerificationResponse>;

    /**
     * Creates request options for verifyEmail without sending the request
     * @param {string} email 
     * @param {'live' | '1d' | '1w' | '1m'} [cacheMaxAge] 
     * @param {'true' | 'false'} [onlyIfFree] 
     * @throws {RequiredError}
     * @memberof VerificationApiInterface
     */
    verifyEmailRequestOpts(requestParameters: VerifyEmailRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a final JSON aggregate by default. Accept: text/event-stream selects a finite stream of unnamed data events. Events carry a stage, state, result or error; there is no kind field or [DONE] marker on this endpoint. A result or error is terminal. Verification may consume credits and must not be automatically retried or reconnected.
     * @summary Verify an email address
     * @param {string} email 
     * @param {'live' | '1d' | '1w' | '1m'} [cacheMaxAge] 
     * @param {'true' | 'false'} [onlyIfFree] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VerificationApiInterface
     */
    verifyEmailRaw(requestParameters: VerifyEmailRequest, initOverrides?: runtime.RequestOptions | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerificationResponse>>;

    /**
     * Returns a final JSON aggregate by default. Accept: text/event-stream selects a finite stream of unnamed data events. Events carry a stage, state, result or error; there is no kind field or [DONE] marker on this endpoint. A result or error is terminal. Verification may consume credits and must not be automatically retried or reconnected.
     * Verify an email address
     */
    verifyEmail(requestParameters: VerifyEmailRequest, initOverrides?: runtime.RequestOptions | runtime.InitOverrideFunction): Promise<VerificationResponse>;

}

/**
 * 
 */
export class VerificationApi extends runtime.BaseAPI implements VerificationApiInterface {

    /**
     * Creates request options for verifyBatch without sending the request
     */
    async verifyBatchRequestOpts(requestParameters: VerifyBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['batchVerificationRequest'] == null) {
            throw new runtime.RequiredError(
                'batchVerificationRequest',
                'Required parameter "batchVerificationRequest" was null or undefined when calling verifyBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKey authentication
        }


        let urlPath = `/v1/verify/batch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchVerificationRequestToJSON(requestParameters['batchVerificationRequest']),
        };
    }

    /**
     * Processes email addresses sequentially. A successful HTTP 200 response contains per-item results or errors. Do not replay the whole batch when only one item fails. This operation may consume credits.
     * Verify a batch of email addresses
     */
    async verifyBatchRaw(requestParameters: VerifyBatchRequest, initOverrides?: runtime.RequestOptions | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchVerificationResponse>> {
        const requestOptions = await this.verifyBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchVerificationResponseFromJSON(jsonValue));
    }

    /**
     * Processes email addresses sequentially. A successful HTTP 200 response contains per-item results or errors. Do not replay the whole batch when only one item fails. This operation may consume credits.
     * Verify a batch of email addresses
     */
    async verifyBatch(requestParameters: VerifyBatchRequest, initOverrides?: runtime.RequestOptions | runtime.InitOverrideFunction): Promise<BatchVerificationResponse> {
        const response = await this.verifyBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyEmail without sending the request
     */
    async verifyEmailRequestOpts(requestParameters: VerifyEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling verifyEmail().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['cacheMaxAge'] != null) {
            queryParameters['cacheMaxAge'] = requestParameters['cacheMaxAge'];
        }

        if (requestParameters['onlyIfFree'] != null) {
            queryParameters['onlyIfFree'] = requestParameters['onlyIfFree'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKey authentication
        }


        let urlPath = `/v1/verify`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a final JSON aggregate by default. Accept: text/event-stream selects a finite stream of unnamed data events. Events carry a stage, state, result or error; there is no kind field or [DONE] marker on this endpoint. A result or error is terminal. Verification may consume credits and must not be automatically retried or reconnected.
     * Verify an email address
     */
    async verifyEmailRaw(requestParameters: VerifyEmailRequest, initOverrides?: runtime.RequestOptions | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerificationResponse>> {
        const requestOptions = await this.verifyEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerificationResponseFromJSON(jsonValue));
    }

    /**
     * Returns a final JSON aggregate by default. Accept: text/event-stream selects a finite stream of unnamed data events. Events carry a stage, state, result or error; there is no kind field or [DONE] marker on this endpoint. A result or error is terminal. Verification may consume credits and must not be automatically retried or reconnected.
     * Verify an email address
     */
    async verifyEmail(requestParameters: VerifyEmailRequest, initOverrides?: runtime.RequestOptions | runtime.InitOverrideFunction): Promise<VerificationResponse> {
        const response = await this.verifyEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const VerifyEmailCacheMaxAgeEnum = {
    Live: 'live',
    _1d: '1d',
    _1w: '1w',
    _1m: '1m',
} as const;
export type VerifyEmailCacheMaxAgeEnum = typeof VerifyEmailCacheMaxAgeEnum[keyof typeof VerifyEmailCacheMaxAgeEnum];
/**
 * @export
 */
export const VerifyEmailOnlyIfFreeEnum = {
    True: 'true',
    False: 'false',
} as const;
export type VerifyEmailOnlyIfFreeEnum = typeof VerifyEmailOnlyIfFreeEnum[keyof typeof VerifyEmailOnlyIfFreeEnum];
