/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AirtableMappingOptionsResponseOptionsTablesInnerFieldsInner } from './AirtableMappingOptionsResponseOptionsTablesInnerFieldsInner.js';
import {
    AirtableMappingOptionsResponseOptionsTablesInnerFieldsInnerFromJSON,
    AirtableMappingOptionsResponseOptionsTablesInnerFieldsInnerFromJSONTyped,
    AirtableMappingOptionsResponseOptionsTablesInnerFieldsInnerToJSON,
    AirtableMappingOptionsResponseOptionsTablesInnerFieldsInnerToJSONTyped,
} from './AirtableMappingOptionsResponseOptionsTablesInnerFieldsInner.js';

/**
 * 
 * @export
 * @interface AirtableMappingOptionsResponseOptionsTablesInner
 */
export interface AirtableMappingOptionsResponseOptionsTablesInner {
    [key: string]: any | any;
    /**
     * 
     */
    fields: Array<AirtableMappingOptionsResponseOptionsTablesInnerFieldsInner>;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
}

/**
 * Check if a given object implements the AirtableMappingOptionsResponseOptionsTablesInner interface.
 */
export function instanceOfAirtableMappingOptionsResponseOptionsTablesInner(value: object): value is AirtableMappingOptionsResponseOptionsTablesInner {
    if (!('fields' in value) || value['fields'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AirtableMappingOptionsResponseOptionsTablesInnerFromJSON(json: any): AirtableMappingOptionsResponseOptionsTablesInner {
    return AirtableMappingOptionsResponseOptionsTablesInnerFromJSONTyped(json, false);
}

export function AirtableMappingOptionsResponseOptionsTablesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirtableMappingOptionsResponseOptionsTablesInner {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fields': ((json['fields'] as Array<any>).map(AirtableMappingOptionsResponseOptionsTablesInnerFieldsInnerFromJSON)),
        'id': json['id'],
        'name': json['name'],
    };
}

export function AirtableMappingOptionsResponseOptionsTablesInnerToJSON(json: any): AirtableMappingOptionsResponseOptionsTablesInner {
    return AirtableMappingOptionsResponseOptionsTablesInnerToJSONTyped(json, false);
}

export function AirtableMappingOptionsResponseOptionsTablesInnerToJSONTyped(value?: AirtableMappingOptionsResponseOptionsTablesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'fields': ((value['fields'] as Array<any>).map(AirtableMappingOptionsResponseOptionsTablesInnerFieldsInnerToJSON)),
        'id': value['id'],
        'name': value['name'],
    };
}

