/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AirtableMappingOptionsResponseOptionsTablesInner } from './AirtableMappingOptionsResponseOptionsTablesInner.js';
import {
    AirtableMappingOptionsResponseOptionsTablesInnerFromJSON,
    AirtableMappingOptionsResponseOptionsTablesInnerFromJSONTyped,
    AirtableMappingOptionsResponseOptionsTablesInnerToJSON,
    AirtableMappingOptionsResponseOptionsTablesInnerToJSONTyped,
} from './AirtableMappingOptionsResponseOptionsTablesInner.js';
import type { AirtableMappingOptionsResponseOptionsBasesInner } from './AirtableMappingOptionsResponseOptionsBasesInner.js';
import {
    AirtableMappingOptionsResponseOptionsBasesInnerFromJSON,
    AirtableMappingOptionsResponseOptionsBasesInnerFromJSONTyped,
    AirtableMappingOptionsResponseOptionsBasesInnerToJSON,
    AirtableMappingOptionsResponseOptionsBasesInnerToJSONTyped,
} from './AirtableMappingOptionsResponseOptionsBasesInner.js';

/**
 * 
 * @export
 * @interface AirtableMappingOptionsResponseOptions
 */
export interface AirtableMappingOptionsResponseOptions {
    [key: string]: any | any;
    /**
     * 
     */
    bases: Array<AirtableMappingOptionsResponseOptionsBasesInner>;
    /**
     * 
     */
    provider: string;
    /**
     * 
     */
    tables: Array<AirtableMappingOptionsResponseOptionsTablesInner>;
}

/**
 * Check if a given object implements the AirtableMappingOptionsResponseOptions interface.
 */
export function instanceOfAirtableMappingOptionsResponseOptions(value: object): value is AirtableMappingOptionsResponseOptions {
    if (!('bases' in value) || value['bases'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('tables' in value) || value['tables'] === undefined) return false;
    return true;
}

export function AirtableMappingOptionsResponseOptionsFromJSON(json: any): AirtableMappingOptionsResponseOptions {
    return AirtableMappingOptionsResponseOptionsFromJSONTyped(json, false);
}

export function AirtableMappingOptionsResponseOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirtableMappingOptionsResponseOptions {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'bases': ((json['bases'] as Array<any>).map(AirtableMappingOptionsResponseOptionsBasesInnerFromJSON)),
        'provider': json['provider'],
        'tables': ((json['tables'] as Array<any>).map(AirtableMappingOptionsResponseOptionsTablesInnerFromJSON)),
    };
}

export function AirtableMappingOptionsResponseOptionsToJSON(json: any): AirtableMappingOptionsResponseOptions {
    return AirtableMappingOptionsResponseOptionsToJSONTyped(json, false);
}

export function AirtableMappingOptionsResponseOptionsToJSONTyped(value?: AirtableMappingOptionsResponseOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'bases': ((value['bases'] as Array<any>).map(AirtableMappingOptionsResponseOptionsBasesInnerToJSON)),
        'provider': value['provider'],
        'tables': ((value['tables'] as Array<any>).map(AirtableMappingOptionsResponseOptionsTablesInnerToJSON)),
    };
}

