/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ApiKeyIdentity
 */
export interface ApiKeyIdentity {
    /**
     * 
     */
    keyId: string;
    /**
     * 
     */
    teamId: string;
}

/**
 * Check if a given object implements the ApiKeyIdentity interface.
 */
export function instanceOfApiKeyIdentity(value: object): value is ApiKeyIdentity {
    if (!('keyId' in value) || value['keyId'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    return true;
}

export function ApiKeyIdentityFromJSON(json: any): ApiKeyIdentity {
    return ApiKeyIdentityFromJSONTyped(json, false);
}

export function ApiKeyIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyIdentity {
    if (json == null) {
        return json;
    }
    return {
        
        'keyId': json['keyId'],
        'teamId': json['teamId'],
    };
}

export function ApiKeyIdentityToJSON(json: any): ApiKeyIdentity {
    return ApiKeyIdentityToJSONTyped(json, false);
}

export function ApiKeyIdentityToJSONTyped(value?: ApiKeyIdentity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keyId': value['keyId'],
        'teamId': value['teamId'],
    };
}

