/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Validation issue details. code identifies the validation rule and message explains the failure. Additional rule-specific properties, including the field path, are preserved.
 * @export
 * @interface ApiValidationIssue
 */
export interface ApiValidationIssue {
    [key: string]: any | any;
    /**
     * 
     */
    code?: string;
    /**
     * 
     */
    message?: string;
}

/**
 * Check if a given object implements the ApiValidationIssue interface.
 */
export function instanceOfApiValidationIssue(value: object): value is ApiValidationIssue {
    return true;
}

export function ApiValidationIssueFromJSON(json: any): ApiValidationIssue {
    return ApiValidationIssueFromJSONTyped(json, false);
}

export function ApiValidationIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiValidationIssue {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ApiValidationIssueToJSON(json: any): ApiValidationIssue {
    return ApiValidationIssueToJSONTyped(json, false);
}

export function ApiValidationIssueToJSONTyped(value?: ApiValidationIssue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'code': value['code'],
        'message': value['message'],
    };
}

