/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BindTypeformFormRequest
 */
export interface BindTypeformFormRequest {
    /**
     * 
     */
    capability: BindTypeformFormRequestCapabilityEnum;
    /**
     * 
     */
    connectionId: string;
    /**
     * 
     */
    fieldMapping: { [key: string]: string; };
    /**
     * 
     */
    formId: string;
    /**
     * 
     */
    webhookTag?: string;
}


/**
 * @export
 */
export const BindTypeformFormRequestCapabilityEnum = {
    EmailFind: 'email.find',
    EmailVerify: 'email.verify',
    DomainSearch: 'domain.search',
} as const;
export type BindTypeformFormRequestCapabilityEnum = typeof BindTypeformFormRequestCapabilityEnum[keyof typeof BindTypeformFormRequestCapabilityEnum];


/**
 * Check if a given object implements the BindTypeformFormRequest interface.
 */
export function instanceOfBindTypeformFormRequest(value: object): value is BindTypeformFormRequest {
    if (!('capability' in value) || value['capability'] === undefined) return false;
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('fieldMapping' in value) || value['fieldMapping'] === undefined) return false;
    if (!('formId' in value) || value['formId'] === undefined) return false;
    return true;
}

export function BindTypeformFormRequestFromJSON(json: any): BindTypeformFormRequest {
    return BindTypeformFormRequestFromJSONTyped(json, false);
}

export function BindTypeformFormRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BindTypeformFormRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'capability': json['capability'],
        'connectionId': json['connectionId'],
        'fieldMapping': json['fieldMapping'],
        'formId': json['formId'],
        'webhookTag': json['webhookTag'] == null ? undefined : json['webhookTag'],
    };
}

export function BindTypeformFormRequestToJSON(json: any): BindTypeformFormRequest {
    return BindTypeformFormRequestToJSONTyped(json, false);
}

export function BindTypeformFormRequestToJSONTyped(value?: BindTypeformFormRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capability': value['capability'],
        'connectionId': value['connectionId'],
        'fieldMapping': value['fieldMapping'],
        'formId': value['formId'],
        'webhookTag': value['webhookTag'],
    };
}

