/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AirtableMappingOptionsResponseOptionsBasesInner } from './AirtableMappingOptionsResponseOptionsBasesInner.js';
import {
    AirtableMappingOptionsResponseOptionsBasesInnerFromJSON,
    AirtableMappingOptionsResponseOptionsBasesInnerFromJSONTyped,
    AirtableMappingOptionsResponseOptionsBasesInnerToJSON,
    AirtableMappingOptionsResponseOptionsBasesInnerToJSONTyped,
} from './AirtableMappingOptionsResponseOptionsBasesInner.js';

/**
 * 
 * @export
 * @interface CodaTableInspectionResponseInspection
 */
export interface CodaTableInspectionResponseInspection {
    [key: string]: any | any;
    /**
     * 
     */
    columns: Array<AirtableMappingOptionsResponseOptionsBasesInner>;
    /**
     * 
     */
    providerAccountId: string;
}

/**
 * Check if a given object implements the CodaTableInspectionResponseInspection interface.
 */
export function instanceOfCodaTableInspectionResponseInspection(value: object): value is CodaTableInspectionResponseInspection {
    if (!('columns' in value) || value['columns'] === undefined) return false;
    if (!('providerAccountId' in value) || value['providerAccountId'] === undefined) return false;
    return true;
}

export function CodaTableInspectionResponseInspectionFromJSON(json: any): CodaTableInspectionResponseInspection {
    return CodaTableInspectionResponseInspectionFromJSONTyped(json, false);
}

export function CodaTableInspectionResponseInspectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodaTableInspectionResponseInspection {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'columns': ((json['columns'] as Array<any>).map(AirtableMappingOptionsResponseOptionsBasesInnerFromJSON)),
        'providerAccountId': json['providerAccountId'],
    };
}

export function CodaTableInspectionResponseInspectionToJSON(json: any): CodaTableInspectionResponseInspection {
    return CodaTableInspectionResponseInspectionToJSONTyped(json, false);
}

export function CodaTableInspectionResponseInspectionToJSONTyped(value?: CodaTableInspectionResponseInspection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'columns': ((value['columns'] as Array<any>).map(AirtableMappingOptionsResponseOptionsBasesInnerToJSON)),
        'providerAccountId': value['providerAccountId'],
    };
}

