/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CompanyListResultsInnerAddressesInner } from './CompanyListResultsInnerAddressesInner.js';
import {
    CompanyListResultsInnerAddressesInnerFromJSON,
    CompanyListResultsInnerAddressesInnerFromJSONTyped,
    CompanyListResultsInnerAddressesInnerToJSON,
    CompanyListResultsInnerAddressesInnerToJSONTyped,
} from './CompanyListResultsInnerAddressesInner.js';

/**
 * 
 * @export
 * @interface CompanyListResultsInner
 */
export interface CompanyListResultsInner {
    /**
     * 
     */
    addresses?: Array<CompanyListResultsInnerAddressesInner> | null;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    domains: Array<string>;
    /**
     * 
     */
    foundedOn?: string | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    industry?: string | null;
    /**
     * 
     */
    linkedin?: string | null;
    /**
     * 
     */
    location?: string | null;
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    numberOfEmployees?: number | null;
    /**
     * 
     */
    stock?: string | null;
    /**
     * 
     */
    twitter?: string | null;
    /**
     * 
     */
    type?: string | null;
    /**
     * 
     */
    updatedAt: string;
    /**
     * 
     */
    website?: string | null;
}

/**
 * Check if a given object implements the CompanyListResultsInner interface.
 */
export function instanceOfCompanyListResultsInner(value: object): value is CompanyListResultsInner {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('domains' in value) || value['domains'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function CompanyListResultsInnerFromJSON(json: any): CompanyListResultsInner {
    return CompanyListResultsInnerFromJSONTyped(json, false);
}

export function CompanyListResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyListResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'addresses': json['addresses'] === undefined ? undefined : json['addresses'] === null ? null : ((json['addresses'] as Array<any>).map(CompanyListResultsInnerAddressesInnerFromJSON)),
        'createdAt': json['created_at'],
        'domains': json['domains'],
        'foundedOn': json['founded_on'] === undefined ? undefined : json['founded_on'] === null ? null : json['founded_on'],
        'id': json['id'],
        'industry': json['industry'] === undefined ? undefined : json['industry'] === null ? null : json['industry'],
        'linkedin': json['linkedin'] === undefined ? undefined : json['linkedin'] === null ? null : json['linkedin'],
        'location': json['location'] === undefined ? undefined : json['location'] === null ? null : json['location'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'numberOfEmployees': json['number_of_employees'] === undefined ? undefined : json['number_of_employees'] === null ? null : json['number_of_employees'],
        'stock': json['stock'] === undefined ? undefined : json['stock'] === null ? null : json['stock'],
        'twitter': json['twitter'] === undefined ? undefined : json['twitter'] === null ? null : json['twitter'],
        'type': json['type'] === undefined ? undefined : json['type'] === null ? null : json['type'],
        'updatedAt': json['updated_at'],
        'website': json['website'] === undefined ? undefined : json['website'] === null ? null : json['website'],
    };
}

export function CompanyListResultsInnerToJSON(json: any): CompanyListResultsInner {
    return CompanyListResultsInnerToJSONTyped(json, false);
}

export function CompanyListResultsInnerToJSONTyped(value?: CompanyListResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addresses': value['addresses'] === undefined ? undefined : value['addresses'] === null ? null : ((value['addresses'] as Array<any>).map(CompanyListResultsInnerAddressesInnerToJSON)),
        'created_at': value['createdAt'],
        'domains': value['domains'],
        'founded_on': value['foundedOn'],
        'id': value['id'],
        'industry': value['industry'],
        'linkedin': value['linkedin'],
        'location': value['location'],
        'name': value['name'],
        'number_of_employees': value['numberOfEmployees'],
        'stock': value['stock'],
        'twitter': value['twitter'],
        'type': value['type'],
        'updated_at': value['updatedAt'],
        'website': value['website'],
    };
}

