/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CompanyContextJob
 */
export interface CompanyContextJob {
    [key: string]: any | any;
    /**
     * 
     */
    employmentType: string | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    location: string | null;
    /**
     * 
     */
    postedAt: string;
    /**
     * 
     */
    seniorityLevel: string | null;
    /**
     * 
     */
    source: string;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    url: string | null;
}

/**
 * Check if a given object implements the CompanyContextJob interface.
 */
export function instanceOfCompanyContextJob(value: object): value is CompanyContextJob {
    if (!('employmentType' in value) || value['employmentType'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('postedAt' in value) || value['postedAt'] === undefined) return false;
    if (!('seniorityLevel' in value) || value['seniorityLevel'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CompanyContextJobFromJSON(json: any): CompanyContextJob {
    return CompanyContextJobFromJSONTyped(json, false);
}

export function CompanyContextJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyContextJob {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'employmentType': json['employmentType'],
        'id': json['id'],
        'location': json['location'],
        'postedAt': json['postedAt'],
        'seniorityLevel': json['seniorityLevel'],
        'source': json['source'],
        'title': json['title'],
        'url': json['url'],
    };
}

export function CompanyContextJobToJSON(json: any): CompanyContextJob {
    return CompanyContextJobToJSONTyped(json, false);
}

export function CompanyContextJobToJSONTyped(value?: CompanyContextJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'employmentType': value['employmentType'],
        'id': value['id'],
        'location': value['location'],
        'postedAt': value['postedAt'],
        'seniorityLevel': value['seniorityLevel'],
        'source': value['source'],
        'title': value['title'],
        'url': value['url'],
    };
}

