/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ConfigureWarehouseRequest
 */
export interface ConfigureWarehouseRequest {
    /**
     * 
     */
    config: { [key: string]: string; };
    /**
     * 
     */
    credential: { [key: string]: string; };
    /**
     * 
     */
    label: string;
    /**
     * 
     */
    mode?: ConfigureWarehouseRequestModeEnum;
    /**
     * 
     */
    provider: ConfigureWarehouseRequestProviderEnum;
}


/**
 * @export
 */
export const ConfigureWarehouseRequestModeEnum = {
    Live: 'live',
    Emulated: 'emulated',
} as const;
export type ConfigureWarehouseRequestModeEnum = typeof ConfigureWarehouseRequestModeEnum[keyof typeof ConfigureWarehouseRequestModeEnum];

/**
 * @export
 */
export const ConfigureWarehouseRequestProviderEnum = {
    Postgresql: 'postgresql',
    Bigquery: 'bigquery',
    Snowflake: 'snowflake',
    Redshift: 'redshift',
} as const;
export type ConfigureWarehouseRequestProviderEnum = typeof ConfigureWarehouseRequestProviderEnum[keyof typeof ConfigureWarehouseRequestProviderEnum];


/**
 * Check if a given object implements the ConfigureWarehouseRequest interface.
 */
export function instanceOfConfigureWarehouseRequest(value: object): value is ConfigureWarehouseRequest {
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('credential' in value) || value['credential'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function ConfigureWarehouseRequestFromJSON(json: any): ConfigureWarehouseRequest {
    return ConfigureWarehouseRequestFromJSONTyped(json, false);
}

export function ConfigureWarehouseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigureWarehouseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'],
        'credential': json['credential'],
        'label': json['label'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'provider': json['provider'],
    };
}

export function ConfigureWarehouseRequestToJSON(json: any): ConfigureWarehouseRequest {
    return ConfigureWarehouseRequestToJSONTyped(json, false);
}

export function ConfigureWarehouseRequestToJSONTyped(value?: ConfigureWarehouseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'credential': value['credential'],
        'label': value['label'],
        'mode': value['mode'],
        'provider': value['provider'],
    };
}

