/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ConfigureCrmSyncRequestConfigurationPolicy
 */
export interface ConfigureCrmSyncRequestConfigurationPolicy {
    /**
     * 
     */
    createOn: Set<ConfigureCrmSyncRequestConfigurationPolicyCreateOnEnum>;
    /**
     * 
     */
    deleteOnLeadDeleted: boolean;
    /**
     * 
     */
    logActivity: boolean;
    /**
     * 
     */
    updateOnLeadUpdated: boolean;
}


/**
 * @export
 */
export const ConfigureCrmSyncRequestConfigurationPolicyCreateOnEnum = {
    LeadCreated: 'lead.created',
    SequenceEmailSent: 'sequence.email.sent',
} as const;
export type ConfigureCrmSyncRequestConfigurationPolicyCreateOnEnum = typeof ConfigureCrmSyncRequestConfigurationPolicyCreateOnEnum[keyof typeof ConfigureCrmSyncRequestConfigurationPolicyCreateOnEnum];


/**
 * Check if a given object implements the ConfigureCrmSyncRequestConfigurationPolicy interface.
 */
export function instanceOfConfigureCrmSyncRequestConfigurationPolicy(value: object): value is ConfigureCrmSyncRequestConfigurationPolicy {
    if (!('createOn' in value) || value['createOn'] === undefined) return false;
    if (!('deleteOnLeadDeleted' in value) || value['deleteOnLeadDeleted'] === undefined) return false;
    if (!('logActivity' in value) || value['logActivity'] === undefined) return false;
    if (!('updateOnLeadUpdated' in value) || value['updateOnLeadUpdated'] === undefined) return false;
    return true;
}

export function ConfigureCrmSyncRequestConfigurationPolicyFromJSON(json: any): ConfigureCrmSyncRequestConfigurationPolicy {
    return ConfigureCrmSyncRequestConfigurationPolicyFromJSONTyped(json, false);
}

export function ConfigureCrmSyncRequestConfigurationPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigureCrmSyncRequestConfigurationPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'createOn': new Set(json['createOn']),
        'deleteOnLeadDeleted': json['deleteOnLeadDeleted'],
        'logActivity': json['logActivity'],
        'updateOnLeadUpdated': json['updateOnLeadUpdated'],
    };
}

export function ConfigureCrmSyncRequestConfigurationPolicyToJSON(json: any): ConfigureCrmSyncRequestConfigurationPolicy {
    return ConfigureCrmSyncRequestConfigurationPolicyToJSONTyped(json, false);
}

export function ConfigureCrmSyncRequestConfigurationPolicyToJSONTyped(value?: ConfigureCrmSyncRequestConfigurationPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createOn': Array.from(value['createOn'] as Set<any>),
        'deleteOnLeadDeleted': value['deleteOnLeadDeleted'],
        'logActivity': value['logActivity'],
        'updateOnLeadUpdated': value['updateOnLeadUpdated'],
    };
}

