/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ConfigureTeamsWorkflowRequest
 */
export interface ConfigureTeamsWorkflowRequest {
    /**
     * 
     */
    label: string;
    /**
     * 
     */
    mode?: ConfigureTeamsWorkflowRequestModeEnum;
    /**
     * 
     */
    webhookUrl: string;
}


/**
 * @export
 */
export const ConfigureTeamsWorkflowRequestModeEnum = {
    Live: 'live',
    Emulated: 'emulated',
} as const;
export type ConfigureTeamsWorkflowRequestModeEnum = typeof ConfigureTeamsWorkflowRequestModeEnum[keyof typeof ConfigureTeamsWorkflowRequestModeEnum];


/**
 * Check if a given object implements the ConfigureTeamsWorkflowRequest interface.
 */
export function instanceOfConfigureTeamsWorkflowRequest(value: object): value is ConfigureTeamsWorkflowRequest {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('webhookUrl' in value) || value['webhookUrl'] === undefined) return false;
    return true;
}

export function ConfigureTeamsWorkflowRequestFromJSON(json: any): ConfigureTeamsWorkflowRequest {
    return ConfigureTeamsWorkflowRequestFromJSONTyped(json, false);
}

export function ConfigureTeamsWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigureTeamsWorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'webhookUrl': json['webhookUrl'],
    };
}

export function ConfigureTeamsWorkflowRequestToJSON(json: any): ConfigureTeamsWorkflowRequest {
    return ConfigureTeamsWorkflowRequestToJSONTyped(json, false);
}

export function ConfigureTeamsWorkflowRequestToJSONTyped(value?: ConfigureTeamsWorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'mode': value['mode'],
        'webhookUrl': value['webhookUrl'],
    };
}

