/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CreateLeadRequestPerson } from './CreateLeadRequestPerson.js';
import {
    CreateLeadRequestPersonFromJSON,
    CreateLeadRequestPersonFromJSONTyped,
    CreateLeadRequestPersonToJSON,
    CreateLeadRequestPersonToJSONTyped,
} from './CreateLeadRequestPerson.js';
import type { CreateLeadRequestCompany } from './CreateLeadRequestCompany.js';
import {
    CreateLeadRequestCompanyFromJSON,
    CreateLeadRequestCompanyFromJSONTyped,
    CreateLeadRequestCompanyToJSON,
    CreateLeadRequestCompanyToJSONTyped,
} from './CreateLeadRequestCompany.js';

/**
 * 
 * @export
 * @interface CreateLeadRequest
 */
export interface CreateLeadRequest {
    /**
     * 
     */
    company?: CreateLeadRequestCompany;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    person?: CreateLeadRequestPerson;
    /**
     * 
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the CreateLeadRequest interface.
 */
export function instanceOfCreateLeadRequest(value: object): value is CreateLeadRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateLeadRequestFromJSON(json: any): CreateLeadRequest {
    return CreateLeadRequestFromJSONTyped(json, false);
}

export function CreateLeadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLeadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'] == null ? undefined : CreateLeadRequestCompanyFromJSON(json['company']),
        'email': json['email'],
        'person': json['person'] == null ? undefined : CreateLeadRequestPersonFromJSON(json['person']),
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function CreateLeadRequestToJSON(json: any): CreateLeadRequest {
    return CreateLeadRequestToJSONTyped(json, false);
}

export function CreateLeadRequestToJSONTyped(value?: CreateLeadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': CreateLeadRequestCompanyToJSON(value['company']),
        'email': value['email'],
        'person': CreateLeadRequestPersonToJSON(value['person']),
        'tags': value['tags'],
    };
}

