/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateAutomationHookRequest
 */
export interface CreateAutomationHookRequest {
    /**
     * 
     */
    callbackUrl: string;
    /**
     * 
     */
    event: CreateAutomationHookRequestEventEnum;
}


/**
 * @export
 */
export const CreateAutomationHookRequestEventEnum = {
    LeadCreated: 'lead.created',
    LeadVerified: 'lead.verified',
    IntegrationJobCompleted: 'integration.job.completed',
    SequenceCreated: 'sequence.created',
    SequenceEmailOpened: 'sequence.email.opened',
    SequenceReplyReceived: 'sequence.reply.received',
} as const;
export type CreateAutomationHookRequestEventEnum = typeof CreateAutomationHookRequestEventEnum[keyof typeof CreateAutomationHookRequestEventEnum];


/**
 * Check if a given object implements the CreateAutomationHookRequest interface.
 */
export function instanceOfCreateAutomationHookRequest(value: object): value is CreateAutomationHookRequest {
    if (!('callbackUrl' in value) || value['callbackUrl'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function CreateAutomationHookRequestFromJSON(json: any): CreateAutomationHookRequest {
    return CreateAutomationHookRequestFromJSONTyped(json, false);
}

export function CreateAutomationHookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAutomationHookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'callbackUrl': json['callbackUrl'],
        'event': json['event'],
    };
}

export function CreateAutomationHookRequestToJSON(json: any): CreateAutomationHookRequest {
    return CreateAutomationHookRequestToJSONTyped(json, false);
}

export function CreateAutomationHookRequestToJSONTyped(value?: CreateAutomationHookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'callbackUrl': value['callbackUrl'],
        'event': value['event'],
    };
}

