/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CrmMappingOptionsResponseOptions } from './CrmMappingOptionsResponseOptions.js';
import {
    CrmMappingOptionsResponseOptionsFromJSON,
    CrmMappingOptionsResponseOptionsFromJSONTyped,
    CrmMappingOptionsResponseOptionsToJSON,
    CrmMappingOptionsResponseOptionsToJSONTyped,
} from './CrmMappingOptionsResponseOptions.js';

/**
 * 
 * @export
 * @interface CrmMappingOptionsResponse
 */
export interface CrmMappingOptionsResponse {
    [key: string]: any | any;
    /**
     * 
     */
    options: CrmMappingOptionsResponseOptions;
}

/**
 * Check if a given object implements the CrmMappingOptionsResponse interface.
 */
export function instanceOfCrmMappingOptionsResponse(value: object): value is CrmMappingOptionsResponse {
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function CrmMappingOptionsResponseFromJSON(json: any): CrmMappingOptionsResponse {
    return CrmMappingOptionsResponseFromJSONTyped(json, false);
}

export function CrmMappingOptionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrmMappingOptionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'options': CrmMappingOptionsResponseOptionsFromJSON(json['options']),
    };
}

export function CrmMappingOptionsResponseToJSON(json: any): CrmMappingOptionsResponse {
    return CrmMappingOptionsResponseToJSONTyped(json, false);
}

export function CrmMappingOptionsResponseToJSONTyped(value?: CrmMappingOptionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'options': CrmMappingOptionsResponseOptionsToJSON(value['options']),
    };
}

