/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DeleteEmailResponse
 */
export interface DeleteEmailResponse {
    /**
     * 
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the DeleteEmailResponse interface.
 */
export function instanceOfDeleteEmailResponse(value: object): value is DeleteEmailResponse {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function DeleteEmailResponseFromJSON(json: any): DeleteEmailResponse {
    return DeleteEmailResponseFromJSONTyped(json, false);
}

export function DeleteEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
    };
}

export function DeleteEmailResponseToJSON(json: any): DeleteEmailResponse {
    return DeleteEmailResponseToJSONTyped(json, false);
}

export function DeleteEmailResponseToJSONTyped(value?: DeleteEmailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

