/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DomainCatchAll
 */
export interface DomainCatchAll {
    /**
     * 
     */
    catchAll: boolean | null;
}

/**
 * Check if a given object implements the DomainCatchAll interface.
 */
export function instanceOfDomainCatchAll(value: object): value is DomainCatchAll {
    if ((!('catchAll' in (value as Record<string, any>)) && !('catch_all' in (value as Record<string, any>))) || ((value as Record<string, any>)['catchAll'] === undefined && (value as Record<string, any>)['catch_all'] === undefined)) return false;
    return true;
}

export function DomainCatchAllFromJSON(json: any): DomainCatchAll {
    return DomainCatchAllFromJSONTyped(json, false);
}

export function DomainCatchAllFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainCatchAll {
    if (json == null) {
        return json;
    }
    return {
        
        'catchAll': json['catch_all'],
    };
}

export function DomainCatchAllToJSON(json: any): DomainCatchAll {
    return DomainCatchAllToJSONTyped(json, false);
}

export function DomainCatchAllToJSONTyped(value?: DomainCatchAll | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'catch_all': value['catchAll'],
    };
}

