/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EmailPageResultsInnerSourcesInner
 */
export interface EmailPageResultsInnerSourcesInner {
    /**
     * 
     */
    domain: string;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    firstSeen: string;
    /**
     * 
     */
    lastSeen: string;
    /**
     * 
     */
    sourceType: string;
    /**
     * 
     */
    sourceUrl: string;
}

/**
 * Check if a given object implements the EmailPageResultsInnerSourcesInner interface.
 */
export function instanceOfEmailPageResultsInnerSourcesInner(value: object): value is EmailPageResultsInnerSourcesInner {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if ((!('firstSeen' in (value as Record<string, any>)) && !('first_seen' in (value as Record<string, any>))) || ((value as Record<string, any>)['firstSeen'] === undefined && (value as Record<string, any>)['first_seen'] === undefined)) return false;
    if ((!('lastSeen' in (value as Record<string, any>)) && !('last_seen' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastSeen'] === undefined && (value as Record<string, any>)['last_seen'] === undefined)) return false;
    if ((!('sourceType' in (value as Record<string, any>)) && !('source_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['sourceType'] === undefined && (value as Record<string, any>)['source_type'] === undefined)) return false;
    if ((!('sourceUrl' in (value as Record<string, any>)) && !('source_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['sourceUrl'] === undefined && (value as Record<string, any>)['source_url'] === undefined)) return false;
    return true;
}

export function EmailPageResultsInnerSourcesInnerFromJSON(json: any): EmailPageResultsInnerSourcesInner {
    return EmailPageResultsInnerSourcesInnerFromJSONTyped(json, false);
}

export function EmailPageResultsInnerSourcesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailPageResultsInnerSourcesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'email': json['email'],
        'firstSeen': json['first_seen'],
        'lastSeen': json['last_seen'],
        'sourceType': json['source_type'],
        'sourceUrl': json['source_url'],
    };
}

export function EmailPageResultsInnerSourcesInnerToJSON(json: any): EmailPageResultsInnerSourcesInner {
    return EmailPageResultsInnerSourcesInnerToJSONTyped(json, false);
}

export function EmailPageResultsInnerSourcesInnerToJSONTyped(value?: EmailPageResultsInnerSourcesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'email': value['email'],
        'first_seen': value['firstSeen'],
        'last_seen': value['lastSeen'],
        'source_type': value['sourceType'],
        'source_url': value['sourceUrl'],
    };
}

