/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EmailPageResultsInnerSourcesInner } from './EmailPageResultsInnerSourcesInner.js';
import {
    EmailPageResultsInnerSourcesInnerFromJSON,
    EmailPageResultsInnerSourcesInnerFromJSONTyped,
    EmailPageResultsInnerSourcesInnerToJSON,
    EmailPageResultsInnerSourcesInnerToJSONTyped,
} from './EmailPageResultsInnerSourcesInner.js';

/**
 * 
 * @export
 * @interface EmailPageResultsInner
 */
export interface EmailPageResultsInner {
    /**
     * 
     */
    category?: string | null;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    domain: string;
    /**
     * 
     */
    email?: string | null;
    /**
     * 
     */
    firstName?: string | null;
    /**
     * 
     */
    firstSeen: string;
    /**
     * 
     */
    fullName?: string | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    lastName?: string | null;
    /**
     * 
     */
    lastSeen: string;
    /**
     * 
     */
    linkedin?: string | null;
    /**
     * 
     */
    position?: string | null;
    /**
     * 
     */
    revealed: boolean;
    /**
     * 
     */
    score: number;
    /**
     * 
     */
    sources?: Array<EmailPageResultsInnerSourcesInner>;
    /**
     * 
     */
    sourcesNextCursor?: string | null;
    /**
     * Known values: VALID, CATCHALL, UNKNOWN, INVALID. Clients preserve future values.
     */
    status: string;
    /**
     * 
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the EmailPageResultsInner interface.
 */
export function instanceOfEmailPageResultsInner(value: object): value is EmailPageResultsInner {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if ((!('firstSeen' in (value as Record<string, any>)) && !('first_seen' in (value as Record<string, any>))) || ((value as Record<string, any>)['firstSeen'] === undefined && (value as Record<string, any>)['first_seen'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('lastSeen' in (value as Record<string, any>)) && !('last_seen' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastSeen'] === undefined && (value as Record<string, any>)['last_seen'] === undefined)) return false;
    if (!('revealed' in value) || value['revealed'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function EmailPageResultsInnerFromJSON(json: any): EmailPageResultsInner {
    return EmailPageResultsInnerFromJSONTyped(json, false);
}

export function EmailPageResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailPageResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] === undefined ? undefined : json['category'] === null ? null : json['category'],
        'createdAt': json['created_at'],
        'domain': json['domain'],
        'email': json['email'] === undefined ? undefined : json['email'] === null ? null : json['email'],
        'firstName': json['first_name'] === undefined ? undefined : json['first_name'] === null ? null : json['first_name'],
        'firstSeen': json['first_seen'],
        'fullName': json['full_name'] === undefined ? undefined : json['full_name'] === null ? null : json['full_name'],
        'id': json['id'],
        'lastName': json['last_name'] === undefined ? undefined : json['last_name'] === null ? null : json['last_name'],
        'lastSeen': json['last_seen'],
        'linkedin': json['linkedin'] === undefined ? undefined : json['linkedin'] === null ? null : json['linkedin'],
        'position': json['position'] === undefined ? undefined : json['position'] === null ? null : json['position'],
        'revealed': json['revealed'],
        'score': json['score'],
        'sources': json['sources'] == null ? undefined : ((json['sources'] as Array<any>).map(EmailPageResultsInnerSourcesInnerFromJSON)),
        'sourcesNextCursor': json['sourcesNextCursor'] === undefined ? undefined : json['sourcesNextCursor'] === null ? null : json['sourcesNextCursor'],
        'status': json['status'],
        'updatedAt': json['updated_at'],
    };
}

export function EmailPageResultsInnerToJSON(json: any): EmailPageResultsInner {
    return EmailPageResultsInnerToJSONTyped(json, false);
}

export function EmailPageResultsInnerToJSONTyped(value?: EmailPageResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'created_at': value['createdAt'],
        'domain': value['domain'],
        'email': value['email'],
        'first_name': value['firstName'],
        'first_seen': value['firstSeen'],
        'full_name': value['fullName'],
        'id': value['id'],
        'last_name': value['lastName'],
        'last_seen': value['lastSeen'],
        'linkedin': value['linkedin'],
        'position': value['position'],
        'revealed': value['revealed'],
        'score': value['score'],
        'sources': value['sources'] == null ? undefined : ((value['sources'] as Array<any>).map(EmailPageResultsInnerSourcesInnerToJSON)),
        'sourcesNextCursor': value['sourcesNextCursor'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
    };
}

