/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ExcelWorkbookInspectionResponseInspection
 */
export interface ExcelWorkbookInspectionResponseInspection {
    [key: string]: any | any;
    /**
     * 
     */
    driveItemId: string;
    /**
     * 
     */
    headers: Array<string>;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    provider: string;
    /**
     * 
     */
    usedRangeAddress: string;
    /**
     * 
     */
    worksheet: string;
    /**
     * 
     */
    worksheets: Array<string>;
}

/**
 * Check if a given object implements the ExcelWorkbookInspectionResponseInspection interface.
 */
export function instanceOfExcelWorkbookInspectionResponseInspection(value: object): value is ExcelWorkbookInspectionResponseInspection {
    if (!('driveItemId' in value) || value['driveItemId'] === undefined) return false;
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('usedRangeAddress' in value) || value['usedRangeAddress'] === undefined) return false;
    if (!('worksheet' in value) || value['worksheet'] === undefined) return false;
    if (!('worksheets' in value) || value['worksheets'] === undefined) return false;
    return true;
}

export function ExcelWorkbookInspectionResponseInspectionFromJSON(json: any): ExcelWorkbookInspectionResponseInspection {
    return ExcelWorkbookInspectionResponseInspectionFromJSONTyped(json, false);
}

export function ExcelWorkbookInspectionResponseInspectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExcelWorkbookInspectionResponseInspection {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'driveItemId': json['driveItemId'],
        'headers': json['headers'],
        'name': json['name'],
        'provider': json['provider'],
        'usedRangeAddress': json['usedRangeAddress'],
        'worksheet': json['worksheet'],
        'worksheets': json['worksheets'],
    };
}

export function ExcelWorkbookInspectionResponseInspectionToJSON(json: any): ExcelWorkbookInspectionResponseInspection {
    return ExcelWorkbookInspectionResponseInspectionToJSONTyped(json, false);
}

export function ExcelWorkbookInspectionResponseInspectionToJSONTyped(value?: ExcelWorkbookInspectionResponseInspection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'driveItemId': value['driveItemId'],
        'headers': value['headers'],
        'name': value['name'],
        'provider': value['provider'],
        'usedRangeAddress': value['usedRangeAddress'],
        'worksheet': value['worksheet'],
        'worksheets': value['worksheets'],
    };
}

