/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetLeadResponseLeadVerification } from './GetLeadResponseLeadVerification.js';
import {
    GetLeadResponseLeadVerificationFromJSON,
    GetLeadResponseLeadVerificationFromJSONTyped,
    GetLeadResponseLeadVerificationToJSON,
    GetLeadResponseLeadVerificationToJSONTyped,
} from './GetLeadResponseLeadVerification.js';
import type { GetLeadResponseLeadSync } from './GetLeadResponseLeadSync.js';
import {
    GetLeadResponseLeadSyncFromJSON,
    GetLeadResponseLeadSyncFromJSONTyped,
    GetLeadResponseLeadSyncToJSON,
    GetLeadResponseLeadSyncToJSONTyped,
} from './GetLeadResponseLeadSync.js';
import type { CreateLeadRequestPerson } from './CreateLeadRequestPerson.js';
import {
    CreateLeadRequestPersonFromJSON,
    CreateLeadRequestPersonFromJSONTyped,
    CreateLeadRequestPersonToJSON,
    CreateLeadRequestPersonToJSONTyped,
} from './CreateLeadRequestPerson.js';
import type { GetLeadResponseLeadCompany } from './GetLeadResponseLeadCompany.js';
import {
    GetLeadResponseLeadCompanyFromJSON,
    GetLeadResponseLeadCompanyFromJSONTyped,
    GetLeadResponseLeadCompanyToJSON,
    GetLeadResponseLeadCompanyToJSONTyped,
} from './GetLeadResponseLeadCompany.js';

/**
 * 
 * @export
 * @interface GetLeadResponseLead
 */
export interface GetLeadResponseLead {
    /**
     * 
     */
    company?: GetLeadResponseLeadCompany;
    /**
     * 
     */
    companyId?: string | null;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    createdBy: string | null;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    lastActivityAt?: string | null;
    /**
     * 
     */
    lastContactedAt?: string | null;
    /**
     * 
     */
    person?: CreateLeadRequestPerson;
    /**
     * 
     */
    sync?: GetLeadResponseLeadSync;
    /**
     * 
     */
    tags?: Array<string>;
    /**
     * 
     */
    teamId: string;
    /**
     * 
     */
    updatedAt: string;
    /**
     * 
     */
    verification?: GetLeadResponseLeadVerification;
}

/**
 * Check if a given object implements the GetLeadResponseLead interface.
 */
export function instanceOfGetLeadResponseLead(value: object): value is GetLeadResponseLead {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('createdBy' in (value as Record<string, any>)) && !('created_by' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdBy'] === undefined && (value as Record<string, any>)['created_by'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('teamId' in (value as Record<string, any>)) && !('team_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['teamId'] === undefined && (value as Record<string, any>)['team_id'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function GetLeadResponseLeadFromJSON(json: any): GetLeadResponseLead {
    return GetLeadResponseLeadFromJSONTyped(json, false);
}

export function GetLeadResponseLeadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLeadResponseLead {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'] == null ? undefined : GetLeadResponseLeadCompanyFromJSON(json['company']),
        'companyId': json['company_id'] === undefined ? undefined : json['company_id'] === null ? null : json['company_id'],
        'createdAt': json['created_at'],
        'createdBy': json['created_by'],
        'email': json['email'],
        'id': json['id'],
        'lastActivityAt': json['last_activity_at'] === undefined ? undefined : json['last_activity_at'] === null ? null : json['last_activity_at'],
        'lastContactedAt': json['last_contacted_at'] === undefined ? undefined : json['last_contacted_at'] === null ? null : json['last_contacted_at'],
        'person': json['person'] == null ? undefined : CreateLeadRequestPersonFromJSON(json['person']),
        'sync': json['sync'] == null ? undefined : GetLeadResponseLeadSyncFromJSON(json['sync']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'teamId': json['team_id'],
        'updatedAt': json['updated_at'],
        'verification': json['verification'] == null ? undefined : GetLeadResponseLeadVerificationFromJSON(json['verification']),
    };
}

export function GetLeadResponseLeadToJSON(json: any): GetLeadResponseLead {
    return GetLeadResponseLeadToJSONTyped(json, false);
}

export function GetLeadResponseLeadToJSONTyped(value?: GetLeadResponseLead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': GetLeadResponseLeadCompanyToJSON(value['company']),
        'company_id': value['companyId'],
        'created_at': value['createdAt'],
        'created_by': value['createdBy'],
        'email': value['email'],
        'id': value['id'],
        'last_activity_at': value['lastActivityAt'],
        'last_contacted_at': value['lastContactedAt'],
        'person': CreateLeadRequestPersonToJSON(value['person']),
        'sync': GetLeadResponseLeadSyncToJSON(value['sync']),
        'tags': value['tags'],
        'team_id': value['teamId'],
        'updated_at': value['updatedAt'],
        'verification': GetLeadResponseLeadVerificationToJSON(value['verification']),
    };
}

