/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { InsightsResponse } from './InsightsResponse.js';
import {
    InsightsResponseFromJSON,
    InsightsResponseFromJSONTyped,
    InsightsResponseToJSON,
    InsightsResponseToJSONTyped,
} from './InsightsResponse.js';

/**
 * 
 * @export
 * @interface InsightFinalEvent
 */
export interface InsightFinalEvent {
    [key: string]: any | any;
    /**
     * 
     */
    email: string;
    /**
     * Known values: final. Clients preserve future values.
     */
    kind: string;
    /**
     * 
     */
    response: InsightsResponse;
}

/**
 * Check if a given object implements the InsightFinalEvent interface.
 */
export function instanceOfInsightFinalEvent(value: object): value is InsightFinalEvent {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('response' in value) || value['response'] === undefined) return false;
    return true;
}

export function InsightFinalEventFromJSON(json: any): InsightFinalEvent {
    return InsightFinalEventFromJSONTyped(json, false);
}

export function InsightFinalEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightFinalEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'email': json['email'],
        'kind': json['kind'],
        'response': InsightsResponseFromJSON(json['response']),
    };
}

export function InsightFinalEventToJSON(json: any): InsightFinalEvent {
    return InsightFinalEventToJSONTyped(json, false);
}

export function InsightFinalEventToJSONTyped(value?: InsightFinalEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'email': value['email'],
        'kind': value['kind'],
        'response': InsightsResponseToJSON(value['response']),
    };
}

