/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { InsightPlatformScan } from './InsightPlatformScan.js';
import {
    InsightPlatformScanFromJSON,
    InsightPlatformScanFromJSONTyped,
    InsightPlatformScanToJSON,
    InsightPlatformScanToJSONTyped,
} from './InsightPlatformScan.js';

/**
 * 
 * @export
 * @interface InsightPlatformScanEvent
 */
export interface InsightPlatformScanEvent {
    [key: string]: any | any;
    /**
     * 
     */
    email: string;
    /**
     * Known values: platform_scan. Clients preserve future values.
     */
    kind: string;
    /**
     * 
     */
    scan: InsightPlatformScan;
}

/**
 * Check if a given object implements the InsightPlatformScanEvent interface.
 */
export function instanceOfInsightPlatformScanEvent(value: object): value is InsightPlatformScanEvent {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('scan' in value) || value['scan'] === undefined) return false;
    return true;
}

export function InsightPlatformScanEventFromJSON(json: any): InsightPlatformScanEvent {
    return InsightPlatformScanEventFromJSONTyped(json, false);
}

export function InsightPlatformScanEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightPlatformScanEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'email': json['email'],
        'kind': json['kind'],
        'scan': InsightPlatformScanFromJSON(json['scan']),
    };
}

export function InsightPlatformScanEventToJSON(json: any): InsightPlatformScanEvent {
    return InsightPlatformScanEventToJSONTyped(json, false);
}

export function InsightPlatformScanEventToJSONTyped(value?: InsightPlatformScanEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'email': value['email'],
        'kind': value['kind'],
        'scan': InsightPlatformScanToJSON(value['scan']),
    };
}

