/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InsightEvidence
 */
export interface InsightEvidence {
    [key: string]: any | any;
    /**
     * 
     */
    fieldPath: string;
    /**
     * 
     */
    note?: string;
    /**
     * 
     */
    snippet: string;
    /**
     * 
     */
    sourceUrl?: string;
}

/**
 * Check if a given object implements the InsightEvidence interface.
 */
export function instanceOfInsightEvidence(value: object): value is InsightEvidence {
    if (!('fieldPath' in value) || value['fieldPath'] === undefined) return false;
    if (!('snippet' in value) || value['snippet'] === undefined) return false;
    return true;
}

export function InsightEvidenceFromJSON(json: any): InsightEvidence {
    return InsightEvidenceFromJSONTyped(json, false);
}

export function InsightEvidenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightEvidence {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fieldPath': json['fieldPath'],
        'note': json['note'] == null ? undefined : json['note'],
        'snippet': json['snippet'],
        'sourceUrl': json['sourceUrl'] == null ? undefined : json['sourceUrl'],
    };
}

export function InsightEvidenceToJSON(json: any): InsightEvidence {
    return InsightEvidenceToJSONTyped(json, false);
}

export function InsightEvidenceToJSONTyped(value?: InsightEvidence | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'fieldPath': value['fieldPath'],
        'note': value['note'],
        'snippet': value['snippet'],
        'sourceUrl': value['sourceUrl'],
    };
}

