/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InsightMentionErrorEvent
 */
export interface InsightMentionErrorEvent {
    [key: string]: any | any;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    error: string;
    /**
     * Known values: mention_error. Clients preserve future values.
     */
    kind: string;
    /**
     * 
     */
    sourceUrl: string;
}

/**
 * Check if a given object implements the InsightMentionErrorEvent interface.
 */
export function instanceOfInsightMentionErrorEvent(value: object): value is InsightMentionErrorEvent {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('sourceUrl' in value) || value['sourceUrl'] === undefined) return false;
    return true;
}

export function InsightMentionErrorEventFromJSON(json: any): InsightMentionErrorEvent {
    return InsightMentionErrorEventFromJSONTyped(json, false);
}

export function InsightMentionErrorEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightMentionErrorEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'email': json['email'],
        'error': json['error'],
        'kind': json['kind'],
        'sourceUrl': json['sourceUrl'],
    };
}

export function InsightMentionErrorEventToJSON(json: any): InsightMentionErrorEvent {
    return InsightMentionErrorEventToJSONTyped(json, false);
}

export function InsightMentionErrorEventToJSONTyped(value?: InsightMentionErrorEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'email': value['email'],
        'error': value['error'],
        'kind': value['kind'],
        'sourceUrl': value['sourceUrl'],
    };
}

