/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InsightMentionExtractedEvent
 */
export interface InsightMentionExtractedEvent {
    [key: string]: any | any;
    /**
     * 
     */
    domain: string;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    emailMoved: boolean;
    /**
     * 
     */
    index: number;
    /**
     * Known values: mention_extracted. Clients preserve future values.
     */
    kind: string;
    /**
     * 
     */
    sourceType: string;
    /**
     * 
     */
    sourceUrl: string;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the InsightMentionExtractedEvent interface.
 */
export function instanceOfInsightMentionExtractedEvent(value: object): value is InsightMentionExtractedEvent {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('emailMoved' in value) || value['emailMoved'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('sourceUrl' in value) || value['sourceUrl'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function InsightMentionExtractedEventFromJSON(json: any): InsightMentionExtractedEvent {
    return InsightMentionExtractedEventFromJSONTyped(json, false);
}

export function InsightMentionExtractedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightMentionExtractedEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'domain': json['domain'],
        'email': json['email'],
        'emailMoved': json['emailMoved'],
        'index': json['index'],
        'kind': json['kind'],
        'sourceType': json['sourceType'],
        'sourceUrl': json['sourceUrl'],
        'total': json['total'],
    };
}

export function InsightMentionExtractedEventToJSON(json: any): InsightMentionExtractedEvent {
    return InsightMentionExtractedEventToJSONTyped(json, false);
}

export function InsightMentionExtractedEventToJSONTyped(value?: InsightMentionExtractedEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'domain': value['domain'],
        'email': value['email'],
        'emailMoved': value['emailMoved'],
        'index': value['index'],
        'kind': value['kind'],
        'sourceType': value['sourceType'],
        'sourceUrl': value['sourceUrl'],
        'total': value['total'],
    };
}

