/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InsightPlatformProgressEvent
 */
export interface InsightPlatformProgressEvent {
    [key: string]: any | any;
    /**
     * 
     */
    email: string;
    /**
     * Known values: platform_progress. Clients preserve future values.
     */
    kind: string;
    /**
     * 
     */
    progress: number;
}

/**
 * Check if a given object implements the InsightPlatformProgressEvent interface.
 */
export function instanceOfInsightPlatformProgressEvent(value: object): value is InsightPlatformProgressEvent {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    return true;
}

export function InsightPlatformProgressEventFromJSON(json: any): InsightPlatformProgressEvent {
    return InsightPlatformProgressEventFromJSONTyped(json, false);
}

export function InsightPlatformProgressEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightPlatformProgressEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'email': json['email'],
        'kind': json['kind'],
        'progress': json['progress'],
    };
}

export function InsightPlatformProgressEventToJSON(json: any): InsightPlatformProgressEvent {
    return InsightPlatformProgressEventToJSONTyped(json, false);
}

export function InsightPlatformProgressEventToJSONTyped(value?: InsightPlatformProgressEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'email': value['email'],
        'kind': value['kind'],
        'progress': value['progress'],
    };
}

