/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InsightGeo
 */
export interface InsightGeo {
    [key: string]: any | any;
    /**
     * 
     */
    lat?: number;
    /**
     * 
     */
    lon?: number;
}

/**
 * Check if a given object implements the InsightGeo interface.
 */
export function instanceOfInsightGeo(value: object): value is InsightGeo {
    return true;
}

export function InsightGeoFromJSON(json: any): InsightGeo {
    return InsightGeoFromJSONTyped(json, false);
}

export function InsightGeoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightGeo {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
    };
}

export function InsightGeoToJSON(json: any): InsightGeo {
    return InsightGeoToJSONTyped(json, false);
}

export function InsightGeoToJSONTyped(value?: InsightGeo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'lat': value['lat'],
        'lon': value['lon'],
    };
}

