/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IntegrationConnectionTest
 */
export interface IntegrationConnectionTest {
    [key: string]: any | any;
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    latencyMs: number;
    /**
     * 
     */
    providerAccountId?: string;
    /**
     * Known values: succeeded, failed. Clients preserve future values.
     */
    state: string;
}

/**
 * Check if a given object implements the IntegrationConnectionTest interface.
 */
export function instanceOfIntegrationConnectionTest(value: object): value is IntegrationConnectionTest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('latencyMs' in value) || value['latencyMs'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function IntegrationConnectionTestFromJSON(json: any): IntegrationConnectionTest {
    return IntegrationConnectionTestFromJSONTyped(json, false);
}

export function IntegrationConnectionTestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationConnectionTest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'],
        'latencyMs': json['latencyMs'],
        'providerAccountId': json['providerAccountId'] == null ? undefined : json['providerAccountId'],
        'state': json['state'],
    };
}

export function IntegrationConnectionTestToJSON(json: any): IntegrationConnectionTest {
    return IntegrationConnectionTestToJSONTyped(json, false);
}

export function IntegrationConnectionTestToJSONTyped(value?: IntegrationConnectionTest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'code': value['code'],
        'latencyMs': value['latencyMs'],
        'providerAccountId': value['providerAccountId'],
        'state': value['state'],
    };
}

