/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IntegrationJobCounters
 */
export interface IntegrationJobCounters {
    [key: string]: any | any;
    /**
     * 
     */
    failed: number;
    /**
     * 
     */
    processed: number;
    /**
     * 
     */
    skipped: number;
    /**
     * 
     */
    succeeded: number;
}

/**
 * Check if a given object implements the IntegrationJobCounters interface.
 */
export function instanceOfIntegrationJobCounters(value: object): value is IntegrationJobCounters {
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('processed' in value) || value['processed'] === undefined) return false;
    if (!('skipped' in value) || value['skipped'] === undefined) return false;
    if (!('succeeded' in value) || value['succeeded'] === undefined) return false;
    return true;
}

export function IntegrationJobCountersFromJSON(json: any): IntegrationJobCounters {
    return IntegrationJobCountersFromJSONTyped(json, false);
}

export function IntegrationJobCountersFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationJobCounters {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'failed': json['failed'],
        'processed': json['processed'],
        'skipped': json['skipped'],
        'succeeded': json['succeeded'],
    };
}

export function IntegrationJobCountersToJSON(json: any): IntegrationJobCounters {
    return IntegrationJobCountersToJSONTyped(json, false);
}

export function IntegrationJobCountersToJSONTyped(value?: IntegrationJobCounters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'failed': value['failed'],
        'processed': value['processed'],
        'skipped': value['skipped'],
        'succeeded': value['succeeded'],
    };
}

