/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IntegrationJob } from './IntegrationJob.js';
import {
    IntegrationJobFromJSON,
    IntegrationJobFromJSONTyped,
    IntegrationJobToJSON,
    IntegrationJobToJSONTyped,
} from './IntegrationJob.js';

/**
 * 
 * @export
 * @interface IntegrationJobResponse
 */
export interface IntegrationJobResponse {
    [key: string]: any | any;
    /**
     * 
     */
    job: IntegrationJob;
}

/**
 * Check if a given object implements the IntegrationJobResponse interface.
 */
export function instanceOfIntegrationJobResponse(value: object): value is IntegrationJobResponse {
    if (!('job' in value) || value['job'] === undefined) return false;
    return true;
}

export function IntegrationJobResponseFromJSON(json: any): IntegrationJobResponse {
    return IntegrationJobResponseFromJSONTyped(json, false);
}

export function IntegrationJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'job': IntegrationJobFromJSON(json['job']),
    };
}

export function IntegrationJobResponseToJSON(json: any): IntegrationJobResponse {
    return IntegrationJobResponseToJSONTyped(json, false);
}

export function IntegrationJobResponseToJSONTyped(value?: IntegrationJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'job': IntegrationJobToJSON(value['job']),
    };
}

