/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IntegrationConnection } from './IntegrationConnection.js';
import {
    IntegrationConnectionFromJSON,
    IntegrationConnectionFromJSONTyped,
    IntegrationConnectionToJSON,
    IntegrationConnectionToJSONTyped,
} from './IntegrationConnection.js';

/**
 * 
 * @export
 * @interface IntegrationFormConnectionResponse
 */
export interface IntegrationFormConnectionResponse {
    [key: string]: any | any;
    /**
     * 
     */
    callbackConfigured: boolean;
    /**
     * 
     */
    connection: IntegrationConnection;
}

/**
 * Check if a given object implements the IntegrationFormConnectionResponse interface.
 */
export function instanceOfIntegrationFormConnectionResponse(value: object): value is IntegrationFormConnectionResponse {
    if (!('callbackConfigured' in value) || value['callbackConfigured'] === undefined) return false;
    if (!('connection' in value) || value['connection'] === undefined) return false;
    return true;
}

export function IntegrationFormConnectionResponseFromJSON(json: any): IntegrationFormConnectionResponse {
    return IntegrationFormConnectionResponseFromJSONTyped(json, false);
}

export function IntegrationFormConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationFormConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'callbackConfigured': json['callbackConfigured'],
        'connection': IntegrationConnectionFromJSON(json['connection']),
    };
}

export function IntegrationFormConnectionResponseToJSON(json: any): IntegrationFormConnectionResponse {
    return IntegrationFormConnectionResponseToJSONTyped(json, false);
}

export function IntegrationFormConnectionResponseToJSONTyped(value?: IntegrationFormConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'callbackConfigured': value['callbackConfigured'],
        'connection': IntegrationConnectionToJSON(value['connection']),
    };
}

