/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { QueuedIntegrationJob } from './QueuedIntegrationJob.js';
import {
    QueuedIntegrationJobFromJSON,
    QueuedIntegrationJobFromJSONTyped,
    QueuedIntegrationJobToJSON,
    QueuedIntegrationJobToJSONTyped,
} from './QueuedIntegrationJob.js';

/**
 * 
 * @export
 * @interface IntegrationLeadExportResponse
 */
export interface IntegrationLeadExportResponse {
    [key: string]: any | any;
    /**
     * 
     */
    job: QueuedIntegrationJob;
    /**
     * 
     */
    queuedContacts: number;
}

/**
 * Check if a given object implements the IntegrationLeadExportResponse interface.
 */
export function instanceOfIntegrationLeadExportResponse(value: object): value is IntegrationLeadExportResponse {
    if (!('job' in value) || value['job'] === undefined) return false;
    if (!('queuedContacts' in value) || value['queuedContacts'] === undefined) return false;
    return true;
}

export function IntegrationLeadExportResponseFromJSON(json: any): IntegrationLeadExportResponse {
    return IntegrationLeadExportResponseFromJSONTyped(json, false);
}

export function IntegrationLeadExportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationLeadExportResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'job': QueuedIntegrationJobFromJSON(json['job']),
        'queuedContacts': json['queuedContacts'],
    };
}

export function IntegrationLeadExportResponseToJSON(json: any): IntegrationLeadExportResponse {
    return IntegrationLeadExportResponseToJSONTyped(json, false);
}

export function IntegrationLeadExportResponseToJSONTyped(value?: IntegrationLeadExportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'job': QueuedIntegrationJobToJSON(value['job']),
        'queuedContacts': value['queuedContacts'],
    };
}

