/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IntegrationJobCounters } from './IntegrationJobCounters.js';
import {
    IntegrationJobCountersFromJSON,
    IntegrationJobCountersFromJSONTyped,
    IntegrationJobCountersToJSON,
    IntegrationJobCountersToJSONTyped,
} from './IntegrationJobCounters.js';

/**
 * 
 * @export
 * @interface IntegrationJob
 */
export interface IntegrationJob {
    [key: string]: any | any;
    /**
     * 
     */
    attempt: number;
    /**
     * 
     */
    cancellationRequested: boolean;
    /**
     * 
     */
    connectionId: string;
    /**
     * 
     */
    connectionLabel: string;
    /**
     * 
     */
    counters: IntegrationJobCounters;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    errorCode: string | null;
    /**
     * 
     */
    errorMessage: string | null;
    /**
     * 
     */
    finishedAt: string | null;
    /**
     * 
     */
    id: string;
    /**
     * Known values: crm_export, crm_delete, crm_activity, sheet_preview, sheet_writeback, notification_delivery, form_ingestion. Clients preserve future values.
     */
    jobType: string;
    /**
     * 
     */
    maxAttempts: number;
    /**
     * 
     */
    provider: string;
    /**
     * 
     */
    startedAt: string | null;
    /**
     * Known values: pending, running, succeeded, failed, cancelled. Clients preserve future values.
     */
    status: string;
    /**
     * 
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the IntegrationJob interface.
 */
export function instanceOfIntegrationJob(value: object): value is IntegrationJob {
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('cancellationRequested' in value) || value['cancellationRequested'] === undefined) return false;
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('connectionLabel' in value) || value['connectionLabel'] === undefined) return false;
    if (!('counters' in value) || value['counters'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    if (!('finishedAt' in value) || value['finishedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('jobType' in value) || value['jobType'] === undefined) return false;
    if (!('maxAttempts' in value) || value['maxAttempts'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function IntegrationJobFromJSON(json: any): IntegrationJob {
    return IntegrationJobFromJSONTyped(json, false);
}

export function IntegrationJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationJob {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'attempt': json['attempt'],
        'cancellationRequested': json['cancellationRequested'],
        'connectionId': json['connectionId'],
        'connectionLabel': json['connectionLabel'],
        'counters': IntegrationJobCountersFromJSON(json['counters']),
        'createdAt': json['createdAt'],
        'errorCode': json['errorCode'],
        'errorMessage': json['errorMessage'],
        'finishedAt': json['finishedAt'],
        'id': json['id'],
        'jobType': json['jobType'],
        'maxAttempts': json['maxAttempts'],
        'provider': json['provider'],
        'startedAt': json['startedAt'],
        'status': json['status'],
        'updatedAt': json['updatedAt'],
    };
}

export function IntegrationJobToJSON(json: any): IntegrationJob {
    return IntegrationJobToJSONTyped(json, false);
}

export function IntegrationJobToJSONTyped(value?: IntegrationJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'attempt': value['attempt'],
        'cancellationRequested': value['cancellationRequested'],
        'connectionId': value['connectionId'],
        'connectionLabel': value['connectionLabel'],
        'counters': IntegrationJobCountersToJSON(value['counters']),
        'createdAt': value['createdAt'],
        'errorCode': value['errorCode'],
        'errorMessage': value['errorMessage'],
        'finishedAt': value['finishedAt'],
        'id': value['id'],
        'jobType': value['jobType'],
        'maxAttempts': value['maxAttempts'],
        'provider': value['provider'],
        'startedAt': value['startedAt'],
        'status': value['status'],
        'updatedAt': value['updatedAt'],
    };
}

