/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CapabilityDomainSearchContactsInner } from './CapabilityDomainSearchContactsInner.js';
import {
    CapabilityDomainSearchContactsInnerFromJSON,
    CapabilityDomainSearchContactsInnerFromJSONTyped,
    CapabilityDomainSearchContactsInnerToJSON,
    CapabilityDomainSearchContactsInnerToJSONTyped,
} from './CapabilityDomainSearchContactsInner.js';
import type { IntegrationCapabilityResponseOutputNonNull } from './IntegrationCapabilityResponseOutputNonNull.js';
import {
    IntegrationCapabilityResponseOutputNonNullFromJSON,
    IntegrationCapabilityResponseOutputNonNullFromJSONTyped,
    IntegrationCapabilityResponseOutputNonNullToJSON,
    IntegrationCapabilityResponseOutputNonNullToJSONTyped,
} from './IntegrationCapabilityResponseOutputNonNull.js';
import type { CapabilityEmailVerifiedDetails } from './CapabilityEmailVerifiedDetails.js';
import {
    CapabilityEmailVerifiedDetailsFromJSON,
    CapabilityEmailVerifiedDetailsFromJSONTyped,
    CapabilityEmailVerifiedDetailsToJSON,
    CapabilityEmailVerifiedDetailsToJSONTyped,
} from './CapabilityEmailVerifiedDetails.js';

/**
 * Null in preview mode; otherwise the result for the selected capability.
 * @export
 * @interface IntegrationCapabilityResponseOutput
 */
export interface IntegrationCapabilityResponseOutput {
    /**
     * 
     */
    confidence: number;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    freshness: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    checkedAt: string;
    /**
     * 
     */
    details: CapabilityEmailVerifiedDetails;
    /**
     * 
     */
    score: number;
    /**
     * 
     */
    sources: number;
    /**
     * 
     */
    contacts: Array<CapabilityDomainSearchContactsInner>;
    /**
     * 
     */
    domain: string;
    /**
     * 
     */
    organization?: string;
}

/**
 * Check if a given object implements the IntegrationCapabilityResponseOutput interface.
 */
export function instanceOfIntegrationCapabilityResponseOutput(value: object): value is IntegrationCapabilityResponseOutput {
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('freshness' in value) || value['freshness'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('checkedAt' in value) || value['checkedAt'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('sources' in value) || value['sources'] === undefined) return false;
    if (!('contacts' in value) || value['contacts'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function IntegrationCapabilityResponseOutputFromJSON(json: any): IntegrationCapabilityResponseOutput {
    return IntegrationCapabilityResponseOutputFromJSONTyped(json, false);
}

export function IntegrationCapabilityResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationCapabilityResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'confidence': json['confidence'],
        'email': json['email'],
        'freshness': json['freshness'],
        'status': json['status'],
        'checkedAt': json['checkedAt'],
        'details': CapabilityEmailVerifiedDetailsFromJSON(json['details']),
        'score': json['score'],
        'sources': json['sources'],
        'contacts': ((json['contacts'] as Array<any>).map(CapabilityDomainSearchContactsInnerFromJSON)),
        'domain': json['domain'],
        'organization': json['organization'] == null ? undefined : json['organization'],
    };
}

export function IntegrationCapabilityResponseOutputToJSON(json: any): IntegrationCapabilityResponseOutput {
    return IntegrationCapabilityResponseOutputToJSONTyped(json, false);
}

export function IntegrationCapabilityResponseOutputToJSONTyped(value?: IntegrationCapabilityResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'confidence': value['confidence'],
        'email': value['email'],
        'freshness': value['freshness'],
        'status': value['status'],
        'checkedAt': value['checkedAt'],
        'details': CapabilityEmailVerifiedDetailsToJSON(value['details']),
        'score': value['score'],
        'sources': value['sources'],
        'contacts': ((value['contacts'] as Array<any>).map(CapabilityDomainSearchContactsInnerToJSON)),
        'domain': value['domain'],
        'organization': value['organization'],
    };
}

