/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IntegrationProviderListProvidersInnerConnectability } from './IntegrationProviderListProvidersInnerConnectability.js';
import {
    IntegrationProviderListProvidersInnerConnectabilityFromJSON,
    IntegrationProviderListProvidersInnerConnectabilityFromJSONTyped,
    IntegrationProviderListProvidersInnerConnectabilityToJSON,
    IntegrationProviderListProvidersInnerConnectabilityToJSONTyped,
} from './IntegrationProviderListProvidersInnerConnectability.js';
import type { IntegrationProviderListProvidersInnerReadiness } from './IntegrationProviderListProvidersInnerReadiness.js';
import {
    IntegrationProviderListProvidersInnerReadinessFromJSON,
    IntegrationProviderListProvidersInnerReadinessFromJSONTyped,
    IntegrationProviderListProvidersInnerReadinessToJSON,
    IntegrationProviderListProvidersInnerReadinessToJSONTyped,
} from './IntegrationProviderListProvidersInnerReadiness.js';

/**
 * 
 * @export
 * @interface IntegrationProviderListProvidersInner
 */
export interface IntegrationProviderListProvidersInner {
    /**
     * 
     */
    auth: string;
    /**
     * 
     */
    category: string;
    /**
     * 
     */
    connectability: IntegrationProviderListProvidersInnerConnectability;
    /**
     * 
     */
    implemented: boolean;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    provider: string;
    /**
     * 
     */
    readiness: IntegrationProviderListProvidersInnerReadiness;
}

/**
 * Check if a given object implements the IntegrationProviderListProvidersInner interface.
 */
export function instanceOfIntegrationProviderListProvidersInner(value: object): value is IntegrationProviderListProvidersInner {
    if (!('auth' in value) || value['auth'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('connectability' in value) || value['connectability'] === undefined) return false;
    if (!('implemented' in value) || value['implemented'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('readiness' in value) || value['readiness'] === undefined) return false;
    return true;
}

export function IntegrationProviderListProvidersInnerFromJSON(json: any): IntegrationProviderListProvidersInner {
    return IntegrationProviderListProvidersInnerFromJSONTyped(json, false);
}

export function IntegrationProviderListProvidersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationProviderListProvidersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'auth': json['auth'],
        'category': json['category'],
        'connectability': IntegrationProviderListProvidersInnerConnectabilityFromJSON(json['connectability']),
        'implemented': json['implemented'],
        'name': json['name'],
        'provider': json['provider'],
        'readiness': IntegrationProviderListProvidersInnerReadinessFromJSON(json['readiness']),
    };
}

export function IntegrationProviderListProvidersInnerToJSON(json: any): IntegrationProviderListProvidersInner {
    return IntegrationProviderListProvidersInnerToJSONTyped(json, false);
}

export function IntegrationProviderListProvidersInnerToJSONTyped(value?: IntegrationProviderListProvidersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth': value['auth'],
        'category': value['category'],
        'connectability': IntegrationProviderListProvidersInnerConnectabilityToJSON(value['connectability']),
        'implemented': value['implemented'],
        'name': value['name'],
        'provider': value['provider'],
        'readiness': IntegrationProviderListProvidersInnerReadinessToJSON(value['readiness']),
    };
}

