/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LeadExportTooLargeError
 */
export interface LeadExportTooLargeError {
    [key: string]: any | any;
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    error: string;
    /**
     * 
     */
    limit: number;
}

/**
 * Check if a given object implements the LeadExportTooLargeError interface.
 */
export function instanceOfLeadExportTooLargeError(value: object): value is LeadExportTooLargeError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function LeadExportTooLargeErrorFromJSON(json: any): LeadExportTooLargeError {
    return LeadExportTooLargeErrorFromJSONTyped(json, false);
}

export function LeadExportTooLargeErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeadExportTooLargeError {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'],
        'error': json['error'],
        'limit': json['limit'],
    };
}

export function LeadExportTooLargeErrorToJSON(json: any): LeadExportTooLargeError {
    return LeadExportTooLargeErrorToJSONTyped(json, false);
}

export function LeadExportTooLargeErrorToJSONTyped(value?: LeadExportTooLargeError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'code': value['code'],
        'error': value['error'],
        'limit': value['limit'],
    };
}

