/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LinkMcpIdentityRequest
 */
export interface LinkMcpIdentityRequest {
    /**
     * 
     */
    scopes?: Set<LinkMcpIdentityRequestScopesEnum>;
}


/**
 * @export
 */
export const LinkMcpIdentityRequestScopesEnum = {
    EmailFind: 'email:find',
    EmailVerify: 'email:verify',
    DomainSearch: 'domain:search',
    ProductRead: 'product:read',
    ProductWrite: 'product:write',
    CampaignsRead: 'campaigns:read',
    CampaignsWrite: 'campaigns:write',
    AccountRead: 'account:read',
} as const;
export type LinkMcpIdentityRequestScopesEnum = typeof LinkMcpIdentityRequestScopesEnum[keyof typeof LinkMcpIdentityRequestScopesEnum];


/**
 * Check if a given object implements the LinkMcpIdentityRequest interface.
 */
export function instanceOfLinkMcpIdentityRequest(value: object): value is LinkMcpIdentityRequest {
    return true;
}

export function LinkMcpIdentityRequestFromJSON(json: any): LinkMcpIdentityRequest {
    return LinkMcpIdentityRequestFromJSONTyped(json, false);
}

export function LinkMcpIdentityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkMcpIdentityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'scopes': json['scopes'] == null ? undefined : new Set(json['scopes']),
    };
}

export function LinkMcpIdentityRequestToJSON(json: any): LinkMcpIdentityRequest {
    return LinkMcpIdentityRequestToJSONTyped(json, false);
}

export function LinkMcpIdentityRequestToJSONTyped(value?: LinkMcpIdentityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scopes': value['scopes'] == null ? undefined : Array.from(value['scopes'] as Set<any>),
    };
}

