/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailMessageRecord } from './MailMessageRecord.js';
import {
    MailMessageRecordFromJSON,
    MailMessageRecordFromJSONTyped,
    MailMessageRecordToJSON,
    MailMessageRecordToJSONTyped,
} from './MailMessageRecord.js';

/**
 * 
 * @export
 * @interface MailPostInboxByMessageIdReplyResponse200
 */
export interface MailPostInboxByMessageIdReplyResponse200 {
    /**
     * 
     */
    message: MailMessageRecord;
}

/**
 * Check if a given object implements the MailPostInboxByMessageIdReplyResponse200 interface.
 */
export function instanceOfMailPostInboxByMessageIdReplyResponse200(value: object): value is MailPostInboxByMessageIdReplyResponse200 {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function MailPostInboxByMessageIdReplyResponse200FromJSON(json: any): MailPostInboxByMessageIdReplyResponse200 {
    return MailPostInboxByMessageIdReplyResponse200FromJSONTyped(json, false);
}

export function MailPostInboxByMessageIdReplyResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostInboxByMessageIdReplyResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'message': MailMessageRecordFromJSON(json['message']),
    };
}

export function MailPostInboxByMessageIdReplyResponse200ToJSON(json: any): MailPostInboxByMessageIdReplyResponse200 {
    return MailPostInboxByMessageIdReplyResponse200ToJSONTyped(json, false);
}

export function MailPostInboxByMessageIdReplyResponse200ToJSONTyped(value?: MailPostInboxByMessageIdReplyResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': MailMessageRecordToJSON(value['message']),
    };
}

