/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailGetWebhooksResponse200SubscriptionsInner } from './MailGetWebhooksResponse200SubscriptionsInner.js';
import {
    MailGetWebhooksResponse200SubscriptionsInnerFromJSON,
    MailGetWebhooksResponse200SubscriptionsInnerFromJSONTyped,
    MailGetWebhooksResponse200SubscriptionsInnerToJSON,
    MailGetWebhooksResponse200SubscriptionsInnerToJSONTyped,
} from './MailGetWebhooksResponse200SubscriptionsInner.js';

/**
 * 
 * @export
 * @interface MailPostWebhooksBySubscriptionIdRotateSecretResponse200
 */
export interface MailPostWebhooksBySubscriptionIdRotateSecretResponse200 {
    /**
     * 
     */
    signingSecret: string;
    /**
     * 
     */
    subscription: MailGetWebhooksResponse200SubscriptionsInner;
}

/**
 * Check if a given object implements the MailPostWebhooksBySubscriptionIdRotateSecretResponse200 interface.
 */
export function instanceOfMailPostWebhooksBySubscriptionIdRotateSecretResponse200(value: object): value is MailPostWebhooksBySubscriptionIdRotateSecretResponse200 {
    if (!('signingSecret' in value) || value['signingSecret'] === undefined) return false;
    if (!('subscription' in value) || value['subscription'] === undefined) return false;
    return true;
}

export function MailPostWebhooksBySubscriptionIdRotateSecretResponse200FromJSON(json: any): MailPostWebhooksBySubscriptionIdRotateSecretResponse200 {
    return MailPostWebhooksBySubscriptionIdRotateSecretResponse200FromJSONTyped(json, false);
}

export function MailPostWebhooksBySubscriptionIdRotateSecretResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostWebhooksBySubscriptionIdRotateSecretResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'signingSecret': json['signingSecret'],
        'subscription': MailGetWebhooksResponse200SubscriptionsInnerFromJSON(json['subscription']),
    };
}

export function MailPostWebhooksBySubscriptionIdRotateSecretResponse200ToJSON(json: any): MailPostWebhooksBySubscriptionIdRotateSecretResponse200 {
    return MailPostWebhooksBySubscriptionIdRotateSecretResponse200ToJSONTyped(json, false);
}

export function MailPostWebhooksBySubscriptionIdRotateSecretResponse200ToJSONTyped(value?: MailPostWebhooksBySubscriptionIdRotateSecretResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signingSecret': value['signingSecret'],
        'subscription': MailGetWebhooksResponse200SubscriptionsInnerToJSON(value['subscription']),
    };
}

