/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
 * @export
 * @interface MailPostDeliverabilityMailboxesByMailboxIdRequest
 */
export interface MailPostDeliverabilityMailboxesByMailboxIdRequest {
    /**
     * 
     */
    rampEnabled: boolean;
    /**
     * 
     */
    rampIntervalHours: number;
    /**
     * 
     */
    rampStep: number;
    /**
     * 
     */
    startingDailyLimit: number;
    /**
     * 
     */
    targetDailyLimit: number;
}

/**
 * Check if a given object implements the MailPostDeliverabilityMailboxesByMailboxIdRequest interface.
 */
export function instanceOfMailPostDeliverabilityMailboxesByMailboxIdRequest(value: object): value is MailPostDeliverabilityMailboxesByMailboxIdRequest {
    if (!('rampEnabled' in value) || value['rampEnabled'] === undefined) return false;
    if (!('rampIntervalHours' in value) || value['rampIntervalHours'] === undefined) return false;
    if (!('rampStep' in value) || value['rampStep'] === undefined) return false;
    if (!('startingDailyLimit' in value) || value['startingDailyLimit'] === undefined) return false;
    if (!('targetDailyLimit' in value) || value['targetDailyLimit'] === undefined) return false;
    return true;
}

export function MailPostDeliverabilityMailboxesByMailboxIdRequestFromJSON(json: any): MailPostDeliverabilityMailboxesByMailboxIdRequest {
    return MailPostDeliverabilityMailboxesByMailboxIdRequestFromJSONTyped(json, false);
}

export function MailPostDeliverabilityMailboxesByMailboxIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostDeliverabilityMailboxesByMailboxIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rampEnabled': json['rampEnabled'],
        'rampIntervalHours': json['rampIntervalHours'],
        'rampStep': json['rampStep'],
        'startingDailyLimit': json['startingDailyLimit'],
        'targetDailyLimit': json['targetDailyLimit'],
    };
}

export function MailPostDeliverabilityMailboxesByMailboxIdRequestToJSON(json: any): MailPostDeliverabilityMailboxesByMailboxIdRequest {
    return MailPostDeliverabilityMailboxesByMailboxIdRequestToJSONTyped(json, false);
}

export function MailPostDeliverabilityMailboxesByMailboxIdRequestToJSONTyped(value?: MailPostDeliverabilityMailboxesByMailboxIdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rampEnabled': value['rampEnabled'],
        'rampIntervalHours': value['rampIntervalHours'],
        'rampStep': value['rampStep'],
        'startingDailyLimit': value['startingDailyLimit'],
        'targetDailyLimit': value['targetDailyLimit'],
    };
}

