/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailDeleteTrackingDomainResponse200
 */
export interface MailDeleteTrackingDomainResponse200 {
    /**
     * 
     */
    removed: boolean;
}

/**
 * Check if a given object implements the MailDeleteTrackingDomainResponse200 interface.
 */
export function instanceOfMailDeleteTrackingDomainResponse200(value: object): value is MailDeleteTrackingDomainResponse200 {
    if (!('removed' in value) || value['removed'] === undefined) return false;
    return true;
}

export function MailDeleteTrackingDomainResponse200FromJSON(json: any): MailDeleteTrackingDomainResponse200 {
    return MailDeleteTrackingDomainResponse200FromJSONTyped(json, false);
}

export function MailDeleteTrackingDomainResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailDeleteTrackingDomainResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'removed': json['removed'],
    };
}

export function MailDeleteTrackingDomainResponse200ToJSON(json: any): MailDeleteTrackingDomainResponse200 {
    return MailDeleteTrackingDomainResponse200ToJSONTyped(json, false);
}

export function MailDeleteTrackingDomainResponse200ToJSONTyped(value?: MailDeleteTrackingDomainResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'removed': value['removed'],
    };
}

