/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailCadenceWorkflowExperimentVariant } from './MailCadenceWorkflowExperimentVariant.js';
import {
    MailCadenceWorkflowExperimentVariantFromJSON,
    MailCadenceWorkflowExperimentVariantFromJSONTyped,
    MailCadenceWorkflowExperimentVariantToJSON,
    MailCadenceWorkflowExperimentVariantToJSONTyped,
} from './MailCadenceWorkflowExperimentVariant.js';

/**
 * 
 * @export
 * @interface MailCadenceWorkflowExperiment
 */
export interface MailCadenceWorkflowExperiment {
    /**
     * 
     */
    assignmentUnit: MailCadenceWorkflowExperimentAssignmentUnitEnum;
    /**
     * 
     */
    attributionWindowMs?: number;
    /**
     * 
     */
    guardrailMetrics?: Array<string>;
    /**
     * 
     */
    hypothesis?: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    minimumRuntimeMs?: number;
    /**
     * 
     */
    minimumSampleSize?: number;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    primaryMetric?: string;
    /**
     * 
     */
    variants: Array<MailCadenceWorkflowExperimentVariant>;
}


/**
 * @export
 */
export const MailCadenceWorkflowExperimentAssignmentUnitEnum = {
    Contact: 'contact',
} as const;
export type MailCadenceWorkflowExperimentAssignmentUnitEnum = typeof MailCadenceWorkflowExperimentAssignmentUnitEnum[keyof typeof MailCadenceWorkflowExperimentAssignmentUnitEnum];


/**
 * Check if a given object implements the MailCadenceWorkflowExperiment interface.
 */
export function instanceOfMailCadenceWorkflowExperiment(value: object): value is MailCadenceWorkflowExperiment {
    if (!('assignmentUnit' in value) || value['assignmentUnit'] === undefined) return false;
    if (value['assignmentUnit'] !== 'contact') return false;
    
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('variants' in value) || value['variants'] === undefined) return false;
    return true;
}

export function MailCadenceWorkflowExperimentFromJSON(json: any): MailCadenceWorkflowExperiment {
    return MailCadenceWorkflowExperimentFromJSONTyped(json, false);
}

export function MailCadenceWorkflowExperimentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailCadenceWorkflowExperiment {
    if (json == null) {
        return json;
    }
    return {
        
        'assignmentUnit': json['assignmentUnit'],
        'attributionWindowMs': json['attributionWindowMs'] == null ? undefined : json['attributionWindowMs'],
        'guardrailMetrics': json['guardrailMetrics'] == null ? undefined : json['guardrailMetrics'],
        'hypothesis': json['hypothesis'] == null ? undefined : json['hypothesis'],
        'id': json['id'],
        'minimumRuntimeMs': json['minimumRuntimeMs'] == null ? undefined : json['minimumRuntimeMs'],
        'minimumSampleSize': json['minimumSampleSize'] == null ? undefined : json['minimumSampleSize'],
        'name': json['name'],
        'primaryMetric': json['primaryMetric'] == null ? undefined : json['primaryMetric'],
        'variants': ((json['variants'] as Array<any>).map(MailCadenceWorkflowExperimentVariantFromJSON)),
    };
}

export function MailCadenceWorkflowExperimentToJSON(json: any): MailCadenceWorkflowExperiment {
    return MailCadenceWorkflowExperimentToJSONTyped(json, false);
}

export function MailCadenceWorkflowExperimentToJSONTyped(value?: MailCadenceWorkflowExperiment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignmentUnit': value['assignmentUnit'],
        'attributionWindowMs': value['attributionWindowMs'],
        'guardrailMetrics': value['guardrailMetrics'],
        'hypothesis': value['hypothesis'],
        'id': value['id'],
        'minimumRuntimeMs': value['minimumRuntimeMs'],
        'minimumSampleSize': value['minimumSampleSize'],
        'name': value['name'],
        'primaryMetric': value['primaryMetric'],
        'variants': ((value['variants'] as Array<any>).map(MailCadenceWorkflowExperimentVariantToJSON)),
    };
}

