/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailContactRecord
 */
export interface MailContactRecord {
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    customFields: { [key: string]: string; };
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the MailContactRecord interface.
 */
export function instanceOfMailContactRecord(value: object): value is MailContactRecord {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('customFields' in value) || value['customFields'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MailContactRecordFromJSON(json: any): MailContactRecord {
    return MailContactRecordFromJSONTyped(json, false);
}

export function MailContactRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailContactRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'customFields': json['customFields'],
        'email': json['email'],
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tenantId': json['tenantId'],
        'updatedAt': json['updatedAt'],
    };
}

export function MailContactRecordToJSON(json: any): MailContactRecord {
    return MailContactRecordToJSONTyped(json, false);
}

export function MailContactRecordToJSONTyped(value?: MailContactRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'customFields': value['customFields'],
        'email': value['email'],
        'id': value['id'],
        'name': value['name'],
        'tenantId': value['tenantId'],
        'updatedAt': value['updatedAt'],
    };
}

