/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostPortfolioTeamsRequest
 */
export interface MailPostPortfolioTeamsRequest {
    /**
     * 
     */
    teamId: string;
}

/**
 * Check if a given object implements the MailPostPortfolioTeamsRequest interface.
 */
export function instanceOfMailPostPortfolioTeamsRequest(value: object): value is MailPostPortfolioTeamsRequest {
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    return true;
}

export function MailPostPortfolioTeamsRequestFromJSON(json: any): MailPostPortfolioTeamsRequest {
    return MailPostPortfolioTeamsRequestFromJSONTyped(json, false);
}

export function MailPostPortfolioTeamsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostPortfolioTeamsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['teamId'],
    };
}

export function MailPostPortfolioTeamsRequestToJSON(json: any): MailPostPortfolioTeamsRequest {
    return MailPostPortfolioTeamsRequestToJSONTyped(json, false);
}

export function MailPostPortfolioTeamsRequestToJSONTyped(value?: MailPostPortfolioTeamsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'teamId': value['teamId'],
    };
}

