/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailReplyAutomationRule } from './MailReplyAutomationRule.js';
import {
    MailReplyAutomationRuleFromJSON,
    MailReplyAutomationRuleFromJSONTyped,
    MailReplyAutomationRuleToJSON,
    MailReplyAutomationRuleToJSONTyped,
} from './MailReplyAutomationRule.js';

/**
 * 
 * @export
 * @interface MailPostReplyAutomationsResponse200
 */
export interface MailPostReplyAutomationsResponse200 {
    /**
     * 
     */
    automation: MailReplyAutomationRule;
}

/**
 * Check if a given object implements the MailPostReplyAutomationsResponse200 interface.
 */
export function instanceOfMailPostReplyAutomationsResponse200(value: object): value is MailPostReplyAutomationsResponse200 {
    if (!('automation' in value) || value['automation'] === undefined) return false;
    return true;
}

export function MailPostReplyAutomationsResponse200FromJSON(json: any): MailPostReplyAutomationsResponse200 {
    return MailPostReplyAutomationsResponse200FromJSONTyped(json, false);
}

export function MailPostReplyAutomationsResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostReplyAutomationsResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'automation': MailReplyAutomationRuleFromJSON(json['automation']),
    };
}

export function MailPostReplyAutomationsResponse200ToJSON(json: any): MailPostReplyAutomationsResponse200 {
    return MailPostReplyAutomationsResponse200ToJSONTyped(json, false);
}

export function MailPostReplyAutomationsResponse200ToJSONTyped(value?: MailPostReplyAutomationsResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'automation': MailReplyAutomationRuleToJSON(value['automation']),
    };
}

