/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostDeliverabilityPoolsRequest
 */
export interface MailPostDeliverabilityPoolsRequest {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    strategy: MailPostDeliverabilityPoolsRequestStrategyEnum;
}


/**
 * @export
 */
export const MailPostDeliverabilityPoolsRequestStrategyEnum = {
    RoundRobin: 'round_robin',
    CapacityWeighted: 'capacity_weighted',
} as const;
export type MailPostDeliverabilityPoolsRequestStrategyEnum = typeof MailPostDeliverabilityPoolsRequestStrategyEnum[keyof typeof MailPostDeliverabilityPoolsRequestStrategyEnum];


/**
 * Check if a given object implements the MailPostDeliverabilityPoolsRequest interface.
 */
export function instanceOfMailPostDeliverabilityPoolsRequest(value: object): value is MailPostDeliverabilityPoolsRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('strategy' in value) || value['strategy'] === undefined) return false;
    return true;
}

export function MailPostDeliverabilityPoolsRequestFromJSON(json: any): MailPostDeliverabilityPoolsRequest {
    return MailPostDeliverabilityPoolsRequestFromJSONTyped(json, false);
}

export function MailPostDeliverabilityPoolsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostDeliverabilityPoolsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'strategy': json['strategy'],
    };
}

export function MailPostDeliverabilityPoolsRequestToJSON(json: any): MailPostDeliverabilityPoolsRequest {
    return MailPostDeliverabilityPoolsRequestToJSONTyped(json, false);
}

export function MailPostDeliverabilityPoolsRequestToJSONTyped(value?: MailPostDeliverabilityPoolsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'strategy': value['strategy'],
    };
}

