/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailSendingWindow
 */
export interface MailSendingWindow {
    /**
     * 
     */
    endMinute: number;
    /**
     * 
     */
    startMinute: number;
    /**
     * 
     */
    weekdays: Array<string>;
}

/**
 * Check if a given object implements the MailSendingWindow interface.
 */
export function instanceOfMailSendingWindow(value: object): value is MailSendingWindow {
    if (!('endMinute' in value) || value['endMinute'] === undefined) return false;
    if (!('startMinute' in value) || value['startMinute'] === undefined) return false;
    if (!('weekdays' in value) || value['weekdays'] === undefined) return false;
    return true;
}

export function MailSendingWindowFromJSON(json: any): MailSendingWindow {
    return MailSendingWindowFromJSONTyped(json, false);
}

export function MailSendingWindowFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailSendingWindow {
    if (json == null) {
        return json;
    }
    return {
        
        'endMinute': json['endMinute'],
        'startMinute': json['startMinute'],
        'weekdays': json['weekdays'],
    };
}

export function MailSendingWindowToJSON(json: any): MailSendingWindow {
    return MailSendingWindowToJSONTyped(json, false);
}

export function MailSendingWindowToJSONTyped(value?: MailSendingWindow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endMinute': value['endMinute'],
        'startMinute': value['startMinute'],
        'weekdays': value['weekdays'],
    };
}

