/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailExperimentReport } from './MailExperimentReport.js';
import {
    MailExperimentReportFromJSON,
    MailExperimentReportFromJSONTyped,
    MailExperimentReportToJSON,
    MailExperimentReportToJSONTyped,
} from './MailExperimentReport.js';

/**
 * 
 * @export
 * @interface MailGetExperimentsOverviewResponse200
 */
export interface MailGetExperimentsOverviewResponse200 {
    /**
     * 
     */
    results: Array<MailExperimentReport>;
}

/**
 * Check if a given object implements the MailGetExperimentsOverviewResponse200 interface.
 */
export function instanceOfMailGetExperimentsOverviewResponse200(value: object): value is MailGetExperimentsOverviewResponse200 {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function MailGetExperimentsOverviewResponse200FromJSON(json: any): MailGetExperimentsOverviewResponse200 {
    return MailGetExperimentsOverviewResponse200FromJSONTyped(json, false);
}

export function MailGetExperimentsOverviewResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailGetExperimentsOverviewResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(MailExperimentReportFromJSON)),
    };
}

export function MailGetExperimentsOverviewResponse200ToJSON(json: any): MailGetExperimentsOverviewResponse200 {
    return MailGetExperimentsOverviewResponse200ToJSONTyped(json, false);
}

export function MailGetExperimentsOverviewResponse200ToJSONTyped(value?: MailGetExperimentsOverviewResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(MailExperimentReportToJSON)),
    };
}

