/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailCadenceDefinition } from './MailCadenceDefinition.js';
import {
    MailCadenceDefinitionFromJSON,
    MailCadenceDefinitionFromJSONTyped,
    MailCadenceDefinitionToJSON,
    MailCadenceDefinitionToJSONTyped,
} from './MailCadenceDefinition.js';

/**
 * 
 * @export
 * @interface MailPostCadencesResponse200
 */
export interface MailPostCadencesResponse200 {
    /**
     * 
     */
    cadence: MailCadenceDefinition;
}

/**
 * Check if a given object implements the MailPostCadencesResponse200 interface.
 */
export function instanceOfMailPostCadencesResponse200(value: object): value is MailPostCadencesResponse200 {
    if (!('cadence' in value) || value['cadence'] === undefined) return false;
    return true;
}

export function MailPostCadencesResponse200FromJSON(json: any): MailPostCadencesResponse200 {
    return MailPostCadencesResponse200FromJSONTyped(json, false);
}

export function MailPostCadencesResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCadencesResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'cadence': MailCadenceDefinitionFromJSON(json['cadence']),
    };
}

export function MailPostCadencesResponse200ToJSON(json: any): MailPostCadencesResponse200 {
    return MailPostCadencesResponse200ToJSONTyped(json, false);
}

export function MailPostCadencesResponse200ToJSONTyped(value?: MailPostCadencesResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cadence': MailCadenceDefinitionToJSON(value['cadence']),
    };
}

