/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostMessagesRequestTo
 */
export interface MailPostMessagesRequestTo {
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    name?: string;
}

/**
 * Check if a given object implements the MailPostMessagesRequestTo interface.
 */
export function instanceOfMailPostMessagesRequestTo(value: object): value is MailPostMessagesRequestTo {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function MailPostMessagesRequestToFromJSON(json: any): MailPostMessagesRequestTo {
    return MailPostMessagesRequestToFromJSONTyped(json, false);
}

export function MailPostMessagesRequestToFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostMessagesRequestTo {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MailPostMessagesRequestToToJSON(json: any): MailPostMessagesRequestTo {
    return MailPostMessagesRequestToToJSONTyped(json, false);
}

export function MailPostMessagesRequestToToJSONTyped(value?: MailPostMessagesRequestTo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
    };
}

