/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailQuotaRule } from './MailQuotaRule.js';
import {
    MailQuotaRuleFromJSON,
    MailQuotaRuleFromJSONTyped,
    MailQuotaRuleToJSON,
    MailQuotaRuleToJSONTyped,
} from './MailQuotaRule.js';
import type { MailSendingWindow } from './MailSendingWindow.js';
import {
    MailSendingWindowFromJSON,
    MailSendingWindowFromJSONTyped,
    MailSendingWindowToJSON,
    MailSendingWindowToJSONTyped,
} from './MailSendingWindow.js';

/**
 * 
 * @export
 * @interface MailMessagePolicyInput
 */
export interface MailMessagePolicyInput {
    /**
     * 
     */
    domainQuotas?: Array<MailQuotaRule>;
    /**
     * 
     */
    mailboxQuotas?: Array<MailQuotaRule>;
    /**
     * 
     */
    recipientCooldownMs?: number;
    /**
     * 
     */
    recipientQuotas?: Array<MailQuotaRule>;
    /**
     * 
     */
    sendingWindows?: Array<MailSendingWindow>;
    /**
     * 
     */
    tenantQuotas?: Array<MailQuotaRule>;
    /**
     * 
     */
    timeZone?: string;
}

/**
 * Check if a given object implements the MailMessagePolicyInput interface.
 */
export function instanceOfMailMessagePolicyInput(value: object): value is MailMessagePolicyInput {
    return true;
}

export function MailMessagePolicyInputFromJSON(json: any): MailMessagePolicyInput {
    return MailMessagePolicyInputFromJSONTyped(json, false);
}

export function MailMessagePolicyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMessagePolicyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'domainQuotas': json['domainQuotas'] == null ? undefined : ((json['domainQuotas'] as Array<any>).map(MailQuotaRuleFromJSON)),
        'mailboxQuotas': json['mailboxQuotas'] == null ? undefined : ((json['mailboxQuotas'] as Array<any>).map(MailQuotaRuleFromJSON)),
        'recipientCooldownMs': json['recipientCooldownMs'] == null ? undefined : json['recipientCooldownMs'],
        'recipientQuotas': json['recipientQuotas'] == null ? undefined : ((json['recipientQuotas'] as Array<any>).map(MailQuotaRuleFromJSON)),
        'sendingWindows': json['sendingWindows'] == null ? undefined : ((json['sendingWindows'] as Array<any>).map(MailSendingWindowFromJSON)),
        'tenantQuotas': json['tenantQuotas'] == null ? undefined : ((json['tenantQuotas'] as Array<any>).map(MailQuotaRuleFromJSON)),
        'timeZone': json['timeZone'] == null ? undefined : json['timeZone'],
    };
}

export function MailMessagePolicyInputToJSON(json: any): MailMessagePolicyInput {
    return MailMessagePolicyInputToJSONTyped(json, false);
}

export function MailMessagePolicyInputToJSONTyped(value?: MailMessagePolicyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domainQuotas': value['domainQuotas'] == null ? undefined : ((value['domainQuotas'] as Array<any>).map(MailQuotaRuleToJSON)),
        'mailboxQuotas': value['mailboxQuotas'] == null ? undefined : ((value['mailboxQuotas'] as Array<any>).map(MailQuotaRuleToJSON)),
        'recipientCooldownMs': value['recipientCooldownMs'],
        'recipientQuotas': value['recipientQuotas'] == null ? undefined : ((value['recipientQuotas'] as Array<any>).map(MailQuotaRuleToJSON)),
        'sendingWindows': value['sendingWindows'] == null ? undefined : ((value['sendingWindows'] as Array<any>).map(MailSendingWindowToJSON)),
        'tenantQuotas': value['tenantQuotas'] == null ? undefined : ((value['tenantQuotas'] as Array<any>).map(MailQuotaRuleToJSON)),
        'timeZone': value['timeZone'],
    };
}

