/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostCrmClassifyReplyRequest
 */
export interface MailPostCrmClassifyReplyRequest {
    /**
     * 
     */
    contactId?: string;
    /**
     * 
     */
    subject?: string;
    /**
     * 
     */
    text: string;
}

/**
 * Check if a given object implements the MailPostCrmClassifyReplyRequest interface.
 */
export function instanceOfMailPostCrmClassifyReplyRequest(value: object): value is MailPostCrmClassifyReplyRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function MailPostCrmClassifyReplyRequestFromJSON(json: any): MailPostCrmClassifyReplyRequest {
    return MailPostCrmClassifyReplyRequestFromJSONTyped(json, false);
}

export function MailPostCrmClassifyReplyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCrmClassifyReplyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contactId': json['contactId'] == null ? undefined : json['contactId'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'text': json['text'],
    };
}

export function MailPostCrmClassifyReplyRequestToJSON(json: any): MailPostCrmClassifyReplyRequest {
    return MailPostCrmClassifyReplyRequestToJSONTyped(json, false);
}

export function MailPostCrmClassifyReplyRequestToJSONTyped(value?: MailPostCrmClassifyReplyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contactId': value['contactId'],
        'subject': value['subject'],
        'text': value['text'],
    };
}

