/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner } from './MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner.js';
import {
    MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInnerFromJSON,
    MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInnerFromJSONTyped,
    MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInnerToJSON,
    MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInnerToJSONTyped,
} from './MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner.js';

/**
 * Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
 * @export
 * @interface MailPostCadencesRequestNodesInnerAnyOf5Experiment
 */
export interface MailPostCadencesRequestNodesInnerAnyOf5Experiment {
    /**
     * 
     */
    assignmentUnit: MailPostCadencesRequestNodesInnerAnyOf5ExperimentAssignmentUnitEnum;
    /**
     * 
     */
    attributionWindowMs?: number;
    /**
     * 
     */
    guardrailMetrics?: Array<MailPostCadencesRequestNodesInnerAnyOf5ExperimentGuardrailMetricsEnum>;
    /**
     * 
     */
    hypothesis?: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    minimumRuntimeMs?: number;
    /**
     * 
     */
    minimumSampleSize?: number;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    primaryMetric?: MailPostCadencesRequestNodesInnerAnyOf5ExperimentPrimaryMetricEnum;
    /**
     * 
     */
    variants: Array<MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner>;
}


/**
 * @export
 */
export const MailPostCadencesRequestNodesInnerAnyOf5ExperimentAssignmentUnitEnum = {
    Contact: 'contact',
} as const;
export type MailPostCadencesRequestNodesInnerAnyOf5ExperimentAssignmentUnitEnum = typeof MailPostCadencesRequestNodesInnerAnyOf5ExperimentAssignmentUnitEnum[keyof typeof MailPostCadencesRequestNodesInnerAnyOf5ExperimentAssignmentUnitEnum];

/**
 * @export
 */
export const MailPostCadencesRequestNodesInnerAnyOf5ExperimentGuardrailMetricsEnum = {
    Bounce: 'bounce',
    Complaint: 'complaint',
    Unsubscribe: 'unsubscribe',
    PermanentFailure: 'permanent_failure',
} as const;
export type MailPostCadencesRequestNodesInnerAnyOf5ExperimentGuardrailMetricsEnum = typeof MailPostCadencesRequestNodesInnerAnyOf5ExperimentGuardrailMetricsEnum[keyof typeof MailPostCadencesRequestNodesInnerAnyOf5ExperimentGuardrailMetricsEnum];

/**
 * @export
 */
export const MailPostCadencesRequestNodesInnerAnyOf5ExperimentPrimaryMetricEnum = {
    PositiveReply: 'positive_reply',
    MeetingBooked: 'meeting_booked',
    HumanReply: 'human_reply',
    Click: 'click',
    Open: 'open',
    Custom: 'custom',
} as const;
export type MailPostCadencesRequestNodesInnerAnyOf5ExperimentPrimaryMetricEnum = typeof MailPostCadencesRequestNodesInnerAnyOf5ExperimentPrimaryMetricEnum[keyof typeof MailPostCadencesRequestNodesInnerAnyOf5ExperimentPrimaryMetricEnum];


/**
 * Check if a given object implements the MailPostCadencesRequestNodesInnerAnyOf5Experiment interface.
 */
export function instanceOfMailPostCadencesRequestNodesInnerAnyOf5Experiment(value: object): value is MailPostCadencesRequestNodesInnerAnyOf5Experiment {
    if (!('assignmentUnit' in value) || value['assignmentUnit'] === undefined) return false;
    if (value['assignmentUnit'] !== 'contact') return false;
    
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('variants' in value) || value['variants'] === undefined) return false;
    return true;
}

export function MailPostCadencesRequestNodesInnerAnyOf5ExperimentFromJSON(json: any): MailPostCadencesRequestNodesInnerAnyOf5Experiment {
    return MailPostCadencesRequestNodesInnerAnyOf5ExperimentFromJSONTyped(json, false);
}

export function MailPostCadencesRequestNodesInnerAnyOf5ExperimentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCadencesRequestNodesInnerAnyOf5Experiment {
    if (json == null) {
        return json;
    }
    return {
        
        'assignmentUnit': json['assignmentUnit'],
        'attributionWindowMs': json['attributionWindowMs'] == null ? undefined : json['attributionWindowMs'],
        'guardrailMetrics': json['guardrailMetrics'] == null ? undefined : json['guardrailMetrics'],
        'hypothesis': json['hypothesis'] == null ? undefined : json['hypothesis'],
        'id': json['id'],
        'minimumRuntimeMs': json['minimumRuntimeMs'] == null ? undefined : json['minimumRuntimeMs'],
        'minimumSampleSize': json['minimumSampleSize'] == null ? undefined : json['minimumSampleSize'],
        'name': json['name'],
        'primaryMetric': json['primaryMetric'] == null ? undefined : json['primaryMetric'],
        'variants': ((json['variants'] as Array<any>).map(MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInnerFromJSON)),
    };
}

export function MailPostCadencesRequestNodesInnerAnyOf5ExperimentToJSON(json: any): MailPostCadencesRequestNodesInnerAnyOf5Experiment {
    return MailPostCadencesRequestNodesInnerAnyOf5ExperimentToJSONTyped(json, false);
}

export function MailPostCadencesRequestNodesInnerAnyOf5ExperimentToJSONTyped(value?: MailPostCadencesRequestNodesInnerAnyOf5Experiment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignmentUnit': value['assignmentUnit'],
        'attributionWindowMs': value['attributionWindowMs'],
        'guardrailMetrics': value['guardrailMetrics'],
        'hypothesis': value['hypothesis'],
        'id': value['id'],
        'minimumRuntimeMs': value['minimumRuntimeMs'],
        'minimumSampleSize': value['minimumSampleSize'],
        'name': value['name'],
        'primaryMetric': value['primaryMetric'],
        'variants': ((value['variants'] as Array<any>).map(MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInnerToJSON)),
    };
}

