/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailSuppressionRecord
 */
export interface MailSuppressionRecord {
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    mailboxId?: string;
    /**
     * 
     */
    reason: string;
    /**
     * 
     */
    scope: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    value: string;
}

/**
 * Check if a given object implements the MailSuppressionRecord interface.
 */
export function instanceOfMailSuppressionRecord(value: object): value is MailSuppressionRecord {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function MailSuppressionRecordFromJSON(json: any): MailSuppressionRecord {
    return MailSuppressionRecordFromJSONTyped(json, false);
}

export function MailSuppressionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailSuppressionRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'mailboxId': json['mailboxId'] == null ? undefined : json['mailboxId'],
        'reason': json['reason'],
        'scope': json['scope'],
        'tenantId': json['tenantId'],
        'value': json['value'],
    };
}

export function MailSuppressionRecordToJSON(json: any): MailSuppressionRecord {
    return MailSuppressionRecordToJSONTyped(json, false);
}

export function MailSuppressionRecordToJSONTyped(value?: MailSuppressionRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'mailboxId': value['mailboxId'],
        'reason': value['reason'],
        'scope': value['scope'],
        'tenantId': value['tenantId'],
        'value': value['value'],
    };
}

