/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailMailboxHealthRecord } from './MailMailboxHealthRecord.js';
import {
    MailMailboxHealthRecordFromJSON,
    MailMailboxHealthRecordFromJSONTyped,
    MailMailboxHealthRecordToJSON,
    MailMailboxHealthRecordToJSONTyped,
} from './MailMailboxHealthRecord.js';

/**
 * 
 * @export
 * @interface MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200
 */
export interface MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 {
    /**
     * 
     */
    health: MailMailboxHealthRecord;
}

/**
 * Check if a given object implements the MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 interface.
 */
export function instanceOfMailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200(value: object): value is MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 {
    if (!('health' in value) || value['health'] === undefined) return false;
    return true;
}

export function MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200FromJSON(json: any): MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 {
    return MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200FromJSONTyped(json, false);
}

export function MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'health': MailMailboxHealthRecordFromJSON(json['health']),
    };
}

export function MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200ToJSON(json: any): MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 {
    return MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200ToJSONTyped(json, false);
}

export function MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200ToJSONTyped(value?: MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'health': MailMailboxHealthRecordToJSON(value['health']),
    };
}

