/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostCrmContactsBatchRequest
 */
export interface MailPostCrmContactsBatchRequest {
    /**
     * 
     */
    contactIds: Array<string>;
}

/**
 * Check if a given object implements the MailPostCrmContactsBatchRequest interface.
 */
export function instanceOfMailPostCrmContactsBatchRequest(value: object): value is MailPostCrmContactsBatchRequest {
    if (!('contactIds' in value) || value['contactIds'] === undefined) return false;
    return true;
}

export function MailPostCrmContactsBatchRequestFromJSON(json: any): MailPostCrmContactsBatchRequest {
    return MailPostCrmContactsBatchRequestFromJSONTyped(json, false);
}

export function MailPostCrmContactsBatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCrmContactsBatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contactIds': json['contactIds'],
    };
}

export function MailPostCrmContactsBatchRequestToJSON(json: any): MailPostCrmContactsBatchRequest {
    return MailPostCrmContactsBatchRequestToJSONTyped(json, false);
}

export function MailPostCrmContactsBatchRequestToJSONTyped(value?: MailPostCrmContactsBatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contactIds': value['contactIds'],
    };
}

