/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostCampaignsByCampaignIdLaunchRequest
 */
export interface MailPostCampaignsByCampaignIdLaunchRequest {
    /**
     * 
     */
    expectedVersion: number;
}

/**
 * Check if a given object implements the MailPostCampaignsByCampaignIdLaunchRequest interface.
 */
export function instanceOfMailPostCampaignsByCampaignIdLaunchRequest(value: object): value is MailPostCampaignsByCampaignIdLaunchRequest {
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    return true;
}

export function MailPostCampaignsByCampaignIdLaunchRequestFromJSON(json: any): MailPostCampaignsByCampaignIdLaunchRequest {
    return MailPostCampaignsByCampaignIdLaunchRequestFromJSONTyped(json, false);
}

export function MailPostCampaignsByCampaignIdLaunchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCampaignsByCampaignIdLaunchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expectedVersion': json['expectedVersion'],
    };
}

export function MailPostCampaignsByCampaignIdLaunchRequestToJSON(json: any): MailPostCampaignsByCampaignIdLaunchRequest {
    return MailPostCampaignsByCampaignIdLaunchRequestToJSONTyped(json, false);
}

export function MailPostCampaignsByCampaignIdLaunchRequestToJSONTyped(value?: MailPostCampaignsByCampaignIdLaunchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expectedVersion': value['expectedVersion'],
    };
}

