/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailCadenceNodeAnyOf4AllOfCondition } from './MailCadenceNodeAnyOf4AllOfCondition.js';
import {
    MailCadenceNodeAnyOf4AllOfConditionFromJSON,
    MailCadenceNodeAnyOf4AllOfConditionFromJSONTyped,
    MailCadenceNodeAnyOf4AllOfConditionToJSON,
    MailCadenceNodeAnyOf4AllOfConditionToJSONTyped,
} from './MailCadenceNodeAnyOf4AllOfCondition.js';

/**
 * 
 * @export
 * @interface MailCadenceNodeAnyOf4
 */
export interface MailCadenceNodeAnyOf4 {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    condition: MailCadenceNodeAnyOf4AllOfCondition;
    /**
     * 
     */
    falseNodeId: string;
    /**
     * 
     */
    kind: MailCadenceNodeAnyOf4KindEnum;
    /**
     * 
     */
    trueNodeId: string;
}


/**
 * @export
 */
export const MailCadenceNodeAnyOf4KindEnum = {
    Branch: 'branch',
} as const;
export type MailCadenceNodeAnyOf4KindEnum = typeof MailCadenceNodeAnyOf4KindEnum[keyof typeof MailCadenceNodeAnyOf4KindEnum];


/**
 * Check if a given object implements the MailCadenceNodeAnyOf4 interface.
 */
export function instanceOfMailCadenceNodeAnyOf4(value: object): value is MailCadenceNodeAnyOf4 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('condition' in value) || value['condition'] === undefined) return false;
    if (!('falseNodeId' in value) || value['falseNodeId'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (value['kind'] !== 'branch') return false;
    
    if (!('trueNodeId' in value) || value['trueNodeId'] === undefined) return false;
    return true;
}

export function MailCadenceNodeAnyOf4FromJSON(json: any): MailCadenceNodeAnyOf4 {
    return MailCadenceNodeAnyOf4FromJSONTyped(json, false);
}

export function MailCadenceNodeAnyOf4FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailCadenceNodeAnyOf4 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'condition': MailCadenceNodeAnyOf4AllOfConditionFromJSON(json['condition']),
        'falseNodeId': json['falseNodeId'],
        'kind': json['kind'],
        'trueNodeId': json['trueNodeId'],
    };
}

export function MailCadenceNodeAnyOf4ToJSON(json: any): MailCadenceNodeAnyOf4 {
    return MailCadenceNodeAnyOf4ToJSONTyped(json, false);
}

export function MailCadenceNodeAnyOf4ToJSONTyped(value?: MailCadenceNodeAnyOf4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'condition': MailCadenceNodeAnyOf4AllOfConditionToJSON(value['condition']),
        'falseNodeId': value['falseNodeId'],
        'kind': value['kind'],
        'trueNodeId': value['trueNodeId'],
    };
}

