/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner
 */
export interface MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    templateId: string;
    /**
     * 
     */
    templateVersion: number;
    /**
     * 
     */
    weight: number;
}

/**
 * Check if a given object implements the MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner interface.
 */
export function instanceOfMailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner(value: object): value is MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('templateVersion' in value) || value['templateVersion'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    return true;
}

export function MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInnerFromJSON(json: any): MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner {
    return MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInnerFromJSONTyped(json, false);
}

export function MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'templateId': json['templateId'],
        'templateVersion': json['templateVersion'],
        'weight': json['weight'],
    };
}

export function MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInnerToJSON(json: any): MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner {
    return MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInnerToJSONTyped(json, false);
}

export function MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInnerToJSONTyped(value?: MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'templateId': value['templateId'],
        'templateVersion': value['templateVersion'],
        'weight': value['weight'],
    };
}

