/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Identifies the host-owned delivery adapter used by a mailbox.
 * 
 * The built-in values retain editor completion, while the string intersection
 * allows applications to register adapters for an existing transactional email
 * service without changing Reacon Mail.
 * @export
 * @interface MailMailboxProviderKind
 */
export interface MailMailboxProviderKind {
}

/**
 * Check if a given object implements the MailMailboxProviderKind interface.
 */
export function instanceOfMailMailboxProviderKind(value: object): value is MailMailboxProviderKind {
    return true;
}

export function MailMailboxProviderKindFromJSON(json: any): MailMailboxProviderKind {
    return MailMailboxProviderKindFromJSONTyped(json, false);
}

export function MailMailboxProviderKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMailboxProviderKind {
    return json;
}

export function MailMailboxProviderKindToJSON(json: any): MailMailboxProviderKind {
    return MailMailboxProviderKindToJSONTyped(json, false);
}

export function MailMailboxProviderKindToJSONTyped(value?: MailMailboxProviderKind | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

