/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailMessageTemplateVersionWhatsappApproval
 */
export interface MailMessageTemplateVersionWhatsappApproval {
    /**
     * 
     */
    approvedAt: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    language: string;
    /**
     * 
     */
    templateName: string;
}

/**
 * Check if a given object implements the MailMessageTemplateVersionWhatsappApproval interface.
 */
export function instanceOfMailMessageTemplateVersionWhatsappApproval(value: object): value is MailMessageTemplateVersionWhatsappApproval {
    if (!('approvedAt' in value) || value['approvedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('templateName' in value) || value['templateName'] === undefined) return false;
    return true;
}

export function MailMessageTemplateVersionWhatsappApprovalFromJSON(json: any): MailMessageTemplateVersionWhatsappApproval {
    return MailMessageTemplateVersionWhatsappApprovalFromJSONTyped(json, false);
}

export function MailMessageTemplateVersionWhatsappApprovalFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMessageTemplateVersionWhatsappApproval {
    if (json == null) {
        return json;
    }
    return {
        
        'approvedAt': json['approvedAt'],
        'id': json['id'],
        'language': json['language'],
        'templateName': json['templateName'],
    };
}

export function MailMessageTemplateVersionWhatsappApprovalToJSON(json: any): MailMessageTemplateVersionWhatsappApproval {
    return MailMessageTemplateVersionWhatsappApprovalToJSONTyped(json, false);
}

export function MailMessageTemplateVersionWhatsappApprovalToJSONTyped(value?: MailMessageTemplateVersionWhatsappApproval | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'approvedAt': value['approvedAt'],
        'id': value['id'],
        'language': value['language'],
        'templateName': value['templateName'],
    };
}

