/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailCadenceStopConditions } from './MailCadenceStopConditions.js';
import {
    MailCadenceStopConditionsFromJSON,
    MailCadenceStopConditionsFromJSONTyped,
    MailCadenceStopConditionsToJSON,
    MailCadenceStopConditionsToJSONTyped,
} from './MailCadenceStopConditions.js';
import type { MailCadenceNode } from './MailCadenceNode.js';
import {
    MailCadenceNodeFromJSON,
    MailCadenceNodeFromJSONTyped,
    MailCadenceNodeToJSON,
    MailCadenceNodeToJSONTyped,
} from './MailCadenceNode.js';

/**
 * 
 * @export
 * @interface MailCadenceDefinition
 */
export interface MailCadenceDefinition {
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    createdByActorId: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    nodes: Array<MailCadenceNode>;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    stopConditions?: MailCadenceStopConditions;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    version: number;
}

/**
 * Check if a given object implements the MailCadenceDefinition interface.
 */
export function instanceOfMailCadenceDefinition(value: object): value is MailCadenceDefinition {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdByActorId' in value) || value['createdByActorId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function MailCadenceDefinitionFromJSON(json: any): MailCadenceDefinition {
    return MailCadenceDefinitionFromJSONTyped(json, false);
}

export function MailCadenceDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailCadenceDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'createdByActorId': json['createdByActorId'],
        'id': json['id'],
        'name': json['name'],
        'nodes': ((json['nodes'] as Array<any>).map(MailCadenceNodeFromJSON)),
        'status': json['status'],
        'stopConditions': json['stopConditions'] == null ? undefined : MailCadenceStopConditionsFromJSON(json['stopConditions']),
        'tenantId': json['tenantId'],
        'version': json['version'],
    };
}

export function MailCadenceDefinitionToJSON(json: any): MailCadenceDefinition {
    return MailCadenceDefinitionToJSONTyped(json, false);
}

export function MailCadenceDefinitionToJSONTyped(value?: MailCadenceDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'createdByActorId': value['createdByActorId'],
        'id': value['id'],
        'name': value['name'],
        'nodes': ((value['nodes'] as Array<any>).map(MailCadenceNodeToJSON)),
        'status': value['status'],
        'stopConditions': MailCadenceStopConditionsToJSON(value['stopConditions']),
        'tenantId': value['tenantId'],
        'version': value['version'],
    };
}

