/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailGetExperimentsResponse200ResultsInner } from './MailGetExperimentsResponse200ResultsInner.js';
import {
    MailGetExperimentsResponse200ResultsInnerFromJSON,
    MailGetExperimentsResponse200ResultsInnerFromJSONTyped,
    MailGetExperimentsResponse200ResultsInnerToJSON,
    MailGetExperimentsResponse200ResultsInnerToJSONTyped,
} from './MailGetExperimentsResponse200ResultsInner.js';

/**
 * 
 * @export
 * @interface MailGetExperimentsResponse200
 */
export interface MailGetExperimentsResponse200 {
    /**
     * 
     */
    results: Array<MailGetExperimentsResponse200ResultsInner>;
}

/**
 * Check if a given object implements the MailGetExperimentsResponse200 interface.
 */
export function instanceOfMailGetExperimentsResponse200(value: object): value is MailGetExperimentsResponse200 {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function MailGetExperimentsResponse200FromJSON(json: any): MailGetExperimentsResponse200 {
    return MailGetExperimentsResponse200FromJSONTyped(json, false);
}

export function MailGetExperimentsResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailGetExperimentsResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(MailGetExperimentsResponse200ResultsInnerFromJSON)),
    };
}

export function MailGetExperimentsResponse200ToJSON(json: any): MailGetExperimentsResponse200 {
    return MailGetExperimentsResponse200ToJSONTyped(json, false);
}

export function MailGetExperimentsResponse200ToJSONTyped(value?: MailGetExperimentsResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(MailGetExperimentsResponse200ResultsInnerToJSON)),
    };
}

