/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostDeliverabilityDomainHealthRequest
 */
export interface MailPostDeliverabilityDomainHealthRequest {
    /**
     * 
     */
    dkimSelectors?: Array<string>;
    /**
     * 
     */
    domain: string;
}

/**
 * Check if a given object implements the MailPostDeliverabilityDomainHealthRequest interface.
 */
export function instanceOfMailPostDeliverabilityDomainHealthRequest(value: object): value is MailPostDeliverabilityDomainHealthRequest {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function MailPostDeliverabilityDomainHealthRequestFromJSON(json: any): MailPostDeliverabilityDomainHealthRequest {
    return MailPostDeliverabilityDomainHealthRequestFromJSONTyped(json, false);
}

export function MailPostDeliverabilityDomainHealthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostDeliverabilityDomainHealthRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'dkimSelectors': json['dkimSelectors'] == null ? undefined : json['dkimSelectors'],
        'domain': json['domain'],
    };
}

export function MailPostDeliverabilityDomainHealthRequestToJSON(json: any): MailPostDeliverabilityDomainHealthRequest {
    return MailPostDeliverabilityDomainHealthRequestToJSONTyped(json, false);
}

export function MailPostDeliverabilityDomainHealthRequestToJSONTyped(value?: MailPostDeliverabilityDomainHealthRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dkimSelectors': value['dkimSelectors'],
        'domain': value['domain'],
    };
}

