/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostCrmNotesRequest
 */
export interface MailPostCrmNotesRequest {
    /**
     * 
     */
    contactId: string;
    /**
     * 
     */
    text: string;
}

/**
 * Check if a given object implements the MailPostCrmNotesRequest interface.
 */
export function instanceOfMailPostCrmNotesRequest(value: object): value is MailPostCrmNotesRequest {
    if (!('contactId' in value) || value['contactId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function MailPostCrmNotesRequestFromJSON(json: any): MailPostCrmNotesRequest {
    return MailPostCrmNotesRequestFromJSONTyped(json, false);
}

export function MailPostCrmNotesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCrmNotesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contactId': json['contactId'],
        'text': json['text'],
    };
}

export function MailPostCrmNotesRequestToJSON(json: any): MailPostCrmNotesRequest {
    return MailPostCrmNotesRequestToJSONTyped(json, false);
}

export function MailPostCrmNotesRequestToJSONTyped(value?: MailPostCrmNotesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contactId': value['contactId'],
        'text': value['text'],
    };
}

