/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner
 */
export interface MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner {
    /**
     * 
     */
    html?: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    subject: string;
    /**
     * 
     */
    text: string;
    /**
     * 
     */
    weight: number;
}

/**
 * Check if a given object implements the MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner interface.
 */
export function instanceOfMailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner(value: object): value is MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    return true;
}

export function MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInnerFromJSON(json: any): MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner {
    return MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInnerFromJSONTyped(json, false);
}

export function MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'html': json['html'] == null ? undefined : json['html'],
        'id': json['id'],
        'subject': json['subject'],
        'text': json['text'],
        'weight': json['weight'],
    };
}

export function MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInnerToJSON(json: any): MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner {
    return MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInnerToJSONTyped(json, false);
}

export function MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInnerToJSONTyped(value?: MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'html': value['html'],
        'id': value['id'],
        'subject': value['subject'],
        'text': value['text'],
        'weight': value['weight'],
    };
}

