/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailInboxMessageRecord } from './MailInboxMessageRecord.js';
import {
    MailInboxMessageRecordFromJSON,
    MailInboxMessageRecordFromJSONTyped,
    MailInboxMessageRecordToJSON,
    MailInboxMessageRecordToJSONTyped,
} from './MailInboxMessageRecord.js';
import type { MailReplyClassificationResult } from './MailReplyClassificationResult.js';
import {
    MailReplyClassificationResultFromJSON,
    MailReplyClassificationResultFromJSONTyped,
    MailReplyClassificationResultToJSON,
    MailReplyClassificationResultToJSONTyped,
} from './MailReplyClassificationResult.js';
import type { MailConversationEntryFrom } from './MailConversationEntryFrom.js';
import {
    MailConversationEntryFromFromJSON,
    MailConversationEntryFromFromJSONTyped,
    MailConversationEntryFromToJSON,
    MailConversationEntryFromToJSONTyped,
} from './MailConversationEntryFrom.js';

/**
 * 
 * @export
 * @interface MailPostInboxByMessageIdResponse200Message
 */
export interface MailPostInboxByMessageIdResponse200Message {
    /**
     * 
     */
    assignedToActorId?: string;
    /**
     * 
     */
    contactId?: string;
    /**
     * 
     */
    from: MailConversationEntryFrom;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    inboundClassification: string;
    /**
     * 
     */
    mailboxId: string;
    /**
     * 
     */
    outboundMessageId: string;
    /**
     * 
     */
    providerEventId: string;
    /**
     * 
     */
    receivedAt: string;
    /**
     * 
     */
    replyClassification: MailReplyClassificationResult;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    subject: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    text: string;
    /**
     * 
     */
    threadKey: string;
    /**
     * 
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the MailPostInboxByMessageIdResponse200Message interface.
 */
export function instanceOfMailPostInboxByMessageIdResponse200Message(value: object): value is MailPostInboxByMessageIdResponse200Message {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('inboundClassification' in value) || value['inboundClassification'] === undefined) return false;
    if (!('mailboxId' in value) || value['mailboxId'] === undefined) return false;
    if (!('outboundMessageId' in value) || value['outboundMessageId'] === undefined) return false;
    if (!('providerEventId' in value) || value['providerEventId'] === undefined) return false;
    if (!('receivedAt' in value) || value['receivedAt'] === undefined) return false;
    if (!('replyClassification' in value) || value['replyClassification'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('threadKey' in value) || value['threadKey'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MailPostInboxByMessageIdResponse200MessageFromJSON(json: any): MailPostInboxByMessageIdResponse200Message {
    return MailPostInboxByMessageIdResponse200MessageFromJSONTyped(json, false);
}

export function MailPostInboxByMessageIdResponse200MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostInboxByMessageIdResponse200Message {
    if (json == null) {
        return json;
    }
    return {
        
        'assignedToActorId': json['assignedToActorId'] == null ? undefined : json['assignedToActorId'],
        'contactId': json['contactId'] == null ? undefined : json['contactId'],
        'from': MailConversationEntryFromFromJSON(json['from']),
        'id': json['id'],
        'inboundClassification': json['inboundClassification'],
        'mailboxId': json['mailboxId'],
        'outboundMessageId': json['outboundMessageId'],
        'providerEventId': json['providerEventId'],
        'receivedAt': json['receivedAt'],
        'replyClassification': MailReplyClassificationResultFromJSON(json['replyClassification']),
        'status': json['status'],
        'subject': json['subject'],
        'tenantId': json['tenantId'],
        'text': json['text'],
        'threadKey': json['threadKey'],
        'updatedAt': json['updatedAt'],
    };
}

export function MailPostInboxByMessageIdResponse200MessageToJSON(json: any): MailPostInboxByMessageIdResponse200Message {
    return MailPostInboxByMessageIdResponse200MessageToJSONTyped(json, false);
}

export function MailPostInboxByMessageIdResponse200MessageToJSONTyped(value?: MailPostInboxByMessageIdResponse200Message | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignedToActorId': value['assignedToActorId'],
        'contactId': value['contactId'],
        'from': MailConversationEntryFromToJSON(value['from']),
        'id': value['id'],
        'inboundClassification': value['inboundClassification'],
        'mailboxId': value['mailboxId'],
        'outboundMessageId': value['outboundMessageId'],
        'providerEventId': value['providerEventId'],
        'receivedAt': value['receivedAt'],
        'replyClassification': MailReplyClassificationResultToJSON(value['replyClassification']),
        'status': value['status'],
        'subject': value['subject'],
        'tenantId': value['tenantId'],
        'text': value['text'],
        'threadKey': value['threadKey'],
        'updatedAt': value['updatedAt'],
    };
}

