/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailMessageAnalyticsOverviewMailboxesInner
 */
export interface MailMessageAnalyticsOverviewMailboxesInner {
    /**
     * 
     */
    accepted: number;
    /**
     * 
     */
    bounced: number;
    /**
     * 
     */
    complained: number;
    /**
     * 
     */
    mailboxId: string;
    /**
     * 
     */
    replied: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the MailMessageAnalyticsOverviewMailboxesInner interface.
 */
export function instanceOfMailMessageAnalyticsOverviewMailboxesInner(value: object): value is MailMessageAnalyticsOverviewMailboxesInner {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    if (!('bounced' in value) || value['bounced'] === undefined) return false;
    if (!('complained' in value) || value['complained'] === undefined) return false;
    if (!('mailboxId' in value) || value['mailboxId'] === undefined) return false;
    if (!('replied' in value) || value['replied'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function MailMessageAnalyticsOverviewMailboxesInnerFromJSON(json: any): MailMessageAnalyticsOverviewMailboxesInner {
    return MailMessageAnalyticsOverviewMailboxesInnerFromJSONTyped(json, false);
}

export function MailMessageAnalyticsOverviewMailboxesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMessageAnalyticsOverviewMailboxesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
        'bounced': json['bounced'],
        'complained': json['complained'],
        'mailboxId': json['mailboxId'],
        'replied': json['replied'],
        'total': json['total'],
    };
}

export function MailMessageAnalyticsOverviewMailboxesInnerToJSON(json: any): MailMessageAnalyticsOverviewMailboxesInner {
    return MailMessageAnalyticsOverviewMailboxesInnerToJSONTyped(json, false);
}

export function MailMessageAnalyticsOverviewMailboxesInnerToJSONTyped(value?: MailMessageAnalyticsOverviewMailboxesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
        'bounced': value['bounced'],
        'complained': value['complained'],
        'mailboxId': value['mailboxId'],
        'replied': value['replied'],
        'total': value['total'],
    };
}

