/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailMailboxHealthRecord } from './MailMailboxHealthRecord.js';
import {
    MailMailboxHealthRecordFromJSON,
    MailMailboxHealthRecordFromJSONTyped,
    MailMailboxHealthRecordToJSON,
    MailMailboxHealthRecordToJSONTyped,
} from './MailMailboxHealthRecord.js';

/**
 * 
 * @export
 * @interface MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200
 */
export interface MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 {
    /**
     * 
     */
    health: MailMailboxHealthRecord;
}

/**
 * Check if a given object implements the MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 interface.
 */
export function instanceOfMailPostDeliverabilityMailboxesByMailboxIdResumeResponse200(value: object): value is MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 {
    if (!('health' in value) || value['health'] === undefined) return false;
    return true;
}

export function MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200FromJSON(json: any): MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 {
    return MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200FromJSONTyped(json, false);
}

export function MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'health': MailMailboxHealthRecordFromJSON(json['health']),
    };
}

export function MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200ToJSON(json: any): MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 {
    return MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200ToJSONTyped(json, false);
}

export function MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200ToJSONTyped(value?: MailPostDeliverabilityMailboxesByMailboxIdResumeResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'health': MailMailboxHealthRecordToJSON(value['health']),
    };
}

