/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailMailPortfolio } from './MailMailPortfolio.js';
import {
    MailMailPortfolioFromJSON,
    MailMailPortfolioFromJSONTyped,
    MailMailPortfolioToJSON,
    MailMailPortfolioToJSONTyped,
} from './MailMailPortfolio.js';
import type { MailMailPortfolioOverviewRow } from './MailMailPortfolioOverviewRow.js';
import {
    MailMailPortfolioOverviewRowFromJSON,
    MailMailPortfolioOverviewRowFromJSONTyped,
    MailMailPortfolioOverviewRowToJSON,
    MailMailPortfolioOverviewRowToJSONTyped,
} from './MailMailPortfolioOverviewRow.js';

/**
 * 
 * @export
 * @interface MailGetPortfolioOverviewResponse200
 */
export interface MailGetPortfolioOverviewResponse200 {
    /**
     * 
     */
    generatedAt: string;
    /**
     * 
     */
    portfolio: MailMailPortfolio;
    /**
     * 
     */
    rows: Array<MailMailPortfolioOverviewRow>;
}

/**
 * Check if a given object implements the MailGetPortfolioOverviewResponse200 interface.
 */
export function instanceOfMailGetPortfolioOverviewResponse200(value: object): value is MailGetPortfolioOverviewResponse200 {
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('portfolio' in value) || value['portfolio'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    return true;
}

export function MailGetPortfolioOverviewResponse200FromJSON(json: any): MailGetPortfolioOverviewResponse200 {
    return MailGetPortfolioOverviewResponse200FromJSONTyped(json, false);
}

export function MailGetPortfolioOverviewResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailGetPortfolioOverviewResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': json['generatedAt'],
        'portfolio': MailMailPortfolioFromJSON(json['portfolio']),
        'rows': ((json['rows'] as Array<any>).map(MailMailPortfolioOverviewRowFromJSON)),
    };
}

export function MailGetPortfolioOverviewResponse200ToJSON(json: any): MailGetPortfolioOverviewResponse200 {
    return MailGetPortfolioOverviewResponse200ToJSONTyped(json, false);
}

export function MailGetPortfolioOverviewResponse200ToJSONTyped(value?: MailGetPortfolioOverviewResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generatedAt': value['generatedAt'],
        'portfolio': MailMailPortfolioToJSON(value['portfolio']),
        'rows': ((value['rows'] as Array<any>).map(MailMailPortfolioOverviewRowToJSON)),
    };
}

