/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailMessageVariantInput
 */
export interface MailMessageVariantInput {
    /**
     * 
     */
    html?: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    subject: string;
    /**
     * 
     */
    text: string;
    /**
     * 
     */
    variables?: { [key: string]: any; };
    /**
     * 
     */
    weight: number;
}

/**
 * Check if a given object implements the MailMessageVariantInput interface.
 */
export function instanceOfMailMessageVariantInput(value: object): value is MailMessageVariantInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    return true;
}

export function MailMessageVariantInputFromJSON(json: any): MailMessageVariantInput {
    return MailMessageVariantInputFromJSONTyped(json, false);
}

export function MailMessageVariantInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMessageVariantInput {
    if (json == null) {
        return json;
    }
    return {
        
        'html': json['html'] == null ? undefined : json['html'],
        'id': json['id'],
        'subject': json['subject'],
        'text': json['text'],
        'variables': json['variables'] == null ? undefined : json['variables'],
        'weight': json['weight'],
    };
}

export function MailMessageVariantInputToJSON(json: any): MailMessageVariantInput {
    return MailMessageVariantInputToJSONTyped(json, false);
}

export function MailMessageVariantInputToJSONTyped(value?: MailMessageVariantInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'html': value['html'],
        'id': value['id'],
        'subject': value['subject'],
        'text': value['text'],
        'variables': value['variables'],
        'weight': value['weight'],
    };
}

