/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailPostInboxByMessageIdResponse200Message } from './MailPostInboxByMessageIdResponse200Message.js';
import {
    MailPostInboxByMessageIdResponse200MessageFromJSON,
    MailPostInboxByMessageIdResponse200MessageFromJSONTyped,
    MailPostInboxByMessageIdResponse200MessageToJSON,
    MailPostInboxByMessageIdResponse200MessageToJSONTyped,
} from './MailPostInboxByMessageIdResponse200Message.js';

/**
 * 
 * @export
 * @interface MailPostInboxByMessageIdResponse200
 */
export interface MailPostInboxByMessageIdResponse200 {
    /**
     * 
     */
    message: MailPostInboxByMessageIdResponse200Message;
}

/**
 * Check if a given object implements the MailPostInboxByMessageIdResponse200 interface.
 */
export function instanceOfMailPostInboxByMessageIdResponse200(value: object): value is MailPostInboxByMessageIdResponse200 {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function MailPostInboxByMessageIdResponse200FromJSON(json: any): MailPostInboxByMessageIdResponse200 {
    return MailPostInboxByMessageIdResponse200FromJSONTyped(json, false);
}

export function MailPostInboxByMessageIdResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostInboxByMessageIdResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'message': MailPostInboxByMessageIdResponse200MessageFromJSON(json['message']),
    };
}

export function MailPostInboxByMessageIdResponse200ToJSON(json: any): MailPostInboxByMessageIdResponse200 {
    return MailPostInboxByMessageIdResponse200ToJSONTyped(json, false);
}

export function MailPostInboxByMessageIdResponse200ToJSONTyped(value?: MailPostInboxByMessageIdResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': MailPostInboxByMessageIdResponse200MessageToJSON(value['message']),
    };
}

