/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailPatchCampaignsByCampaignIdRequestStepsInner } from './MailPatchCampaignsByCampaignIdRequestStepsInner.js';
import {
    MailPatchCampaignsByCampaignIdRequestStepsInnerFromJSON,
    MailPatchCampaignsByCampaignIdRequestStepsInnerFromJSONTyped,
    MailPatchCampaignsByCampaignIdRequestStepsInnerToJSON,
    MailPatchCampaignsByCampaignIdRequestStepsInnerToJSONTyped,
} from './MailPatchCampaignsByCampaignIdRequestStepsInner.js';
import type { MailPatchCampaignsByCampaignIdRequestPolicy } from './MailPatchCampaignsByCampaignIdRequestPolicy.js';
import {
    MailPatchCampaignsByCampaignIdRequestPolicyFromJSON,
    MailPatchCampaignsByCampaignIdRequestPolicyFromJSONTyped,
    MailPatchCampaignsByCampaignIdRequestPolicyToJSON,
    MailPatchCampaignsByCampaignIdRequestPolicyToJSONTyped,
} from './MailPatchCampaignsByCampaignIdRequestPolicy.js';

/**
 * 
 * @export
 * @interface MailPostCampaignsRequest
 */
export interface MailPostCampaignsRequest {
    /**
     * 
     */
    audienceListIds?: Array<string>;
    /**
     * 
     */
    mailboxIds?: Array<string>;
    /**
     * 
     */
    mailboxPoolId?: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    policy?: MailPatchCampaignsByCampaignIdRequestPolicy;
    /**
     * 
     */
    scheduledAt?: string;
    /**
     * 
     */
    steps?: Array<MailPatchCampaignsByCampaignIdRequestStepsInner>;
}

/**
 * Check if a given object implements the MailPostCampaignsRequest interface.
 */
export function instanceOfMailPostCampaignsRequest(value: object): value is MailPostCampaignsRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MailPostCampaignsRequestFromJSON(json: any): MailPostCampaignsRequest {
    return MailPostCampaignsRequestFromJSONTyped(json, false);
}

export function MailPostCampaignsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCampaignsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'audienceListIds': json['audienceListIds'] == null ? undefined : json['audienceListIds'],
        'mailboxIds': json['mailboxIds'] == null ? undefined : json['mailboxIds'],
        'mailboxPoolId': json['mailboxPoolId'] == null ? undefined : json['mailboxPoolId'],
        'name': json['name'],
        'policy': json['policy'] == null ? undefined : MailPatchCampaignsByCampaignIdRequestPolicyFromJSON(json['policy']),
        'scheduledAt': json['scheduledAt'] == null ? undefined : json['scheduledAt'],
        'steps': json['steps'] == null ? undefined : ((json['steps'] as Array<any>).map(MailPatchCampaignsByCampaignIdRequestStepsInnerFromJSON)),
    };
}

export function MailPostCampaignsRequestToJSON(json: any): MailPostCampaignsRequest {
    return MailPostCampaignsRequestToJSONTyped(json, false);
}

export function MailPostCampaignsRequestToJSONTyped(value?: MailPostCampaignsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audienceListIds': value['audienceListIds'],
        'mailboxIds': value['mailboxIds'],
        'mailboxPoolId': value['mailboxPoolId'],
        'name': value['name'],
        'policy': MailPatchCampaignsByCampaignIdRequestPolicyToJSON(value['policy']),
        'scheduledAt': value['scheduledAt'],
        'steps': value['steps'] == null ? undefined : ((value['steps'] as Array<any>).map(MailPatchCampaignsByCampaignIdRequestStepsInnerToJSON)),
    };
}

