/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailConversationThread } from './MailConversationThread.js';
import {
    MailConversationThreadFromJSON,
    MailConversationThreadFromJSONTyped,
    MailConversationThreadToJSON,
    MailConversationThreadToJSONTyped,
} from './MailConversationThread.js';

/**
 * 
 * @export
 * @interface MailGetInboxThreadsResponse200
 */
export interface MailGetInboxThreadsResponse200 {
    /**
     * 
     */
    sampleLimited: boolean;
    /**
     * 
     */
    threads: Array<MailConversationThread>;
}

/**
 * Check if a given object implements the MailGetInboxThreadsResponse200 interface.
 */
export function instanceOfMailGetInboxThreadsResponse200(value: object): value is MailGetInboxThreadsResponse200 {
    if (!('sampleLimited' in value) || value['sampleLimited'] === undefined) return false;
    if (!('threads' in value) || value['threads'] === undefined) return false;
    return true;
}

export function MailGetInboxThreadsResponse200FromJSON(json: any): MailGetInboxThreadsResponse200 {
    return MailGetInboxThreadsResponse200FromJSONTyped(json, false);
}

export function MailGetInboxThreadsResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailGetInboxThreadsResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'sampleLimited': json['sampleLimited'],
        'threads': ((json['threads'] as Array<any>).map(MailConversationThreadFromJSON)),
    };
}

export function MailGetInboxThreadsResponse200ToJSON(json: any): MailGetInboxThreadsResponse200 {
    return MailGetInboxThreadsResponse200ToJSONTyped(json, false);
}

export function MailGetInboxThreadsResponse200ToJSONTyped(value?: MailGetInboxThreadsResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sampleLimited': value['sampleLimited'],
        'threads': ((value['threads'] as Array<any>).map(MailConversationThreadToJSON)),
    };
}

