/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailMailboxPoolMember } from './MailMailboxPoolMember.js';
import {
    MailMailboxPoolMemberFromJSON,
    MailMailboxPoolMemberFromJSONTyped,
    MailMailboxPoolMemberToJSON,
    MailMailboxPoolMemberToJSONTyped,
} from './MailMailboxPoolMember.js';

/**
 * 
 * @export
 * @interface MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200
 */
export interface MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {
    /**
     * 
     */
    member: MailMailboxPoolMember;
}

/**
 * Check if a given object implements the MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 interface.
 */
export function instanceOfMailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200(value: object): value is MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {
    if (!('member' in value) || value['member'] === undefined) return false;
    return true;
}

export function MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200FromJSON(json: any): MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {
    return MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200FromJSONTyped(json, false);
}

export function MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'member': MailMailboxPoolMemberFromJSON(json['member']),
    };
}

export function MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200ToJSON(json: any): MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {
    return MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200ToJSONTyped(json, false);
}

export function MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200ToJSONTyped(value?: MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member': MailMailboxPoolMemberToJSON(value['member']),
    };
}

