/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailDeleteWebhooksBySubscriptionIdResponse200
 */
export interface MailDeleteWebhooksBySubscriptionIdResponse200 {
    /**
     * 
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the MailDeleteWebhooksBySubscriptionIdResponse200 interface.
 */
export function instanceOfMailDeleteWebhooksBySubscriptionIdResponse200(value: object): value is MailDeleteWebhooksBySubscriptionIdResponse200 {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function MailDeleteWebhooksBySubscriptionIdResponse200FromJSON(json: any): MailDeleteWebhooksBySubscriptionIdResponse200 {
    return MailDeleteWebhooksBySubscriptionIdResponse200FromJSONTyped(json, false);
}

export function MailDeleteWebhooksBySubscriptionIdResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailDeleteWebhooksBySubscriptionIdResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
    };
}

export function MailDeleteWebhooksBySubscriptionIdResponse200ToJSON(json: any): MailDeleteWebhooksBySubscriptionIdResponse200 {
    return MailDeleteWebhooksBySubscriptionIdResponse200ToJSONTyped(json, false);
}

export function MailDeleteWebhooksBySubscriptionIdResponse200ToJSONTyped(value?: MailDeleteWebhooksBySubscriptionIdResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

