/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostCrmTasksByTaskIdCompleteRequest
 */
export interface MailPostCrmTasksByTaskIdCompleteRequest {
    /**
     * 
     */
    outcome?: string;
}

/**
 * Check if a given object implements the MailPostCrmTasksByTaskIdCompleteRequest interface.
 */
export function instanceOfMailPostCrmTasksByTaskIdCompleteRequest(value: object): value is MailPostCrmTasksByTaskIdCompleteRequest {
    return true;
}

export function MailPostCrmTasksByTaskIdCompleteRequestFromJSON(json: any): MailPostCrmTasksByTaskIdCompleteRequest {
    return MailPostCrmTasksByTaskIdCompleteRequestFromJSONTyped(json, false);
}

export function MailPostCrmTasksByTaskIdCompleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCrmTasksByTaskIdCompleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'outcome': json['outcome'] == null ? undefined : json['outcome'],
    };
}

export function MailPostCrmTasksByTaskIdCompleteRequestToJSON(json: any): MailPostCrmTasksByTaskIdCompleteRequest {
    return MailPostCrmTasksByTaskIdCompleteRequestToJSONTyped(json, false);
}

export function MailPostCrmTasksByTaskIdCompleteRequestToJSONTyped(value?: MailPostCrmTasksByTaskIdCompleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outcome': value['outcome'],
    };
}

