/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailPostCrmNotesResponse200Event } from './MailPostCrmNotesResponse200Event.js';
import {
    MailPostCrmNotesResponse200EventFromJSON,
    MailPostCrmNotesResponse200EventFromJSONTyped,
    MailPostCrmNotesResponse200EventToJSON,
    MailPostCrmNotesResponse200EventToJSONTyped,
} from './MailPostCrmNotesResponse200Event.js';

/**
 * 
 * @export
 * @interface MailPostCrmNotesResponse200
 */
export interface MailPostCrmNotesResponse200 {
    /**
     * 
     */
    event: MailPostCrmNotesResponse200Event;
}

/**
 * Check if a given object implements the MailPostCrmNotesResponse200 interface.
 */
export function instanceOfMailPostCrmNotesResponse200(value: object): value is MailPostCrmNotesResponse200 {
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function MailPostCrmNotesResponse200FromJSON(json: any): MailPostCrmNotesResponse200 {
    return MailPostCrmNotesResponse200FromJSONTyped(json, false);
}

export function MailPostCrmNotesResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCrmNotesResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'event': MailPostCrmNotesResponse200EventFromJSON(json['event']),
    };
}

export function MailPostCrmNotesResponse200ToJSON(json: any): MailPostCrmNotesResponse200 {
    return MailPostCrmNotesResponse200ToJSONTyped(json, false);
}

export function MailPostCrmNotesResponse200ToJSONTyped(value?: MailPostCrmNotesResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': MailPostCrmNotesResponse200EventToJSON(value['event']),
    };
}

