/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailGetChannelsResponse200Sms
 */
export interface MailGetChannelsResponse200Sms {
    /**
     * 
     */
    configured: boolean;
    /**
     * 
     */
    consentRequired: boolean;
    /**
     * 
     */
    costCeilingRequired: boolean;
    /**
     * 
     */
    executionEnabled: boolean;
    /**
     * 
     */
    sequenceSupported: boolean;
}

/**
 * Check if a given object implements the MailGetChannelsResponse200Sms interface.
 */
export function instanceOfMailGetChannelsResponse200Sms(value: object): value is MailGetChannelsResponse200Sms {
    if (!('configured' in value) || value['configured'] === undefined) return false;
    if (!('consentRequired' in value) || value['consentRequired'] === undefined) return false;
    if (!('costCeilingRequired' in value) || value['costCeilingRequired'] === undefined) return false;
    if (!('executionEnabled' in value) || value['executionEnabled'] === undefined) return false;
    if (!('sequenceSupported' in value) || value['sequenceSupported'] === undefined) return false;
    return true;
}

export function MailGetChannelsResponse200SmsFromJSON(json: any): MailGetChannelsResponse200Sms {
    return MailGetChannelsResponse200SmsFromJSONTyped(json, false);
}

export function MailGetChannelsResponse200SmsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailGetChannelsResponse200Sms {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'],
        'consentRequired': json['consentRequired'],
        'costCeilingRequired': json['costCeilingRequired'],
        'executionEnabled': json['executionEnabled'],
        'sequenceSupported': json['sequenceSupported'],
    };
}

export function MailGetChannelsResponse200SmsToJSON(json: any): MailGetChannelsResponse200Sms {
    return MailGetChannelsResponse200SmsToJSONTyped(json, false);
}

export function MailGetChannelsResponse200SmsToJSONTyped(value?: MailGetChannelsResponse200Sms | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'consentRequired': value['consentRequired'],
        'costCeilingRequired': value['costCeilingRequired'],
        'executionEnabled': value['executionEnabled'],
        'sequenceSupported': value['sequenceSupported'],
    };
}

