/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailDeleteMailboxesByMailboxIdResponse200
 */
export interface MailDeleteMailboxesByMailboxIdResponse200 {
    /**
     * 
     */
    disconnected: boolean;
}

/**
 * Check if a given object implements the MailDeleteMailboxesByMailboxIdResponse200 interface.
 */
export function instanceOfMailDeleteMailboxesByMailboxIdResponse200(value: object): value is MailDeleteMailboxesByMailboxIdResponse200 {
    if (!('disconnected' in value) || value['disconnected'] === undefined) return false;
    return true;
}

export function MailDeleteMailboxesByMailboxIdResponse200FromJSON(json: any): MailDeleteMailboxesByMailboxIdResponse200 {
    return MailDeleteMailboxesByMailboxIdResponse200FromJSONTyped(json, false);
}

export function MailDeleteMailboxesByMailboxIdResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailDeleteMailboxesByMailboxIdResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'disconnected': json['disconnected'],
    };
}

export function MailDeleteMailboxesByMailboxIdResponse200ToJSON(json: any): MailDeleteMailboxesByMailboxIdResponse200 {
    return MailDeleteMailboxesByMailboxIdResponse200ToJSONTyped(json, false);
}

export function MailDeleteMailboxesByMailboxIdResponse200ToJSONTyped(value?: MailDeleteMailboxesByMailboxIdResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disconnected': value['disconnected'],
    };
}

