/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailCadenceRunRecord } from './MailCadenceRunRecord.js';
import {
    MailCadenceRunRecordFromJSON,
    MailCadenceRunRecordFromJSONTyped,
    MailCadenceRunRecordToJSON,
    MailCadenceRunRecordToJSONTyped,
} from './MailCadenceRunRecord.js';

/**
 * 
 * @export
 * @interface MailPostCadenceRunsByRunIdStateResponse200
 */
export interface MailPostCadenceRunsByRunIdStateResponse200 {
    /**
     * 
     */
    run: MailCadenceRunRecord;
}

/**
 * Check if a given object implements the MailPostCadenceRunsByRunIdStateResponse200 interface.
 */
export function instanceOfMailPostCadenceRunsByRunIdStateResponse200(value: object): value is MailPostCadenceRunsByRunIdStateResponse200 {
    if (!('run' in value) || value['run'] === undefined) return false;
    return true;
}

export function MailPostCadenceRunsByRunIdStateResponse200FromJSON(json: any): MailPostCadenceRunsByRunIdStateResponse200 {
    return MailPostCadenceRunsByRunIdStateResponse200FromJSONTyped(json, false);
}

export function MailPostCadenceRunsByRunIdStateResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCadenceRunsByRunIdStateResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'run': MailCadenceRunRecordFromJSON(json['run']),
    };
}

export function MailPostCadenceRunsByRunIdStateResponse200ToJSON(json: any): MailPostCadenceRunsByRunIdStateResponse200 {
    return MailPostCadenceRunsByRunIdStateResponse200ToJSONTyped(json, false);
}

export function MailPostCadenceRunsByRunIdStateResponse200ToJSONTyped(value?: MailPostCadenceRunsByRunIdStateResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run': MailCadenceRunRecordToJSON(value['run']),
    };
}

