/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostCadenceRunsByRunIdStateRequest
 */
export interface MailPostCadenceRunsByRunIdStateRequest {
    /**
     * 
     */
    action: MailPostCadenceRunsByRunIdStateRequestActionEnum;
}


/**
 * @export
 */
export const MailPostCadenceRunsByRunIdStateRequestActionEnum = {
    Pause: 'pause',
    Resume: 'resume',
    Cancel: 'cancel',
} as const;
export type MailPostCadenceRunsByRunIdStateRequestActionEnum = typeof MailPostCadenceRunsByRunIdStateRequestActionEnum[keyof typeof MailPostCadenceRunsByRunIdStateRequestActionEnum];


/**
 * Check if a given object implements the MailPostCadenceRunsByRunIdStateRequest interface.
 */
export function instanceOfMailPostCadenceRunsByRunIdStateRequest(value: object): value is MailPostCadenceRunsByRunIdStateRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function MailPostCadenceRunsByRunIdStateRequestFromJSON(json: any): MailPostCadenceRunsByRunIdStateRequest {
    return MailPostCadenceRunsByRunIdStateRequestFromJSONTyped(json, false);
}

export function MailPostCadenceRunsByRunIdStateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCadenceRunsByRunIdStateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
    };
}

export function MailPostCadenceRunsByRunIdStateRequestToJSON(json: any): MailPostCadenceRunsByRunIdStateRequest {
    return MailPostCadenceRunsByRunIdStateRequestToJSONTyped(json, false);
}

export function MailPostCadenceRunsByRunIdStateRequestToJSONTyped(value?: MailPostCadenceRunsByRunIdStateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
    };
}

