/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailCampaignDraftRecord } from './MailCampaignDraftRecord.js';
import {
    MailCampaignDraftRecordFromJSON,
    MailCampaignDraftRecordFromJSONTyped,
    MailCampaignDraftRecordToJSON,
    MailCampaignDraftRecordToJSONTyped,
} from './MailCampaignDraftRecord.js';

/**
 * 
 * @export
 * @interface MailPatchCampaignsByCampaignIdResponse200
 */
export interface MailPatchCampaignsByCampaignIdResponse200 {
    /**
     * 
     */
    campaign: MailCampaignDraftRecord;
}

/**
 * Check if a given object implements the MailPatchCampaignsByCampaignIdResponse200 interface.
 */
export function instanceOfMailPatchCampaignsByCampaignIdResponse200(value: object): value is MailPatchCampaignsByCampaignIdResponse200 {
    if (!('campaign' in value) || value['campaign'] === undefined) return false;
    return true;
}

export function MailPatchCampaignsByCampaignIdResponse200FromJSON(json: any): MailPatchCampaignsByCampaignIdResponse200 {
    return MailPatchCampaignsByCampaignIdResponse200FromJSONTyped(json, false);
}

export function MailPatchCampaignsByCampaignIdResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPatchCampaignsByCampaignIdResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'campaign': MailCampaignDraftRecordFromJSON(json['campaign']),
    };
}

export function MailPatchCampaignsByCampaignIdResponse200ToJSON(json: any): MailPatchCampaignsByCampaignIdResponse200 {
    return MailPatchCampaignsByCampaignIdResponse200ToJSONTyped(json, false);
}

export function MailPatchCampaignsByCampaignIdResponse200ToJSONTyped(value?: MailPatchCampaignsByCampaignIdResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign': MailCampaignDraftRecordToJSON(value['campaign']),
    };
}

