/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailMessageAnalyticsOverviewVariantsInner
 */
export interface MailMessageAnalyticsOverviewVariantsInner {
    /**
     * 
     */
    accepted: number;
    /**
     * 
     */
    bounced: number;
    /**
     * 
     */
    campaignId?: string;
    /**
     * 
     */
    complained: number;
    /**
     * 
     */
    experimentId?: string;
    /**
     * 
     */
    experimentName?: string;
    /**
     * 
     */
    replied: number;
    /**
     * 
     */
    stepId?: string;
    /**
     * 
     */
    total: number;
    /**
     * 
     */
    variantId: string;
}

/**
 * Check if a given object implements the MailMessageAnalyticsOverviewVariantsInner interface.
 */
export function instanceOfMailMessageAnalyticsOverviewVariantsInner(value: object): value is MailMessageAnalyticsOverviewVariantsInner {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    if (!('bounced' in value) || value['bounced'] === undefined) return false;
    if (!('complained' in value) || value['complained'] === undefined) return false;
    if (!('replied' in value) || value['replied'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('variantId' in value) || value['variantId'] === undefined) return false;
    return true;
}

export function MailMessageAnalyticsOverviewVariantsInnerFromJSON(json: any): MailMessageAnalyticsOverviewVariantsInner {
    return MailMessageAnalyticsOverviewVariantsInnerFromJSONTyped(json, false);
}

export function MailMessageAnalyticsOverviewVariantsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMessageAnalyticsOverviewVariantsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
        'bounced': json['bounced'],
        'campaignId': json['campaignId'] == null ? undefined : json['campaignId'],
        'complained': json['complained'],
        'experimentId': json['experimentId'] == null ? undefined : json['experimentId'],
        'experimentName': json['experimentName'] == null ? undefined : json['experimentName'],
        'replied': json['replied'],
        'stepId': json['stepId'] == null ? undefined : json['stepId'],
        'total': json['total'],
        'variantId': json['variantId'],
    };
}

export function MailMessageAnalyticsOverviewVariantsInnerToJSON(json: any): MailMessageAnalyticsOverviewVariantsInner {
    return MailMessageAnalyticsOverviewVariantsInnerToJSONTyped(json, false);
}

export function MailMessageAnalyticsOverviewVariantsInnerToJSONTyped(value?: MailMessageAnalyticsOverviewVariantsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
        'bounced': value['bounced'],
        'campaignId': value['campaignId'],
        'complained': value['complained'],
        'experimentId': value['experimentId'],
        'experimentName': value['experimentName'],
        'replied': value['replied'],
        'stepId': value['stepId'],
        'total': value['total'],
        'variantId': value['variantId'],
    };
}

