/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailExperimentReportDecision } from './MailExperimentReportDecision.js';
import {
    MailExperimentReportDecisionFromJSON,
    MailExperimentReportDecisionFromJSONTyped,
    MailExperimentReportDecisionToJSON,
    MailExperimentReportDecisionToJSONTyped,
} from './MailExperimentReportDecision.js';
import type { MailExperimentRevisionRecord } from './MailExperimentRevisionRecord.js';
import {
    MailExperimentRevisionRecordFromJSON,
    MailExperimentRevisionRecordFromJSONTyped,
    MailExperimentRevisionRecordToJSON,
    MailExperimentRevisionRecordToJSONTyped,
} from './MailExperimentRevisionRecord.js';
import type { MailExperimentDefinitionRecord } from './MailExperimentDefinitionRecord.js';
import {
    MailExperimentDefinitionRecordFromJSON,
    MailExperimentDefinitionRecordFromJSONTyped,
    MailExperimentDefinitionRecordToJSON,
    MailExperimentDefinitionRecordToJSONTyped,
} from './MailExperimentDefinitionRecord.js';
import type { MailExperimentVariantReport } from './MailExperimentVariantReport.js';
import {
    MailExperimentVariantReportFromJSON,
    MailExperimentVariantReportFromJSONTyped,
    MailExperimentVariantReportToJSON,
    MailExperimentVariantReportToJSONTyped,
} from './MailExperimentVariantReport.js';

/**
 * 
 * @export
 * @interface MailExperimentReport
 */
export interface MailExperimentReport {
    /**
     * 
     */
    assigned: number;
    /**
     * 
     */
    assignmentSampleRatioMismatch: boolean;
    /**
     * 
     */
    automaticDecisionBlockers: Array<string>;
    /**
     * 
     */
    automaticDecisionEligible: boolean;
    /**
     * 
     */
    decision: MailExperimentReportDecision;
    /**
     * 
     */
    decisionBlockers: Array<string>;
    /**
     * 
     */
    definition: MailExperimentDefinitionRecord;
    /**
     * 
     */
    eligibleForDecision: boolean;
    /**
     * 
     */
    exposed: number;
    /**
     * 
     */
    exposureSampleRatioMismatch: boolean;
    /**
     * 
     */
    generatedAt: string;
    /**
     * 
     */
    matured: number;
    /**
     * 
     */
    pendingMaturity: number;
    /**
     * 
     */
    recommendedWinnerVariantId: string | null;
    /**
     * 
     */
    revision: MailExperimentRevisionRecord;
    /**
     * 
     */
    variants: Array<MailExperimentVariantReport>;
}

/**
 * Check if a given object implements the MailExperimentReport interface.
 */
export function instanceOfMailExperimentReport(value: object): value is MailExperimentReport {
    if (!('assigned' in value) || value['assigned'] === undefined) return false;
    if (!('assignmentSampleRatioMismatch' in value) || value['assignmentSampleRatioMismatch'] === undefined) return false;
    if (!('automaticDecisionBlockers' in value) || value['automaticDecisionBlockers'] === undefined) return false;
    if (!('automaticDecisionEligible' in value) || value['automaticDecisionEligible'] === undefined) return false;
    if (!('decision' in value) || value['decision'] === undefined) return false;
    if (!('decisionBlockers' in value) || value['decisionBlockers'] === undefined) return false;
    if (!('definition' in value) || value['definition'] === undefined) return false;
    if (!('eligibleForDecision' in value) || value['eligibleForDecision'] === undefined) return false;
    if (!('exposed' in value) || value['exposed'] === undefined) return false;
    if (!('exposureSampleRatioMismatch' in value) || value['exposureSampleRatioMismatch'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('matured' in value) || value['matured'] === undefined) return false;
    if (!('pendingMaturity' in value) || value['pendingMaturity'] === undefined) return false;
    if (!('recommendedWinnerVariantId' in value) || value['recommendedWinnerVariantId'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('variants' in value) || value['variants'] === undefined) return false;
    return true;
}

export function MailExperimentReportFromJSON(json: any): MailExperimentReport {
    return MailExperimentReportFromJSONTyped(json, false);
}

export function MailExperimentReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailExperimentReport {
    if (json == null) {
        return json;
    }
    return {
        
        'assigned': json['assigned'],
        'assignmentSampleRatioMismatch': json['assignmentSampleRatioMismatch'],
        'automaticDecisionBlockers': json['automaticDecisionBlockers'],
        'automaticDecisionEligible': json['automaticDecisionEligible'],
        'decision': MailExperimentReportDecisionFromJSON(json['decision']),
        'decisionBlockers': json['decisionBlockers'],
        'definition': MailExperimentDefinitionRecordFromJSON(json['definition']),
        'eligibleForDecision': json['eligibleForDecision'],
        'exposed': json['exposed'],
        'exposureSampleRatioMismatch': json['exposureSampleRatioMismatch'],
        'generatedAt': json['generatedAt'],
        'matured': json['matured'],
        'pendingMaturity': json['pendingMaturity'],
        'recommendedWinnerVariantId': json['recommendedWinnerVariantId'],
        'revision': MailExperimentRevisionRecordFromJSON(json['revision']),
        'variants': ((json['variants'] as Array<any>).map(MailExperimentVariantReportFromJSON)),
    };
}

export function MailExperimentReportToJSON(json: any): MailExperimentReport {
    return MailExperimentReportToJSONTyped(json, false);
}

export function MailExperimentReportToJSONTyped(value?: MailExperimentReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assigned': value['assigned'],
        'assignmentSampleRatioMismatch': value['assignmentSampleRatioMismatch'],
        'automaticDecisionBlockers': value['automaticDecisionBlockers'],
        'automaticDecisionEligible': value['automaticDecisionEligible'],
        'decision': MailExperimentReportDecisionToJSON(value['decision']),
        'decisionBlockers': value['decisionBlockers'],
        'definition': MailExperimentDefinitionRecordToJSON(value['definition']),
        'eligibleForDecision': value['eligibleForDecision'],
        'exposed': value['exposed'],
        'exposureSampleRatioMismatch': value['exposureSampleRatioMismatch'],
        'generatedAt': value['generatedAt'],
        'matured': value['matured'],
        'pendingMaturity': value['pendingMaturity'],
        'recommendedWinnerVariantId': value['recommendedWinnerVariantId'],
        'revision': MailExperimentRevisionRecordToJSON(value['revision']),
        'variants': ((value['variants'] as Array<any>).map(MailExperimentVariantReportToJSON)),
    };
}

