/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailMailboxPoolMember
 */
export interface MailMailboxPoolMember {
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    mailboxId: string;
    /**
     * 
     */
    poolId: string;
    /**
     * 
     */
    priority: number;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    updatedAt: string;
    /**
     * 
     */
    weight: number;
}

/**
 * Check if a given object implements the MailMailboxPoolMember interface.
 */
export function instanceOfMailMailboxPoolMember(value: object): value is MailMailboxPoolMember {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('mailboxId' in value) || value['mailboxId'] === undefined) return false;
    if (!('poolId' in value) || value['poolId'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    return true;
}

export function MailMailboxPoolMemberFromJSON(json: any): MailMailboxPoolMember {
    return MailMailboxPoolMemberFromJSONTyped(json, false);
}

export function MailMailboxPoolMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMailboxPoolMember {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'enabled': json['enabled'],
        'mailboxId': json['mailboxId'],
        'poolId': json['poolId'],
        'priority': json['priority'],
        'tenantId': json['tenantId'],
        'updatedAt': json['updatedAt'],
        'weight': json['weight'],
    };
}

export function MailMailboxPoolMemberToJSON(json: any): MailMailboxPoolMember {
    return MailMailboxPoolMemberToJSONTyped(json, false);
}

export function MailMailboxPoolMemberToJSONTyped(value?: MailMailboxPoolMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'enabled': value['enabled'],
        'mailboxId': value['mailboxId'],
        'poolId': value['poolId'],
        'priority': value['priority'],
        'tenantId': value['tenantId'],
        'updatedAt': value['updatedAt'],
        'weight': value['weight'],
    };
}

