/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailDeleteCampaignsByCampaignIdRequest
 */
export interface MailDeleteCampaignsByCampaignIdRequest {
    /**
     * 
     */
    expectedVersion: number;
}

/**
 * Check if a given object implements the MailDeleteCampaignsByCampaignIdRequest interface.
 */
export function instanceOfMailDeleteCampaignsByCampaignIdRequest(value: object): value is MailDeleteCampaignsByCampaignIdRequest {
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    return true;
}

export function MailDeleteCampaignsByCampaignIdRequestFromJSON(json: any): MailDeleteCampaignsByCampaignIdRequest {
    return MailDeleteCampaignsByCampaignIdRequestFromJSONTyped(json, false);
}

export function MailDeleteCampaignsByCampaignIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailDeleteCampaignsByCampaignIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expectedVersion': json['expectedVersion'],
    };
}

export function MailDeleteCampaignsByCampaignIdRequestToJSON(json: any): MailDeleteCampaignsByCampaignIdRequest {
    return MailDeleteCampaignsByCampaignIdRequestToJSONTyped(json, false);
}

export function MailDeleteCampaignsByCampaignIdRequestToJSONTyped(value?: MailDeleteCampaignsByCampaignIdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expectedVersion': value['expectedVersion'],
    };
}

