/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostSuppressionsResponse200
 */
export interface MailPostSuppressionsResponse200 {
    /**
     * 
     */
    created: boolean;
}

/**
 * Check if a given object implements the MailPostSuppressionsResponse200 interface.
 */
export function instanceOfMailPostSuppressionsResponse200(value: object): value is MailPostSuppressionsResponse200 {
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function MailPostSuppressionsResponse200FromJSON(json: any): MailPostSuppressionsResponse200 {
    return MailPostSuppressionsResponse200FromJSONTyped(json, false);
}

export function MailPostSuppressionsResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostSuppressionsResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
    };
}

export function MailPostSuppressionsResponse200ToJSON(json: any): MailPostSuppressionsResponse200 {
    return MailPostSuppressionsResponse200ToJSONTyped(json, false);
}

export function MailPostSuppressionsResponse200ToJSONTyped(value?: MailPostSuppressionsResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
    };
}

