/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailMessageTemplateVersion } from './MailMessageTemplateVersion.js';
import {
    MailMessageTemplateVersionFromJSON,
    MailMessageTemplateVersionFromJSONTyped,
    MailMessageTemplateVersionToJSON,
    MailMessageTemplateVersionToJSONTyped,
} from './MailMessageTemplateVersion.js';

/**
 * 
 * @export
 * @interface MailGetTemplatesResponse200
 */
export interface MailGetTemplatesResponse200 {
    /**
     * 
     */
    results: Array<MailMessageTemplateVersion>;
}

/**
 * Check if a given object implements the MailGetTemplatesResponse200 interface.
 */
export function instanceOfMailGetTemplatesResponse200(value: object): value is MailGetTemplatesResponse200 {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function MailGetTemplatesResponse200FromJSON(json: any): MailGetTemplatesResponse200 {
    return MailGetTemplatesResponse200FromJSONTyped(json, false);
}

export function MailGetTemplatesResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailGetTemplatesResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(MailMessageTemplateVersionFromJSON)),
    };
}

export function MailGetTemplatesResponse200ToJSON(json: any): MailGetTemplatesResponse200 {
    return MailGetTemplatesResponse200ToJSONTyped(json, false);
}

export function MailGetTemplatesResponse200ToJSONTyped(value?: MailGetTemplatesResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(MailMessageTemplateVersionToJSON)),
    };
}

