/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailDomainHealthReport } from './MailDomainHealthReport.js';
import {
    MailDomainHealthReportFromJSON,
    MailDomainHealthReportFromJSONTyped,
    MailDomainHealthReportToJSON,
    MailDomainHealthReportToJSONTyped,
} from './MailDomainHealthReport.js';

/**
 * 
 * @export
 * @interface MailPostDeliverabilityDomainHealthResponse200
 */
export interface MailPostDeliverabilityDomainHealthResponse200 {
    /**
     * 
     */
    report: MailDomainHealthReport;
}

/**
 * Check if a given object implements the MailPostDeliverabilityDomainHealthResponse200 interface.
 */
export function instanceOfMailPostDeliverabilityDomainHealthResponse200(value: object): value is MailPostDeliverabilityDomainHealthResponse200 {
    if (!('report' in value) || value['report'] === undefined) return false;
    return true;
}

export function MailPostDeliverabilityDomainHealthResponse200FromJSON(json: any): MailPostDeliverabilityDomainHealthResponse200 {
    return MailPostDeliverabilityDomainHealthResponse200FromJSONTyped(json, false);
}

export function MailPostDeliverabilityDomainHealthResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostDeliverabilityDomainHealthResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'report': MailDomainHealthReportFromJSON(json['report']),
    };
}

export function MailPostDeliverabilityDomainHealthResponse200ToJSON(json: any): MailPostDeliverabilityDomainHealthResponse200 {
    return MailPostDeliverabilityDomainHealthResponse200ToJSONTyped(json, false);
}

export function MailPostDeliverabilityDomainHealthResponse200ToJSONTyped(value?: MailPostDeliverabilityDomainHealthResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report': MailDomainHealthReportToJSON(value['report']),
    };
}

