/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailExperimentOutcomeRecord
 */
export interface MailExperimentOutcomeRecord {
    /**
     * 
     */
    experimentKey: string;
    /**
     * 
     */
    metadata: object;
    /**
     * 
     */
    occurredAt: string;
    /**
     * 
     */
    outcome: string;
    /**
     * 
     */
    revision: number;
    /**
     * 
     */
    sourceId: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    unitId: string;
    /**
     * 
     */
    value: number;
}

/**
 * Check if a given object implements the MailExperimentOutcomeRecord interface.
 */
export function instanceOfMailExperimentOutcomeRecord(value: object): value is MailExperimentOutcomeRecord {
    if (!('experimentKey' in value) || value['experimentKey'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('sourceId' in value) || value['sourceId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('unitId' in value) || value['unitId'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function MailExperimentOutcomeRecordFromJSON(json: any): MailExperimentOutcomeRecord {
    return MailExperimentOutcomeRecordFromJSONTyped(json, false);
}

export function MailExperimentOutcomeRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailExperimentOutcomeRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'experimentKey': json['experimentKey'],
        'metadata': json['metadata'],
        'occurredAt': json['occurredAt'],
        'outcome': json['outcome'],
        'revision': json['revision'],
        'sourceId': json['sourceId'],
        'tenantId': json['tenantId'],
        'unitId': json['unitId'],
        'value': json['value'],
    };
}

export function MailExperimentOutcomeRecordToJSON(json: any): MailExperimentOutcomeRecord {
    return MailExperimentOutcomeRecordToJSONTyped(json, false);
}

export function MailExperimentOutcomeRecordToJSONTyped(value?: MailExperimentOutcomeRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experimentKey': value['experimentKey'],
        'metadata': value['metadata'],
        'occurredAt': value['occurredAt'],
        'outcome': value['outcome'],
        'revision': value['revision'],
        'sourceId': value['sourceId'],
        'tenantId': value['tenantId'],
        'unitId': value['unitId'],
        'value': value['value'],
    };
}

