/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailExperimentRevisionRecord } from './MailExperimentRevisionRecord.js';
import {
    MailExperimentRevisionRecordFromJSON,
    MailExperimentRevisionRecordFromJSONTyped,
    MailExperimentRevisionRecordToJSON,
    MailExperimentRevisionRecordToJSONTyped,
} from './MailExperimentRevisionRecord.js';
import type { MailExperimentDefinitionRecord } from './MailExperimentDefinitionRecord.js';
import {
    MailExperimentDefinitionRecordFromJSON,
    MailExperimentDefinitionRecordFromJSONTyped,
    MailExperimentDefinitionRecordToJSON,
    MailExperimentDefinitionRecordToJSONTyped,
} from './MailExperimentDefinitionRecord.js';

/**
 * 
 * @export
 * @interface MailGetExperimentsResponse200ResultsInner
 */
export interface MailGetExperimentsResponse200ResultsInner {
    /**
     * 
     */
    definition: MailExperimentDefinitionRecord;
    /**
     * 
     */
    revisions: Array<MailExperimentRevisionRecord>;
}

/**
 * Check if a given object implements the MailGetExperimentsResponse200ResultsInner interface.
 */
export function instanceOfMailGetExperimentsResponse200ResultsInner(value: object): value is MailGetExperimentsResponse200ResultsInner {
    if (!('definition' in value) || value['definition'] === undefined) return false;
    if (!('revisions' in value) || value['revisions'] === undefined) return false;
    return true;
}

export function MailGetExperimentsResponse200ResultsInnerFromJSON(json: any): MailGetExperimentsResponse200ResultsInner {
    return MailGetExperimentsResponse200ResultsInnerFromJSONTyped(json, false);
}

export function MailGetExperimentsResponse200ResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailGetExperimentsResponse200ResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'definition': MailExperimentDefinitionRecordFromJSON(json['definition']),
        'revisions': ((json['revisions'] as Array<any>).map(MailExperimentRevisionRecordFromJSON)),
    };
}

export function MailGetExperimentsResponse200ResultsInnerToJSON(json: any): MailGetExperimentsResponse200ResultsInner {
    return MailGetExperimentsResponse200ResultsInnerToJSONTyped(json, false);
}

export function MailGetExperimentsResponse200ResultsInnerToJSONTyped(value?: MailGetExperimentsResponse200ResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'definition': MailExperimentDefinitionRecordToJSON(value['definition']),
        'revisions': ((value['revisions'] as Array<any>).map(MailExperimentRevisionRecordToJSON)),
    };
}

