/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailGetWebhooksResponse200SubscriptionsInner } from './MailGetWebhooksResponse200SubscriptionsInner.js';
import {
    MailGetWebhooksResponse200SubscriptionsInnerFromJSON,
    MailGetWebhooksResponse200SubscriptionsInnerFromJSONTyped,
    MailGetWebhooksResponse200SubscriptionsInnerToJSON,
    MailGetWebhooksResponse200SubscriptionsInnerToJSONTyped,
} from './MailGetWebhooksResponse200SubscriptionsInner.js';
import type { MailWebhookDelivery } from './MailWebhookDelivery.js';
import {
    MailWebhookDeliveryFromJSON,
    MailWebhookDeliveryFromJSONTyped,
    MailWebhookDeliveryToJSON,
    MailWebhookDeliveryToJSONTyped,
} from './MailWebhookDelivery.js';

/**
 * 
 * @export
 * @interface MailGetWebhooksResponse200
 */
export interface MailGetWebhooksResponse200 {
    /**
     * 
     */
    deliveries: Array<MailWebhookDelivery>;
    /**
     * 
     */
    subscriptions: Array<MailGetWebhooksResponse200SubscriptionsInner>;
}

/**
 * Check if a given object implements the MailGetWebhooksResponse200 interface.
 */
export function instanceOfMailGetWebhooksResponse200(value: object): value is MailGetWebhooksResponse200 {
    if (!('deliveries' in value) || value['deliveries'] === undefined) return false;
    if (!('subscriptions' in value) || value['subscriptions'] === undefined) return false;
    return true;
}

export function MailGetWebhooksResponse200FromJSON(json: any): MailGetWebhooksResponse200 {
    return MailGetWebhooksResponse200FromJSONTyped(json, false);
}

export function MailGetWebhooksResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailGetWebhooksResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'deliveries': ((json['deliveries'] as Array<any>).map(MailWebhookDeliveryFromJSON)),
        'subscriptions': ((json['subscriptions'] as Array<any>).map(MailGetWebhooksResponse200SubscriptionsInnerFromJSON)),
    };
}

export function MailGetWebhooksResponse200ToJSON(json: any): MailGetWebhooksResponse200 {
    return MailGetWebhooksResponse200ToJSONTyped(json, false);
}

export function MailGetWebhooksResponse200ToJSONTyped(value?: MailGetWebhooksResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deliveries': ((value['deliveries'] as Array<any>).map(MailWebhookDeliveryToJSON)),
        'subscriptions': ((value['subscriptions'] as Array<any>).map(MailGetWebhooksResponse200SubscriptionsInnerToJSON)),
    };
}

