/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostCadencesRequestStopConditions
 */
export interface MailPostCadencesRequestStopConditions {
    /**
     * 
     */
    meetingBooked: MailPostCadencesRequestStopConditionsMeetingBookedEnum;
    /**
     * 
     */
    negativeReply: MailPostCadencesRequestStopConditionsNegativeReplyEnum;
    /**
     * 
     */
    outOfOffice: MailPostCadencesRequestStopConditionsOutOfOfficeEnum;
    /**
     * 
     */
    positiveReply: MailPostCadencesRequestStopConditionsPositiveReplyEnum;
    /**
     * 
     */
    unknownHumanReply: MailPostCadencesRequestStopConditionsUnknownHumanReplyEnum;
}


/**
 * @export
 */
export const MailPostCadencesRequestStopConditionsMeetingBookedEnum = {
    Stop: 'stop',
    Continue: 'continue',
} as const;
export type MailPostCadencesRequestStopConditionsMeetingBookedEnum = typeof MailPostCadencesRequestStopConditionsMeetingBookedEnum[keyof typeof MailPostCadencesRequestStopConditionsMeetingBookedEnum];

/**
 * @export
 */
export const MailPostCadencesRequestStopConditionsNegativeReplyEnum = {
    Stop: 'stop',
    Continue: 'continue',
} as const;
export type MailPostCadencesRequestStopConditionsNegativeReplyEnum = typeof MailPostCadencesRequestStopConditionsNegativeReplyEnum[keyof typeof MailPostCadencesRequestStopConditionsNegativeReplyEnum];

/**
 * @export
 */
export const MailPostCadencesRequestStopConditionsOutOfOfficeEnum = {
    Pause: 'pause',
    Stop: 'stop',
    Continue: 'continue',
} as const;
export type MailPostCadencesRequestStopConditionsOutOfOfficeEnum = typeof MailPostCadencesRequestStopConditionsOutOfOfficeEnum[keyof typeof MailPostCadencesRequestStopConditionsOutOfOfficeEnum];

/**
 * @export
 */
export const MailPostCadencesRequestStopConditionsPositiveReplyEnum = {
    Stop: 'stop',
    Continue: 'continue',
} as const;
export type MailPostCadencesRequestStopConditionsPositiveReplyEnum = typeof MailPostCadencesRequestStopConditionsPositiveReplyEnum[keyof typeof MailPostCadencesRequestStopConditionsPositiveReplyEnum];

/**
 * @export
 */
export const MailPostCadencesRequestStopConditionsUnknownHumanReplyEnum = {
    Stop: 'stop',
    Continue: 'continue',
} as const;
export type MailPostCadencesRequestStopConditionsUnknownHumanReplyEnum = typeof MailPostCadencesRequestStopConditionsUnknownHumanReplyEnum[keyof typeof MailPostCadencesRequestStopConditionsUnknownHumanReplyEnum];


/**
 * Check if a given object implements the MailPostCadencesRequestStopConditions interface.
 */
export function instanceOfMailPostCadencesRequestStopConditions(value: object): value is MailPostCadencesRequestStopConditions {
    if (!('meetingBooked' in value) || value['meetingBooked'] === undefined) return false;
    if (!('negativeReply' in value) || value['negativeReply'] === undefined) return false;
    if (!('outOfOffice' in value) || value['outOfOffice'] === undefined) return false;
    if (!('positiveReply' in value) || value['positiveReply'] === undefined) return false;
    if (!('unknownHumanReply' in value) || value['unknownHumanReply'] === undefined) return false;
    return true;
}

export function MailPostCadencesRequestStopConditionsFromJSON(json: any): MailPostCadencesRequestStopConditions {
    return MailPostCadencesRequestStopConditionsFromJSONTyped(json, false);
}

export function MailPostCadencesRequestStopConditionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCadencesRequestStopConditions {
    if (json == null) {
        return json;
    }
    return {
        
        'meetingBooked': json['meetingBooked'],
        'negativeReply': json['negativeReply'],
        'outOfOffice': json['outOfOffice'],
        'positiveReply': json['positiveReply'],
        'unknownHumanReply': json['unknownHumanReply'],
    };
}

export function MailPostCadencesRequestStopConditionsToJSON(json: any): MailPostCadencesRequestStopConditions {
    return MailPostCadencesRequestStopConditionsToJSONTyped(json, false);
}

export function MailPostCadencesRequestStopConditionsToJSONTyped(value?: MailPostCadencesRequestStopConditions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meetingBooked': value['meetingBooked'],
        'negativeReply': value['negativeReply'],
        'outOfOffice': value['outOfOffice'],
        'positiveReply': value['positiveReply'],
        'unknownHumanReply': value['unknownHumanReply'],
    };
}

