/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostPortfolioRequest
 */
export interface MailPostPortfolioRequest {
    /**
     * 
     */
    name: string;
}

/**
 * Check if a given object implements the MailPostPortfolioRequest interface.
 */
export function instanceOfMailPostPortfolioRequest(value: object): value is MailPostPortfolioRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MailPostPortfolioRequestFromJSON(json: any): MailPostPortfolioRequest {
    return MailPostPortfolioRequestFromJSONTyped(json, false);
}

export function MailPostPortfolioRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostPortfolioRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function MailPostPortfolioRequestToJSON(json: any): MailPostPortfolioRequest {
    return MailPostPortfolioRequestToJSONTyped(json, false);
}

export function MailPostPortfolioRequestToJSONTyped(value?: MailPostPortfolioRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

