/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailMailAddress
 */
export interface MailMailAddress {
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    name?: string;
}

/**
 * Check if a given object implements the MailMailAddress interface.
 */
export function instanceOfMailMailAddress(value: object): value is MailMailAddress {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function MailMailAddressFromJSON(json: any): MailMailAddress {
    return MailMailAddressFromJSONTyped(json, false);
}

export function MailMailAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMailAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MailMailAddressToJSON(json: any): MailMailAddress {
    return MailMailAddressToJSONTyped(json, false);
}

export function MailMailAddressToJSONTyped(value?: MailMailAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
    };
}

