/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MailCadenceCampaignRecord } from './MailCadenceCampaignRecord.js';
import {
    MailCadenceCampaignRecordFromJSON,
    MailCadenceCampaignRecordFromJSONTyped,
    MailCadenceCampaignRecordToJSON,
    MailCadenceCampaignRecordToJSONTyped,
} from './MailCadenceCampaignRecord.js';

/**
 * 
 * @export
 * @interface MailGetCadenceCampaignsResponse200
 */
export interface MailGetCadenceCampaignsResponse200 {
    /**
     * 
     */
    results: Array<MailCadenceCampaignRecord>;
}

/**
 * Check if a given object implements the MailGetCadenceCampaignsResponse200 interface.
 */
export function instanceOfMailGetCadenceCampaignsResponse200(value: object): value is MailGetCadenceCampaignsResponse200 {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function MailGetCadenceCampaignsResponse200FromJSON(json: any): MailGetCadenceCampaignsResponse200 {
    return MailGetCadenceCampaignsResponse200FromJSONTyped(json, false);
}

export function MailGetCadenceCampaignsResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailGetCadenceCampaignsResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(MailCadenceCampaignRecordFromJSON)),
    };
}

export function MailGetCadenceCampaignsResponse200ToJSON(json: any): MailGetCadenceCampaignsResponse200 {
    return MailGetCadenceCampaignsResponse200ToJSONTyped(json, false);
}

export function MailGetCadenceCampaignsResponse200ToJSONTyped(value?: MailGetCadenceCampaignsResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(MailCadenceCampaignRecordToJSON)),
    };
}

