/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostCadencesByCadenceIdCopyRequest
 */
export interface MailPostCadencesByCadenceIdCopyRequest {
    /**
     * 
     */
    targetName: string;
    /**
     * 
     */
    targetTeamId: string;
}

/**
 * Check if a given object implements the MailPostCadencesByCadenceIdCopyRequest interface.
 */
export function instanceOfMailPostCadencesByCadenceIdCopyRequest(value: object): value is MailPostCadencesByCadenceIdCopyRequest {
    if (!('targetName' in value) || value['targetName'] === undefined) return false;
    if (!('targetTeamId' in value) || value['targetTeamId'] === undefined) return false;
    return true;
}

export function MailPostCadencesByCadenceIdCopyRequestFromJSON(json: any): MailPostCadencesByCadenceIdCopyRequest {
    return MailPostCadencesByCadenceIdCopyRequestFromJSONTyped(json, false);
}

export function MailPostCadencesByCadenceIdCopyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostCadencesByCadenceIdCopyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetName': json['targetName'],
        'targetTeamId': json['targetTeamId'],
    };
}

export function MailPostCadencesByCadenceIdCopyRequestToJSON(json: any): MailPostCadencesByCadenceIdCopyRequest {
    return MailPostCadencesByCadenceIdCopyRequestToJSONTyped(json, false);
}

export function MailPostCadencesByCadenceIdCopyRequestToJSONTyped(value?: MailPostCadencesByCadenceIdCopyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetName': value['targetName'],
        'targetTeamId': value['targetTeamId'],
    };
}

