/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailPostOauthBeginResponse200
 */
export interface MailPostOauthBeginResponse200 {
    /**
     * 
     */
    authorizationUrl: string;
    /**
     * 
     */
    expiresAt: string;
}

/**
 * Check if a given object implements the MailPostOauthBeginResponse200 interface.
 */
export function instanceOfMailPostOauthBeginResponse200(value: object): value is MailPostOauthBeginResponse200 {
    if (!('authorizationUrl' in value) || value['authorizationUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function MailPostOauthBeginResponse200FromJSON(json: any): MailPostOauthBeginResponse200 {
    return MailPostOauthBeginResponse200FromJSONTyped(json, false);
}

export function MailPostOauthBeginResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailPostOauthBeginResponse200 {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizationUrl': json['authorizationUrl'],
        'expiresAt': json['expiresAt'],
    };
}

export function MailPostOauthBeginResponse200ToJSON(json: any): MailPostOauthBeginResponse200 {
    return MailPostOauthBeginResponse200ToJSONTyped(json, false);
}

export function MailPostOauthBeginResponse200ToJSONTyped(value?: MailPostOauthBeginResponse200 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorizationUrl': value['authorizationUrl'],
        'expiresAt': value['expiresAt'],
    };
}

