/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MailExperimentVariantReportConfidenceInterval95
 */
export interface MailExperimentVariantReportConfidenceInterval95 {
    /**
     * 
     */
    high: number;
    /**
     * 
     */
    low: number;
}

/**
 * Check if a given object implements the MailExperimentVariantReportConfidenceInterval95 interface.
 */
export function instanceOfMailExperimentVariantReportConfidenceInterval95(value: object): value is MailExperimentVariantReportConfidenceInterval95 {
    if (!('high' in value) || value['high'] === undefined) return false;
    if (!('low' in value) || value['low'] === undefined) return false;
    return true;
}

export function MailExperimentVariantReportConfidenceInterval95FromJSON(json: any): MailExperimentVariantReportConfidenceInterval95 {
    return MailExperimentVariantReportConfidenceInterval95FromJSONTyped(json, false);
}

export function MailExperimentVariantReportConfidenceInterval95FromJSONTyped(json: any, ignoreDiscriminator: boolean): MailExperimentVariantReportConfidenceInterval95 {
    if (json == null) {
        return json;
    }
    return {
        
        'high': json['high'],
        'low': json['low'],
    };
}

export function MailExperimentVariantReportConfidenceInterval95ToJSON(json: any): MailExperimentVariantReportConfidenceInterval95 {
    return MailExperimentVariantReportConfidenceInterval95ToJSONTyped(json, false);
}

export function MailExperimentVariantReportConfidenceInterval95ToJSONTyped(value?: MailExperimentVariantReportConfidenceInterval95 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'high': value['high'],
        'low': value['low'],
    };
}

