/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface NameVerificationItem
 */
export interface NameVerificationItem {
    [key: string]: any | any;
    /**
     * 
     */
    error?: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    updatedAt: string;
    /**
     * Known values: deliverable, undeliverable. Clients preserve future values.
     */
    verdict: string;
}

/**
 * Check if a given object implements the NameVerificationItem interface.
 */
export function instanceOfNameVerificationItem(value: object): value is NameVerificationItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    return true;
}

export function NameVerificationItemFromJSON(json: any): NameVerificationItem {
    return NameVerificationItemFromJSONTyped(json, false);
}

export function NameVerificationItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameVerificationItem {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'error': json['error'] == null ? undefined : json['error'],
        'id': json['id'],
        'updatedAt': json['updatedAt'],
        'verdict': json['verdict'],
    };
}

export function NameVerificationItemToJSON(json: any): NameVerificationItem {
    return NameVerificationItemToJSONTyped(json, false);
}

export function NameVerificationItemToJSONTyped(value?: NameVerificationItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'error': value['error'],
        'id': value['id'],
        'updatedAt': value['updatedAt'],
        'verdict': value['verdict'],
    };
}

