/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NameVerificationResponse } from './NameVerificationResponse.js';
import {
    NameVerificationResponseFromJSON,
    NameVerificationResponseFromJSONTyped,
    NameVerificationResponseToJSON,
    NameVerificationResponseToJSONTyped,
} from './NameVerificationResponse.js';

/**
 * 
 * @export
 * @interface NameVerificationEmptyFinal
 */
export interface NameVerificationEmptyFinal {
    [key: string]: any | any;
    /**
     * 
     */
    result: NameVerificationResponse;
    /**
     * 
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the NameVerificationEmptyFinal interface.
 */
export function instanceOfNameVerificationEmptyFinal(value: object): value is NameVerificationEmptyFinal {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function NameVerificationEmptyFinalFromJSON(json: any): NameVerificationEmptyFinal {
    return NameVerificationEmptyFinalFromJSONTyped(json, false);
}

export function NameVerificationEmptyFinalFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameVerificationEmptyFinal {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'result': NameVerificationResponseFromJSON(json['result']),
        'updatedAt': json['updatedAt'],
    };
}

export function NameVerificationEmptyFinalToJSON(json: any): NameVerificationEmptyFinal {
    return NameVerificationEmptyFinalToJSONTyped(json, false);
}

export function NameVerificationEmptyFinalToJSONTyped(value?: NameVerificationEmptyFinal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'result': NameVerificationResponseToJSON(value['result']),
        'updatedAt': value['updatedAt'],
    };
}

