/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { InsightPhone } from './InsightPhone.js';
import {
    InsightPhoneFromJSON,
    InsightPhoneFromJSONTyped,
    InsightPhoneToJSON,
    InsightPhoneToJSONTyped,
} from './InsightPhone.js';
import type { InsightOrganization } from './InsightOrganization.js';
import {
    InsightOrganizationFromJSON,
    InsightOrganizationFromJSONTyped,
    InsightOrganizationToJSON,
    InsightOrganizationToJSONTyped,
} from './InsightOrganization.js';
import type { InsightAddress } from './InsightAddress.js';
import {
    InsightAddressFromJSON,
    InsightAddressFromJSONTyped,
    InsightAddressToJSON,
    InsightAddressToJSONTyped,
} from './InsightAddress.js';
import type { InsightIdentifier } from './InsightIdentifier.js';
import {
    InsightIdentifierFromJSON,
    InsightIdentifierFromJSONTyped,
    InsightIdentifierToJSON,
    InsightIdentifierToJSONTyped,
} from './InsightIdentifier.js';
import type { InsightAttribute } from './InsightAttribute.js';
import {
    InsightAttributeFromJSON,
    InsightAttributeFromJSONTyped,
    InsightAttributeToJSON,
    InsightAttributeToJSONTyped,
} from './InsightAttribute.js';
import type { InsightOffice } from './InsightOffice.js';
import {
    InsightOfficeFromJSON,
    InsightOfficeFromJSONTyped,
    InsightOfficeToJSON,
    InsightOfficeToJSONTyped,
} from './InsightOffice.js';
import type { InsightSource } from './InsightSource.js';
import {
    InsightSourceFromJSON,
    InsightSourceFromJSONTyped,
    InsightSourceToJSON,
    InsightSourceToJSONTyped,
} from './InsightSource.js';
import type { InsightRole } from './InsightRole.js';
import {
    InsightRoleFromJSON,
    InsightRoleFromJSONTyped,
    InsightRoleToJSON,
    InsightRoleToJSONTyped,
} from './InsightRole.js';
import type { InsightSocialProfile } from './InsightSocialProfile.js';
import {
    InsightSocialProfileFromJSON,
    InsightSocialProfileFromJSONTyped,
    InsightSocialProfileToJSON,
    InsightSocialProfileToJSONTyped,
} from './InsightSocialProfile.js';
import type { InsightEvidence } from './InsightEvidence.js';
import {
    InsightEvidenceFromJSON,
    InsightEvidenceFromJSONTyped,
    InsightEvidenceToJSON,
    InsightEvidenceToJSONTyped,
} from './InsightEvidence.js';

/**
 * 
 * @export
 * @interface PersonInsight
 */
export interface PersonInsight {
    [key: string]: any | any;
    /**
     * 
     */
    aka?: Array<string>;
    /**
     * 
     */
    attributes?: Array<InsightAttribute>;
    /**
     * 
     */
    company?: string;
    /**
     * 
     */
    createdAt?: string;
    /**
     * 
     */
    emails?: Array<string>;
    /**
     * 
     */
    evidence?: Array<InsightEvidence>;
    /**
     * 
     */
    firstName?: string;
    /**
     * 
     */
    identifiers?: Array<InsightIdentifier>;
    /**
     * 
     */
    insights: Array<string>;
    /**
     * 
     */
    jobPosition?: string;
    /**
     * 
     */
    lastName?: string;
    /**
     * 
     */
    offices?: Array<InsightOffice>;
    /**
     * 
     */
    organization?: InsightOrganization;
    /**
     * 
     */
    personalAddress?: InsightAddress;
    /**
     * 
     */
    phones?: Array<InsightPhone>;
    /**
     * 
     */
    roles?: Array<InsightRole>;
    /**
     * 
     */
    socialProfiles?: Array<InsightSocialProfile>;
    /**
     * 
     */
    sources?: Array<InsightSource>;
    /**
     * 
     */
    summary: string;
    /**
     * 
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the PersonInsight interface.
 */
export function instanceOfPersonInsight(value: object): value is PersonInsight {
    if (!('insights' in value) || value['insights'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function PersonInsightFromJSON(json: any): PersonInsight {
    return PersonInsightFromJSONTyped(json, false);
}

export function PersonInsightFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonInsight {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'aka': json['aka'] == null ? undefined : json['aka'],
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(InsightAttributeFromJSON)),
        'company': json['company'] == null ? undefined : json['company'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'emails': json['emails'] == null ? undefined : json['emails'],
        'evidence': json['evidence'] == null ? undefined : ((json['evidence'] as Array<any>).map(InsightEvidenceFromJSON)),
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'identifiers': json['identifiers'] == null ? undefined : ((json['identifiers'] as Array<any>).map(InsightIdentifierFromJSON)),
        'insights': json['insights'],
        'jobPosition': json['jobPosition'] == null ? undefined : json['jobPosition'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'offices': json['offices'] == null ? undefined : ((json['offices'] as Array<any>).map(InsightOfficeFromJSON)),
        'organization': json['organization'] == null ? undefined : InsightOrganizationFromJSON(json['organization']),
        'personalAddress': json['personalAddress'] == null ? undefined : InsightAddressFromJSON(json['personalAddress']),
        'phones': json['phones'] == null ? undefined : ((json['phones'] as Array<any>).map(InsightPhoneFromJSON)),
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(InsightRoleFromJSON)),
        'socialProfiles': json['socialProfiles'] == null ? undefined : ((json['socialProfiles'] as Array<any>).map(InsightSocialProfileFromJSON)),
        'sources': json['sources'] == null ? undefined : ((json['sources'] as Array<any>).map(InsightSourceFromJSON)),
        'summary': json['summary'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function PersonInsightToJSON(json: any): PersonInsight {
    return PersonInsightToJSONTyped(json, false);
}

export function PersonInsightToJSONTyped(value?: PersonInsight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'aka': value['aka'],
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(InsightAttributeToJSON)),
        'company': value['company'],
        'createdAt': value['createdAt'],
        'emails': value['emails'],
        'evidence': value['evidence'] == null ? undefined : ((value['evidence'] as Array<any>).map(InsightEvidenceToJSON)),
        'firstName': value['firstName'],
        'identifiers': value['identifiers'] == null ? undefined : ((value['identifiers'] as Array<any>).map(InsightIdentifierToJSON)),
        'insights': value['insights'],
        'jobPosition': value['jobPosition'],
        'lastName': value['lastName'],
        'offices': value['offices'] == null ? undefined : ((value['offices'] as Array<any>).map(InsightOfficeToJSON)),
        'organization': InsightOrganizationToJSON(value['organization']),
        'personalAddress': InsightAddressToJSON(value['personalAddress']),
        'phones': value['phones'] == null ? undefined : ((value['phones'] as Array<any>).map(InsightPhoneToJSON)),
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(InsightRoleToJSON)),
        'socialProfiles': value['socialProfiles'] == null ? undefined : ((value['socialProfiles'] as Array<any>).map(InsightSocialProfileToJSON)),
        'sources': value['sources'] == null ? undefined : ((value['sources'] as Array<any>).map(InsightSourceToJSON)),
        'summary': value['summary'],
        'updatedAt': value['updatedAt'],
    };
}

