/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductSequenceRecipientsAddInputRecipientsInner } from './ProductSequenceRecipientsAddInputRecipientsInner.js';
import {
    ProductSequenceRecipientsAddInputRecipientsInnerFromJSON,
    ProductSequenceRecipientsAddInputRecipientsInnerFromJSONTyped,
    ProductSequenceRecipientsAddInputRecipientsInnerToJSON,
    ProductSequenceRecipientsAddInputRecipientsInnerToJSONTyped,
} from './ProductSequenceRecipientsAddInputRecipientsInner.js';

/**
 * 
 * @export
 * @interface ProductSequenceRecipientsAddInput
 */
export interface ProductSequenceRecipientsAddInput {
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    recipients: Array<ProductSequenceRecipientsAddInputRecipientsInner>;
    /**
     * 
     */
    sequenceId: string;
}

/**
 * Check if a given object implements the ProductSequenceRecipientsAddInput interface.
 */
export function instanceOfProductSequenceRecipientsAddInput(value: object): value is ProductSequenceRecipientsAddInput {
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    if (!('recipients' in value) || value['recipients'] === undefined) return false;
    if (!('sequenceId' in value) || value['sequenceId'] === undefined) return false;
    return true;
}

export function ProductSequenceRecipientsAddInputFromJSON(json: any): ProductSequenceRecipientsAddInput {
    return ProductSequenceRecipientsAddInputFromJSONTyped(json, false);
}

export function ProductSequenceRecipientsAddInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSequenceRecipientsAddInput {
    if (json == null) {
        return json;
    }
    return {
        
        'idempotencyKey': json['idempotencyKey'],
        'recipients': ((json['recipients'] as Array<any>).map(ProductSequenceRecipientsAddInputRecipientsInnerFromJSON)),
        'sequenceId': json['sequenceId'],
    };
}

export function ProductSequenceRecipientsAddInputToJSON(json: any): ProductSequenceRecipientsAddInput {
    return ProductSequenceRecipientsAddInputToJSONTyped(json, false);
}

export function ProductSequenceRecipientsAddInputToJSONTyped(value?: ProductSequenceRecipientsAddInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idempotencyKey': value['idempotencyKey'],
        'recipients': ((value['recipients'] as Array<any>).map(ProductSequenceRecipientsAddInputRecipientsInnerToJSON)),
        'sequenceId': value['sequenceId'],
    };
}

