/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductConnectedApp } from './ProductConnectedApp.js';
import {
    ProductConnectedAppFromJSON,
    ProductConnectedAppFromJSONTyped,
    ProductConnectedAppToJSON,
    ProductConnectedAppToJSONTyped,
} from './ProductConnectedApp.js';

/**
 * 
 * @export
 * @interface ProductConnectedAppsOutput
 */
export interface ProductConnectedAppsOutput {
    /**
     * 
     */
    items: Array<ProductConnectedApp>;
}

/**
 * Check if a given object implements the ProductConnectedAppsOutput interface.
 */
export function instanceOfProductConnectedAppsOutput(value: object): value is ProductConnectedAppsOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ProductConnectedAppsOutputFromJSON(json: any): ProductConnectedAppsOutput {
    return ProductConnectedAppsOutputFromJSONTyped(json, false);
}

export function ProductConnectedAppsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductConnectedAppsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProductConnectedAppFromJSON)),
    };
}

export function ProductConnectedAppsOutputToJSON(json: any): ProductConnectedAppsOutput {
    return ProductConnectedAppsOutputToJSONTyped(json, false);
}

export function ProductConnectedAppsOutputToJSONTyped(value?: ProductConnectedAppsOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProductConnectedAppToJSON)),
    };
}

