/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductCompanyDeleteOutput } from './ProductCompanyDeleteOutput.js';
import {
    ProductCompanyDeleteOutputFromJSON,
    ProductCompanyDeleteOutputFromJSONTyped,
    ProductCompanyDeleteOutputToJSON,
    ProductCompanyDeleteOutputToJSONTyped,
} from './ProductCompanyDeleteOutput.js';

/**
 * 
 * @export
 * @interface ProductCompanyDeleteExecution
 */
export interface ProductCompanyDeleteExecution {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    output: ProductCompanyDeleteOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductCompanyDeleteExecutionToolEnum;
}


/**
 * @export
 */
export const ProductCompanyDeleteExecutionToolEnum = {
    CompanyDelete: 'company_delete',
} as const;
export type ProductCompanyDeleteExecutionToolEnum = typeof ProductCompanyDeleteExecutionToolEnum[keyof typeof ProductCompanyDeleteExecutionToolEnum];


/**
 * Check if a given object implements the ProductCompanyDeleteExecution interface.
 */
export function instanceOfProductCompanyDeleteExecution(value: object): value is ProductCompanyDeleteExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'company_delete') return false;
    
    return true;
}

export function ProductCompanyDeleteExecutionFromJSON(json: any): ProductCompanyDeleteExecution {
    return ProductCompanyDeleteExecutionFromJSONTyped(json, false);
}

export function ProductCompanyDeleteExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyDeleteExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductCompanyDeleteOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductCompanyDeleteExecutionToJSON(json: any): ProductCompanyDeleteExecution {
    return ProductCompanyDeleteExecutionToJSONTyped(json, false);
}

export function ProductCompanyDeleteExecutionToJSONTyped(value?: ProductCompanyDeleteExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductCompanyDeleteOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

