/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductSequenceRecipientsAddOutput } from './ProductSequenceRecipientsAddOutput.js';
import {
    ProductSequenceRecipientsAddOutputFromJSON,
    ProductSequenceRecipientsAddOutputFromJSONTyped,
    ProductSequenceRecipientsAddOutputToJSON,
    ProductSequenceRecipientsAddOutputToJSONTyped,
} from './ProductSequenceRecipientsAddOutput.js';

/**
 * 
 * @export
 * @interface ProductSequenceRecipientsAddExecution
 */
export interface ProductSequenceRecipientsAddExecution {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    output: ProductSequenceRecipientsAddOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductSequenceRecipientsAddExecutionToolEnum;
}


/**
 * @export
 */
export const ProductSequenceRecipientsAddExecutionToolEnum = {
    SequenceRecipientsAdd: 'sequence_recipients_add',
} as const;
export type ProductSequenceRecipientsAddExecutionToolEnum = typeof ProductSequenceRecipientsAddExecutionToolEnum[keyof typeof ProductSequenceRecipientsAddExecutionToolEnum];


/**
 * Check if a given object implements the ProductSequenceRecipientsAddExecution interface.
 */
export function instanceOfProductSequenceRecipientsAddExecution(value: object): value is ProductSequenceRecipientsAddExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'sequence_recipients_add') return false;
    
    return true;
}

export function ProductSequenceRecipientsAddExecutionFromJSON(json: any): ProductSequenceRecipientsAddExecution {
    return ProductSequenceRecipientsAddExecutionFromJSONTyped(json, false);
}

export function ProductSequenceRecipientsAddExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSequenceRecipientsAddExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductSequenceRecipientsAddOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductSequenceRecipientsAddExecutionToJSON(json: any): ProductSequenceRecipientsAddExecution {
    return ProductSequenceRecipientsAddExecutionToJSONTyped(json, false);
}

export function ProductSequenceRecipientsAddExecutionToJSONTyped(value?: ProductSequenceRecipientsAddExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductSequenceRecipientsAddOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

