/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductSequenceRecipientAddOutput } from './ProductSequenceRecipientAddOutput.js';
import {
    ProductSequenceRecipientAddOutputFromJSON,
    ProductSequenceRecipientAddOutputFromJSONTyped,
    ProductSequenceRecipientAddOutputToJSON,
    ProductSequenceRecipientAddOutputToJSONTyped,
} from './ProductSequenceRecipientAddOutput.js';

/**
 * 
 * @export
 * @interface ProductSequenceRecipientAddExecution
 */
export interface ProductSequenceRecipientAddExecution {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    output: ProductSequenceRecipientAddOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductSequenceRecipientAddExecutionToolEnum;
}


/**
 * @export
 */
export const ProductSequenceRecipientAddExecutionToolEnum = {
    SequenceRecipientAdd: 'sequence_recipient_add',
} as const;
export type ProductSequenceRecipientAddExecutionToolEnum = typeof ProductSequenceRecipientAddExecutionToolEnum[keyof typeof ProductSequenceRecipientAddExecutionToolEnum];


/**
 * Check if a given object implements the ProductSequenceRecipientAddExecution interface.
 */
export function instanceOfProductSequenceRecipientAddExecution(value: object): value is ProductSequenceRecipientAddExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'sequence_recipient_add') return false;
    
    return true;
}

export function ProductSequenceRecipientAddExecutionFromJSON(json: any): ProductSequenceRecipientAddExecution {
    return ProductSequenceRecipientAddExecutionFromJSONTyped(json, false);
}

export function ProductSequenceRecipientAddExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSequenceRecipientAddExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductSequenceRecipientAddOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductSequenceRecipientAddExecutionToJSON(json: any): ProductSequenceRecipientAddExecution {
    return ProductSequenceRecipientAddExecutionToJSONTyped(json, false);
}

export function ProductSequenceRecipientAddExecutionToJSONTyped(value?: ProductSequenceRecipientAddExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductSequenceRecipientAddOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

