/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductCompanyListRemoveOutput } from './ProductCompanyListRemoveOutput.js';
import {
    ProductCompanyListRemoveOutputFromJSON,
    ProductCompanyListRemoveOutputFromJSONTyped,
    ProductCompanyListRemoveOutputToJSON,
    ProductCompanyListRemoveOutputToJSONTyped,
} from './ProductCompanyListRemoveOutput.js';

/**
 * 
 * @export
 * @interface ProductCompanyListRemoveExecution
 */
export interface ProductCompanyListRemoveExecution {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    output: ProductCompanyListRemoveOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductCompanyListRemoveExecutionToolEnum;
}


/**
 * @export
 */
export const ProductCompanyListRemoveExecutionToolEnum = {
    CompanyListRemove: 'company_list_remove',
} as const;
export type ProductCompanyListRemoveExecutionToolEnum = typeof ProductCompanyListRemoveExecutionToolEnum[keyof typeof ProductCompanyListRemoveExecutionToolEnum];


/**
 * Check if a given object implements the ProductCompanyListRemoveExecution interface.
 */
export function instanceOfProductCompanyListRemoveExecution(value: object): value is ProductCompanyListRemoveExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'company_list_remove') return false;
    
    return true;
}

export function ProductCompanyListRemoveExecutionFromJSON(json: any): ProductCompanyListRemoveExecution {
    return ProductCompanyListRemoveExecutionFromJSONTyped(json, false);
}

export function ProductCompanyListRemoveExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyListRemoveExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductCompanyListRemoveOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductCompanyListRemoveExecutionToJSON(json: any): ProductCompanyListRemoveExecution {
    return ProductCompanyListRemoveExecutionToJSONTyped(json, false);
}

export function ProductCompanyListRemoveExecutionToJSONTyped(value?: ProductCompanyListRemoveExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductCompanyListRemoveOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

