/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductDiscoverPeopleOutput } from './ProductDiscoverPeopleOutput.js';
import {
    ProductDiscoverPeopleOutputFromJSON,
    ProductDiscoverPeopleOutputFromJSONTyped,
    ProductDiscoverPeopleOutputToJSON,
    ProductDiscoverPeopleOutputToJSONTyped,
} from './ProductDiscoverPeopleOutput.js';

/**
 * 
 * @export
 * @interface ProductDiscoverPeopleExecution
 */
export interface ProductDiscoverPeopleExecution {
    /**
     * 
     */
    executionId: string | null;
    /**
     * 
     */
    output: ProductDiscoverPeopleOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductDiscoverPeopleExecutionToolEnum;
}


/**
 * @export
 */
export const ProductDiscoverPeopleExecutionToolEnum = {
    DiscoverPeople: 'discover_people',
} as const;
export type ProductDiscoverPeopleExecutionToolEnum = typeof ProductDiscoverPeopleExecutionToolEnum[keyof typeof ProductDiscoverPeopleExecutionToolEnum];


/**
 * Check if a given object implements the ProductDiscoverPeopleExecution interface.
 */
export function instanceOfProductDiscoverPeopleExecution(value: object): value is ProductDiscoverPeopleExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'discover_people') return false;
    
    return true;
}

export function ProductDiscoverPeopleExecutionFromJSON(json: any): ProductDiscoverPeopleExecution {
    return ProductDiscoverPeopleExecutionFromJSONTyped(json, false);
}

export function ProductDiscoverPeopleExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDiscoverPeopleExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductDiscoverPeopleOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductDiscoverPeopleExecutionToJSON(json: any): ProductDiscoverPeopleExecution {
    return ProductDiscoverPeopleExecutionToJSONTyped(json, false);
}

export function ProductDiscoverPeopleExecutionToJSONTyped(value?: ProductDiscoverPeopleExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductDiscoverPeopleOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

