/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductCompanyList } from './ProductCompanyList.js';
import {
    ProductCompanyListFromJSON,
    ProductCompanyListFromJSONTyped,
    ProductCompanyListToJSON,
    ProductCompanyListToJSONTyped,
} from './ProductCompanyList.js';

/**
 * 
 * @export
 * @interface ProductCompanyListsListOutput
 */
export interface ProductCompanyListsListOutput {
    /**
     * 
     */
    items: Array<ProductCompanyList>;
}

/**
 * Check if a given object implements the ProductCompanyListsListOutput interface.
 */
export function instanceOfProductCompanyListsListOutput(value: object): value is ProductCompanyListsListOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ProductCompanyListsListOutputFromJSON(json: any): ProductCompanyListsListOutput {
    return ProductCompanyListsListOutputFromJSONTyped(json, false);
}

export function ProductCompanyListsListOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyListsListOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProductCompanyListFromJSON)),
    };
}

export function ProductCompanyListsListOutputToJSON(json: any): ProductCompanyListsListOutput {
    return ProductCompanyListsListOutputToJSONTyped(json, false);
}

export function ProductCompanyListsListOutputToJSONTyped(value?: ProductCompanyListsListOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProductCompanyListToJSON)),
    };
}

