/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductLeadTagRemoveOutput } from './ProductLeadTagRemoveOutput.js';
import {
    ProductLeadTagRemoveOutputFromJSON,
    ProductLeadTagRemoveOutputFromJSONTyped,
    ProductLeadTagRemoveOutputToJSON,
    ProductLeadTagRemoveOutputToJSONTyped,
} from './ProductLeadTagRemoveOutput.js';

/**
 * 
 * @export
 * @interface ProductLeadTagRemoveExecution
 */
export interface ProductLeadTagRemoveExecution {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    output: ProductLeadTagRemoveOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductLeadTagRemoveExecutionToolEnum;
}


/**
 * @export
 */
export const ProductLeadTagRemoveExecutionToolEnum = {
    LeadTagRemove: 'lead_tag_remove',
} as const;
export type ProductLeadTagRemoveExecutionToolEnum = typeof ProductLeadTagRemoveExecutionToolEnum[keyof typeof ProductLeadTagRemoveExecutionToolEnum];


/**
 * Check if a given object implements the ProductLeadTagRemoveExecution interface.
 */
export function instanceOfProductLeadTagRemoveExecution(value: object): value is ProductLeadTagRemoveExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'lead_tag_remove') return false;
    
    return true;
}

export function ProductLeadTagRemoveExecutionFromJSON(json: any): ProductLeadTagRemoveExecution {
    return ProductLeadTagRemoveExecutionFromJSONTyped(json, false);
}

export function ProductLeadTagRemoveExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductLeadTagRemoveExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductLeadTagRemoveOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductLeadTagRemoveExecutionToJSON(json: any): ProductLeadTagRemoveExecution {
    return ProductLeadTagRemoveExecutionToJSONTyped(json, false);
}

export function ProductLeadTagRemoveExecutionToJSONTyped(value?: ProductLeadTagRemoveExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductLeadTagRemoveOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

