/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductLeadDeleteOutput } from './ProductLeadDeleteOutput.js';
import {
    ProductLeadDeleteOutputFromJSON,
    ProductLeadDeleteOutputFromJSONTyped,
    ProductLeadDeleteOutputToJSON,
    ProductLeadDeleteOutputToJSONTyped,
} from './ProductLeadDeleteOutput.js';

/**
 * 
 * @export
 * @interface ProductLeadDeleteExecution
 */
export interface ProductLeadDeleteExecution {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    output: ProductLeadDeleteOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductLeadDeleteExecutionToolEnum;
}


/**
 * @export
 */
export const ProductLeadDeleteExecutionToolEnum = {
    LeadDelete: 'lead_delete',
} as const;
export type ProductLeadDeleteExecutionToolEnum = typeof ProductLeadDeleteExecutionToolEnum[keyof typeof ProductLeadDeleteExecutionToolEnum];


/**
 * Check if a given object implements the ProductLeadDeleteExecution interface.
 */
export function instanceOfProductLeadDeleteExecution(value: object): value is ProductLeadDeleteExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'lead_delete') return false;
    
    return true;
}

export function ProductLeadDeleteExecutionFromJSON(json: any): ProductLeadDeleteExecution {
    return ProductLeadDeleteExecutionFromJSONTyped(json, false);
}

export function ProductLeadDeleteExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductLeadDeleteExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductLeadDeleteOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductLeadDeleteExecutionToJSON(json: any): ProductLeadDeleteExecution {
    return ProductLeadDeleteExecutionToJSONTyped(json, false);
}

export function ProductLeadDeleteExecutionToJSONTyped(value?: ProductLeadDeleteExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductLeadDeleteOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

