/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductPersonSummary } from './ProductPersonSummary.js';
import {
    ProductPersonSummaryFromJSON,
    ProductPersonSummaryFromJSONTyped,
    ProductPersonSummaryToJSON,
    ProductPersonSummaryToJSONTyped,
} from './ProductPersonSummary.js';

/**
 * 
 * @export
 * @interface ProductDiscoverPeopleOutput
 */
export interface ProductDiscoverPeopleOutput {
    /**
     * 
     */
    people: Array<ProductPersonSummary>;
}

/**
 * Check if a given object implements the ProductDiscoverPeopleOutput interface.
 */
export function instanceOfProductDiscoverPeopleOutput(value: object): value is ProductDiscoverPeopleOutput {
    if (!('people' in value) || value['people'] === undefined) return false;
    return true;
}

export function ProductDiscoverPeopleOutputFromJSON(json: any): ProductDiscoverPeopleOutput {
    return ProductDiscoverPeopleOutputFromJSONTyped(json, false);
}

export function ProductDiscoverPeopleOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDiscoverPeopleOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'people': ((json['people'] as Array<any>).map(ProductPersonSummaryFromJSON)),
    };
}

export function ProductDiscoverPeopleOutputToJSON(json: any): ProductDiscoverPeopleOutput {
    return ProductDiscoverPeopleOutputToJSONTyped(json, false);
}

export function ProductDiscoverPeopleOutputToJSONTyped(value?: ProductDiscoverPeopleOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'people': ((value['people'] as Array<any>).map(ProductPersonSummaryToJSON)),
    };
}

