/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductTrackedCompany } from './ProductTrackedCompany.js';
import {
    ProductTrackedCompanyFromJSON,
    ProductTrackedCompanyFromJSONTyped,
    ProductTrackedCompanyToJSON,
    ProductTrackedCompanyToJSONTyped,
} from './ProductTrackedCompany.js';

/**
 * 
 * @export
 * @interface ProductCompaniesListOutput
 */
export interface ProductCompaniesListOutput {
    /**
     * 
     */
    items: Array<ProductTrackedCompany>;
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the ProductCompaniesListOutput interface.
 */
export function instanceOfProductCompaniesListOutput(value: object): value is ProductCompaniesListOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ProductCompaniesListOutputFromJSON(json: any): ProductCompaniesListOutput {
    return ProductCompaniesListOutputFromJSONTyped(json, false);
}

export function ProductCompaniesListOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompaniesListOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProductTrackedCompanyFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function ProductCompaniesListOutputToJSON(json: any): ProductCompaniesListOutput {
    return ProductCompaniesListOutputToJSONTyped(json, false);
}

export function ProductCompaniesListOutputToJSONTyped(value?: ProductCompaniesListOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProductTrackedCompanyToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

