/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductCompanyTrackOutput } from './ProductCompanyTrackOutput.js';
import {
    ProductCompanyTrackOutputFromJSON,
    ProductCompanyTrackOutputFromJSONTyped,
    ProductCompanyTrackOutputToJSON,
    ProductCompanyTrackOutputToJSONTyped,
} from './ProductCompanyTrackOutput.js';

/**
 * 
 * @export
 * @interface ProductCompanyTrackExecution
 */
export interface ProductCompanyTrackExecution {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    output: ProductCompanyTrackOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductCompanyTrackExecutionToolEnum;
}


/**
 * @export
 */
export const ProductCompanyTrackExecutionToolEnum = {
    CompanyTrack: 'company_track',
} as const;
export type ProductCompanyTrackExecutionToolEnum = typeof ProductCompanyTrackExecutionToolEnum[keyof typeof ProductCompanyTrackExecutionToolEnum];


/**
 * Check if a given object implements the ProductCompanyTrackExecution interface.
 */
export function instanceOfProductCompanyTrackExecution(value: object): value is ProductCompanyTrackExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'company_track') return false;
    
    return true;
}

export function ProductCompanyTrackExecutionFromJSON(json: any): ProductCompanyTrackExecution {
    return ProductCompanyTrackExecutionFromJSONTyped(json, false);
}

export function ProductCompanyTrackExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyTrackExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductCompanyTrackOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductCompanyTrackExecutionToJSON(json: any): ProductCompanyTrackExecution {
    return ProductCompanyTrackExecutionToJSONTyped(json, false);
}

export function ProductCompanyTrackExecutionToJSONTyped(value?: ProductCompanyTrackExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductCompanyTrackOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

