/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductUsageHistoryOutput } from './ProductUsageHistoryOutput.js';
import {
    ProductUsageHistoryOutputFromJSON,
    ProductUsageHistoryOutputFromJSONTyped,
    ProductUsageHistoryOutputToJSON,
    ProductUsageHistoryOutputToJSONTyped,
} from './ProductUsageHistoryOutput.js';

/**
 * 
 * @export
 * @interface ProductUsageHistoryExecution
 */
export interface ProductUsageHistoryExecution {
    /**
     * 
     */
    executionId: string | null;
    /**
     * 
     */
    output: ProductUsageHistoryOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductUsageHistoryExecutionToolEnum;
}


/**
 * @export
 */
export const ProductUsageHistoryExecutionToolEnum = {
    UsageHistory: 'usage_history',
} as const;
export type ProductUsageHistoryExecutionToolEnum = typeof ProductUsageHistoryExecutionToolEnum[keyof typeof ProductUsageHistoryExecutionToolEnum];


/**
 * Check if a given object implements the ProductUsageHistoryExecution interface.
 */
export function instanceOfProductUsageHistoryExecution(value: object): value is ProductUsageHistoryExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'usage_history') return false;
    
    return true;
}

export function ProductUsageHistoryExecutionFromJSON(json: any): ProductUsageHistoryExecution {
    return ProductUsageHistoryExecutionFromJSONTyped(json, false);
}

export function ProductUsageHistoryExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUsageHistoryExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductUsageHistoryOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductUsageHistoryExecutionToJSON(json: any): ProductUsageHistoryExecution {
    return ProductUsageHistoryExecutionToJSONTyped(json, false);
}

export function ProductUsageHistoryExecutionToJSONTyped(value?: ProductUsageHistoryExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductUsageHistoryOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

