/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductTeamMembersOutput } from './ProductTeamMembersOutput.js';
import {
    ProductTeamMembersOutputFromJSON,
    ProductTeamMembersOutputFromJSONTyped,
    ProductTeamMembersOutputToJSON,
    ProductTeamMembersOutputToJSONTyped,
} from './ProductTeamMembersOutput.js';

/**
 * 
 * @export
 * @interface ProductTeamMembersExecution
 */
export interface ProductTeamMembersExecution {
    /**
     * 
     */
    executionId: string | null;
    /**
     * 
     */
    output: ProductTeamMembersOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductTeamMembersExecutionToolEnum;
}


/**
 * @export
 */
export const ProductTeamMembersExecutionToolEnum = {
    TeamMembers: 'team_members',
} as const;
export type ProductTeamMembersExecutionToolEnum = typeof ProductTeamMembersExecutionToolEnum[keyof typeof ProductTeamMembersExecutionToolEnum];


/**
 * Check if a given object implements the ProductTeamMembersExecution interface.
 */
export function instanceOfProductTeamMembersExecution(value: object): value is ProductTeamMembersExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'team_members') return false;
    
    return true;
}

export function ProductTeamMembersExecutionFromJSON(json: any): ProductTeamMembersExecution {
    return ProductTeamMembersExecutionFromJSONTyped(json, false);
}

export function ProductTeamMembersExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTeamMembersExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductTeamMembersOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductTeamMembersExecutionToJSON(json: any): ProductTeamMembersExecution {
    return ProductTeamMembersExecutionToJSONTyped(json, false);
}

export function ProductTeamMembersExecutionToJSONTyped(value?: ProductTeamMembersExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductTeamMembersOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

