/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductLeadWithAttributes } from './ProductLeadWithAttributes.js';
import {
    ProductLeadWithAttributesFromJSON,
    ProductLeadWithAttributesFromJSONTyped,
    ProductLeadWithAttributesToJSON,
    ProductLeadWithAttributesToJSONTyped,
} from './ProductLeadWithAttributes.js';

/**
 * 
 * @export
 * @interface ProductLeadEnrichExecution
 */
export interface ProductLeadEnrichExecution {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    output: ProductLeadWithAttributes;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductLeadEnrichExecutionToolEnum;
}


/**
 * @export
 */
export const ProductLeadEnrichExecutionToolEnum = {
    LeadEnrich: 'lead_enrich',
} as const;
export type ProductLeadEnrichExecutionToolEnum = typeof ProductLeadEnrichExecutionToolEnum[keyof typeof ProductLeadEnrichExecutionToolEnum];


/**
 * Check if a given object implements the ProductLeadEnrichExecution interface.
 */
export function instanceOfProductLeadEnrichExecution(value: object): value is ProductLeadEnrichExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'lead_enrich') return false;
    
    return true;
}

export function ProductLeadEnrichExecutionFromJSON(json: any): ProductLeadEnrichExecution {
    return ProductLeadEnrichExecutionFromJSONTyped(json, false);
}

export function ProductLeadEnrichExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductLeadEnrichExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductLeadWithAttributesFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductLeadEnrichExecutionToJSON(json: any): ProductLeadEnrichExecution {
    return ProductLeadEnrichExecutionToJSONTyped(json, false);
}

export function ProductLeadEnrichExecutionToJSONTyped(value?: ProductLeadEnrichExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductLeadWithAttributesToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

