/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductConnectedAppsOutput } from './ProductConnectedAppsOutput.js';
import {
    ProductConnectedAppsOutputFromJSON,
    ProductConnectedAppsOutputFromJSONTyped,
    ProductConnectedAppsOutputToJSON,
    ProductConnectedAppsOutputToJSONTyped,
} from './ProductConnectedAppsOutput.js';

/**
 * 
 * @export
 * @interface ProductConnectedAppsExecution
 */
export interface ProductConnectedAppsExecution {
    /**
     * 
     */
    executionId: string | null;
    /**
     * 
     */
    output: ProductConnectedAppsOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductConnectedAppsExecutionToolEnum;
}


/**
 * @export
 */
export const ProductConnectedAppsExecutionToolEnum = {
    ConnectedApps: 'connected_apps',
} as const;
export type ProductConnectedAppsExecutionToolEnum = typeof ProductConnectedAppsExecutionToolEnum[keyof typeof ProductConnectedAppsExecutionToolEnum];


/**
 * Check if a given object implements the ProductConnectedAppsExecution interface.
 */
export function instanceOfProductConnectedAppsExecution(value: object): value is ProductConnectedAppsExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'connected_apps') return false;
    
    return true;
}

export function ProductConnectedAppsExecutionFromJSON(json: any): ProductConnectedAppsExecution {
    return ProductConnectedAppsExecutionFromJSONTyped(json, false);
}

export function ProductConnectedAppsExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductConnectedAppsExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductConnectedAppsOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductConnectedAppsExecutionToJSON(json: any): ProductConnectedAppsExecution {
    return ProductConnectedAppsExecutionToJSONTyped(json, false);
}

export function ProductConnectedAppsExecutionToJSONTyped(value?: ProductConnectedAppsExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductConnectedAppsOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

