/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductLeadBulkDeleteOutput
 */
export interface ProductLeadBulkDeleteOutput {
    /**
     * 
     */
    deleted: number;
    /**
     * 
     */
    deletedIds: Array<string>;
}

/**
 * Check if a given object implements the ProductLeadBulkDeleteOutput interface.
 */
export function instanceOfProductLeadBulkDeleteOutput(value: object): value is ProductLeadBulkDeleteOutput {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('deletedIds' in value) || value['deletedIds'] === undefined) return false;
    return true;
}

export function ProductLeadBulkDeleteOutputFromJSON(json: any): ProductLeadBulkDeleteOutput {
    return ProductLeadBulkDeleteOutputFromJSONTyped(json, false);
}

export function ProductLeadBulkDeleteOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductLeadBulkDeleteOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
        'deletedIds': json['deletedIds'],
    };
}

export function ProductLeadBulkDeleteOutputToJSON(json: any): ProductLeadBulkDeleteOutput {
    return ProductLeadBulkDeleteOutputToJSONTyped(json, false);
}

export function ProductLeadBulkDeleteOutputToJSONTyped(value?: ProductLeadBulkDeleteOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
        'deletedIds': value['deletedIds'],
    };
}

