/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductTrackedCompany
 */
export interface ProductTrackedCompany {
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    domain: string | null;
    /**
     * 
     */
    employeeRange: string | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    industry: string | null;
    /**
     * 
     */
    name: string | null;
    /**
     * 
     */
    numberOfEmployees: number | null;
    /**
     * 
     */
    website: string | null;
}

/**
 * Check if a given object implements the ProductTrackedCompany interface.
 */
export function instanceOfProductTrackedCompany(value: object): value is ProductTrackedCompany {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('employeeRange' in value) || value['employeeRange'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('industry' in value) || value['industry'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('numberOfEmployees' in value) || value['numberOfEmployees'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    return true;
}

export function ProductTrackedCompanyFromJSON(json: any): ProductTrackedCompany {
    return ProductTrackedCompanyFromJSONTyped(json, false);
}

export function ProductTrackedCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTrackedCompany {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'domain': json['domain'],
        'employeeRange': json['employeeRange'],
        'id': json['id'],
        'industry': json['industry'],
        'name': json['name'],
        'numberOfEmployees': json['numberOfEmployees'],
        'website': json['website'],
    };
}

export function ProductTrackedCompanyToJSON(json: any): ProductTrackedCompany {
    return ProductTrackedCompanyToJSONTyped(json, false);
}

export function ProductTrackedCompanyToJSONTyped(value?: ProductTrackedCompany | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'domain': value['domain'],
        'employeeRange': value['employeeRange'],
        'id': value['id'],
        'industry': value['industry'],
        'name': value['name'],
        'numberOfEmployees': value['numberOfEmployees'],
        'website': value['website'],
    };
}

