/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductUsageTransaction
 */
export interface ProductUsageTransaction {
    /**
     * 
     */
    amount: number;
    /**
     * 
     */
    description: string | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    occurredAt: string;
    /**
     * 
     */
    type: string;
}

/**
 * Check if a given object implements the ProductUsageTransaction interface.
 */
export function instanceOfProductUsageTransaction(value: object): value is ProductUsageTransaction {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ProductUsageTransactionFromJSON(json: any): ProductUsageTransaction {
    return ProductUsageTransactionFromJSONTyped(json, false);
}

export function ProductUsageTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUsageTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'description': json['description'],
        'id': json['id'],
        'occurredAt': json['occurredAt'],
        'type': json['type'],
    };
}

export function ProductUsageTransactionToJSON(json: any): ProductUsageTransaction {
    return ProductUsageTransactionToJSONTyped(json, false);
}

export function ProductUsageTransactionToJSONTyped(value?: ProductUsageTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'description': value['description'],
        'id': value['id'],
        'occurredAt': value['occurredAt'],
        'type': value['type'],
    };
}

