/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductCompanyListAddOutput } from './ProductCompanyListAddOutput.js';
import {
    ProductCompanyListAddOutputFromJSON,
    ProductCompanyListAddOutputFromJSONTyped,
    ProductCompanyListAddOutputToJSON,
    ProductCompanyListAddOutputToJSONTyped,
} from './ProductCompanyListAddOutput.js';

/**
 * 
 * @export
 * @interface ProductCompanyListAddExecution
 */
export interface ProductCompanyListAddExecution {
    /**
     * 
     */
    executionId: string;
    /**
     * 
     */
    output: ProductCompanyListAddOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductCompanyListAddExecutionToolEnum;
}


/**
 * @export
 */
export const ProductCompanyListAddExecutionToolEnum = {
    CompanyListAdd: 'company_list_add',
} as const;
export type ProductCompanyListAddExecutionToolEnum = typeof ProductCompanyListAddExecutionToolEnum[keyof typeof ProductCompanyListAddExecutionToolEnum];


/**
 * Check if a given object implements the ProductCompanyListAddExecution interface.
 */
export function instanceOfProductCompanyListAddExecution(value: object): value is ProductCompanyListAddExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'company_list_add') return false;
    
    return true;
}

export function ProductCompanyListAddExecutionFromJSON(json: any): ProductCompanyListAddExecution {
    return ProductCompanyListAddExecutionFromJSONTyped(json, false);
}

export function ProductCompanyListAddExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyListAddExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductCompanyListAddOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductCompanyListAddExecutionToJSON(json: any): ProductCompanyListAddExecution {
    return ProductCompanyListAddExecutionToJSONTyped(json, false);
}

export function ProductCompanyListAddExecutionToJSONTyped(value?: ProductCompanyListAddExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductCompanyListAddOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

