/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductCompanyEnrichInput
 */
export interface ProductCompanyEnrichInput {
    /**
     * The server applies trim, toLowerCase before validating {"type":"string","pattern":"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z]{2,63}$"}.
     */
    domain: string;
}

/**
 * Check if a given object implements the ProductCompanyEnrichInput interface.
 */
export function instanceOfProductCompanyEnrichInput(value: object): value is ProductCompanyEnrichInput {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function ProductCompanyEnrichInputFromJSON(json: any): ProductCompanyEnrichInput {
    return ProductCompanyEnrichInputFromJSONTyped(json, false);
}

export function ProductCompanyEnrichInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyEnrichInput {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
    };
}

export function ProductCompanyEnrichInputToJSON(json: any): ProductCompanyEnrichInput {
    return ProductCompanyEnrichInputToJSONTyped(json, false);
}

export function ProductCompanyEnrichInputToJSONTyped(value?: ProductCompanyEnrichInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
    };
}

