/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductDiscoverCompaniesOutput } from './ProductDiscoverCompaniesOutput.js';
import {
    ProductDiscoverCompaniesOutputFromJSON,
    ProductDiscoverCompaniesOutputFromJSONTyped,
    ProductDiscoverCompaniesOutputToJSON,
    ProductDiscoverCompaniesOutputToJSONTyped,
} from './ProductDiscoverCompaniesOutput.js';

/**
 * 
 * @export
 * @interface ProductDiscoverCompaniesExecution
 */
export interface ProductDiscoverCompaniesExecution {
    /**
     * 
     */
    executionId: string | null;
    /**
     * 
     */
    output: ProductDiscoverCompaniesOutput;
    /**
     * 
     */
    replay: boolean;
    /**
     * 
     */
    tool: ProductDiscoverCompaniesExecutionToolEnum;
}


/**
 * @export
 */
export const ProductDiscoverCompaniesExecutionToolEnum = {
    DiscoverCompanies: 'discover_companies',
} as const;
export type ProductDiscoverCompaniesExecutionToolEnum = typeof ProductDiscoverCompaniesExecutionToolEnum[keyof typeof ProductDiscoverCompaniesExecutionToolEnum];


/**
 * Check if a given object implements the ProductDiscoverCompaniesExecution interface.
 */
export function instanceOfProductDiscoverCompaniesExecution(value: object): value is ProductDiscoverCompaniesExecution {
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('replay' in value) || value['replay'] === undefined) return false;
    if (!('tool' in value) || value['tool'] === undefined) return false;
    if (value['tool'] !== 'discover_companies') return false;
    
    return true;
}

export function ProductDiscoverCompaniesExecutionFromJSON(json: any): ProductDiscoverCompaniesExecution {
    return ProductDiscoverCompaniesExecutionFromJSONTyped(json, false);
}

export function ProductDiscoverCompaniesExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDiscoverCompaniesExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'output': ProductDiscoverCompaniesOutputFromJSON(json['output']),
        'replay': json['replay'],
        'tool': json['tool'],
    };
}

export function ProductDiscoverCompaniesExecutionToJSON(json: any): ProductDiscoverCompaniesExecution {
    return ProductDiscoverCompaniesExecutionToJSONTyped(json, false);
}

export function ProductDiscoverCompaniesExecutionToJSONTyped(value?: ProductDiscoverCompaniesExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executionId': value['executionId'],
        'output': ProductDiscoverCompaniesOutputToJSON(value['output']),
        'replay': value['replay'],
        'tool': value['tool'],
    };
}

