/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductCompanyDeleteOutput
 */
export interface ProductCompanyDeleteOutput {
    /**
     * 
     */
    companyId: string;
    /**
     * 
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the ProductCompanyDeleteOutput interface.
 */
export function instanceOfProductCompanyDeleteOutput(value: object): value is ProductCompanyDeleteOutput {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function ProductCompanyDeleteOutputFromJSON(json: any): ProductCompanyDeleteOutput {
    return ProductCompanyDeleteOutputFromJSONTyped(json, false);
}

export function ProductCompanyDeleteOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyDeleteOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['companyId'],
        'deleted': json['deleted'],
    };
}

export function ProductCompanyDeleteOutputToJSON(json: any): ProductCompanyDeleteOutput {
    return ProductCompanyDeleteOutputToJSONTyped(json, false);
}

export function ProductCompanyDeleteOutputToJSONTyped(value?: ProductCompanyDeleteOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyId': value['companyId'],
        'deleted': value['deleted'],
    };
}

