/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductTeamMember
 */
export interface ProductTeamMember {
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    role: string;
}

/**
 * Check if a given object implements the ProductTeamMember interface.
 */
export function instanceOfProductTeamMember(value: object): value is ProductTeamMember {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ProductTeamMemberFromJSON(json: any): ProductTeamMember {
    return ProductTeamMemberFromJSONTyped(json, false);
}

export function ProductTeamMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTeamMember {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'id': json['id'],
        'role': json['role'],
    };
}

export function ProductTeamMemberToJSON(json: any): ProductTeamMember {
    return ProductTeamMemberToJSONTyped(json, false);
}

export function ProductTeamMemberToJSONTyped(value?: ProductTeamMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'id': value['id'],
        'role': value['role'],
    };
}

