/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ProductLead } from './ProductLead.js';
import {
    ProductLeadFromJSON,
    ProductLeadFromJSONTyped,
    ProductLeadToJSON,
    ProductLeadToJSONTyped,
} from './ProductLead.js';

/**
 * 
 * @export
 * @interface ProductLeadsListOutput
 */
export interface ProductLeadsListOutput {
    /**
     * 
     */
    items: Array<ProductLead>;
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the ProductLeadsListOutput interface.
 */
export function instanceOfProductLeadsListOutput(value: object): value is ProductLeadsListOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ProductLeadsListOutputFromJSON(json: any): ProductLeadsListOutput {
    return ProductLeadsListOutputFromJSONTyped(json, false);
}

export function ProductLeadsListOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductLeadsListOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProductLeadFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function ProductLeadsListOutputToJSON(json: any): ProductLeadsListOutput {
    return ProductLeadsListOutputToJSONTyped(json, false);
}

export function ProductLeadsListOutputToJSONTyped(value?: ProductLeadsListOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProductLeadToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

