/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductDomainFinderOutput
 */
export interface ProductDomainFinderOutput {
    /**
     * Decimal confidence serialized by PostgreSQL as text (currently 1 or 0.8).
     */
    confidence: string;
    /**
     * 
     */
    domain: string | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string | null;
    /**
     * 
     */
    website: string | null;
}

/**
 * Check if a given object implements the ProductDomainFinderOutput interface.
 */
export function instanceOfProductDomainFinderOutput(value: object): value is ProductDomainFinderOutput {
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    return true;
}

export function ProductDomainFinderOutputFromJSON(json: any): ProductDomainFinderOutput {
    return ProductDomainFinderOutputFromJSONTyped(json, false);
}

export function ProductDomainFinderOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDomainFinderOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'confidence': json['confidence'],
        'domain': json['domain'],
        'id': json['id'],
        'name': json['name'],
        'website': json['website'],
    };
}

export function ProductDomainFinderOutputToJSON(json: any): ProductDomainFinderOutput {
    return ProductDomainFinderOutputToJSONTyped(json, false);
}

export function ProductDomainFinderOutputToJSONTyped(value?: ProductDomainFinderOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'confidence': value['confidence'],
        'domain': value['domain'],
        'id': value['id'],
        'name': value['name'],
        'website': value['website'],
    };
}

