/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductLeadTagCreateInput
 */
export interface ProductLeadTagCreateInput {
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * The server applies trim before validating {"type":"string","minLength":1,"maxLength":500}.
     */
    name: string;
}

/**
 * Check if a given object implements the ProductLeadTagCreateInput interface.
 */
export function instanceOfProductLeadTagCreateInput(value: object): value is ProductLeadTagCreateInput {
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProductLeadTagCreateInputFromJSON(json: any): ProductLeadTagCreateInput {
    return ProductLeadTagCreateInputFromJSONTyped(json, false);
}

export function ProductLeadTagCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductLeadTagCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'idempotencyKey': json['idempotencyKey'],
        'name': json['name'],
    };
}

export function ProductLeadTagCreateInputToJSON(json: any): ProductLeadTagCreateInput {
    return ProductLeadTagCreateInputToJSONTyped(json, false);
}

export function ProductLeadTagCreateInputToJSONTyped(value?: ProductLeadTagCreateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idempotencyKey': value['idempotencyKey'],
        'name': value['name'],
    };
}

