/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductCompanyUpdateInput
 */
export interface ProductCompanyUpdateInput {
    /**
     * 
     */
    companyId: string;
    /**
     * 
     */
    employeeRange?: string;
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    industry?: string;
    /**
     * 
     */
    name?: string;
}

/**
 * Check if a given object implements the ProductCompanyUpdateInput interface.
 */
export function instanceOfProductCompanyUpdateInput(value: object): value is ProductCompanyUpdateInput {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    return true;
}

export function ProductCompanyUpdateInputFromJSON(json: any): ProductCompanyUpdateInput {
    return ProductCompanyUpdateInputFromJSONTyped(json, false);
}

export function ProductCompanyUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['companyId'],
        'employeeRange': json['employeeRange'] == null ? undefined : json['employeeRange'],
        'idempotencyKey': json['idempotencyKey'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ProductCompanyUpdateInputToJSON(json: any): ProductCompanyUpdateInput {
    return ProductCompanyUpdateInputToJSONTyped(json, false);
}

export function ProductCompanyUpdateInputToJSONTyped(value?: ProductCompanyUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyId': value['companyId'],
        'employeeRange': value['employeeRange'],
        'idempotencyKey': value['idempotencyKey'],
        'industry': value['industry'],
        'name': value['name'],
    };
}

