/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductLeadUpsertInput
 */
export interface ProductLeadUpsertInput {
    /**
     * Attribute names must be at most 100 characters. The server enforces this constraint.
     */
    attributes?: { [key: string]: string; };
    /**
     * 
     */
    company?: string;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    firstName?: string;
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    lastName?: string;
    /**
     * 
     */
    position?: string;
}

/**
 * Check if a given object implements the ProductLeadUpsertInput interface.
 */
export function instanceOfProductLeadUpsertInput(value: object): value is ProductLeadUpsertInput {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    return true;
}

export function ProductLeadUpsertInputFromJSON(json: any): ProductLeadUpsertInput {
    return ProductLeadUpsertInputFromJSONTyped(json, false);
}

export function ProductLeadUpsertInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductLeadUpsertInput {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'company': json['company'] == null ? undefined : json['company'],
        'email': json['email'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'idempotencyKey': json['idempotencyKey'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function ProductLeadUpsertInputToJSON(json: any): ProductLeadUpsertInput {
    return ProductLeadUpsertInputToJSONTyped(json, false);
}

export function ProductLeadUpsertInputToJSONTyped(value?: ProductLeadUpsertInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'],
        'company': value['company'],
        'email': value['email'],
        'firstName': value['firstName'],
        'idempotencyKey': value['idempotencyKey'],
        'lastName': value['lastName'],
        'position': value['position'],
    };
}

