/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductCompanyUpdateOutput
 */
export interface ProductCompanyUpdateOutput {
    /**
     * 
     */
    companyId: string;
    /**
     * 
     */
    employeeRange: string | null;
    /**
     * 
     */
    industry: string | null;
    /**
     * 
     */
    name: string | null;
}

/**
 * Check if a given object implements the ProductCompanyUpdateOutput interface.
 */
export function instanceOfProductCompanyUpdateOutput(value: object): value is ProductCompanyUpdateOutput {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('employeeRange' in value) || value['employeeRange'] === undefined) return false;
    if (!('industry' in value) || value['industry'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProductCompanyUpdateOutputFromJSON(json: any): ProductCompanyUpdateOutput {
    return ProductCompanyUpdateOutputFromJSONTyped(json, false);
}

export function ProductCompanyUpdateOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyUpdateOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['companyId'],
        'employeeRange': json['employeeRange'],
        'industry': json['industry'],
        'name': json['name'],
    };
}

export function ProductCompanyUpdateOutputToJSON(json: any): ProductCompanyUpdateOutput {
    return ProductCompanyUpdateOutputToJSONTyped(json, false);
}

export function ProductCompanyUpdateOutputToJSONTyped(value?: ProductCompanyUpdateOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyId': value['companyId'],
        'employeeRange': value['employeeRange'],
        'industry': value['industry'],
        'name': value['name'],
    };
}

