/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductLeadTagAssignOutput
 */
export interface ProductLeadTagAssignOutput {
    /**
     * 
     */
    assigned: boolean;
    /**
     * 
     */
    leadId: string;
    /**
     * 
     */
    tagId: string;
}

/**
 * Check if a given object implements the ProductLeadTagAssignOutput interface.
 */
export function instanceOfProductLeadTagAssignOutput(value: object): value is ProductLeadTagAssignOutput {
    if (!('assigned' in value) || value['assigned'] === undefined) return false;
    if (!('leadId' in value) || value['leadId'] === undefined) return false;
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    return true;
}

export function ProductLeadTagAssignOutputFromJSON(json: any): ProductLeadTagAssignOutput {
    return ProductLeadTagAssignOutputFromJSONTyped(json, false);
}

export function ProductLeadTagAssignOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductLeadTagAssignOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'assigned': json['assigned'],
        'leadId': json['leadId'],
        'tagId': json['tagId'],
    };
}

export function ProductLeadTagAssignOutputToJSON(json: any): ProductLeadTagAssignOutput {
    return ProductLeadTagAssignOutputToJSONTyped(json, false);
}

export function ProductLeadTagAssignOutputToJSONTyped(value?: ProductLeadTagAssignOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assigned': value['assigned'],
        'leadId': value['leadId'],
        'tagId': value['tagId'],
    };
}

