/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProductCompanyList
 */
export interface ProductCompanyList {
    /**
     * 
     */
    companyCount: number;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the ProductCompanyList interface.
 */
export function instanceOfProductCompanyList(value: object): value is ProductCompanyList {
    if (!('companyCount' in value) || value['companyCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProductCompanyListFromJSON(json: any): ProductCompanyList {
    return ProductCompanyListFromJSONTyped(json, false);
}

export function ProductCompanyListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCompanyList {
    if (json == null) {
        return json;
    }
    return {
        
        'companyCount': json['companyCount'],
        'createdAt': json['createdAt'],
        'id': json['id'],
        'name': json['name'],
        'updatedAt': json['updatedAt'],
    };
}

export function ProductCompanyListToJSON(json: any): ProductCompanyList {
    return ProductCompanyListToJSONTyped(json, false);
}

export function ProductCompanyListToJSONTyped(value?: ProductCompanyList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyCount': value['companyCount'],
        'createdAt': value['createdAt'],
        'id': value['id'],
        'name': value['name'],
        'updatedAt': value['updatedAt'],
    };
}

