/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface QueueNotificationTestRequest
 */
export interface QueueNotificationTestRequest {
    /**
     * 
     */
    requestId?: string;
}

/**
 * Check if a given object implements the QueueNotificationTestRequest interface.
 */
export function instanceOfQueueNotificationTestRequest(value: object): value is QueueNotificationTestRequest {
    return true;
}

export function QueueNotificationTestRequestFromJSON(json: any): QueueNotificationTestRequest {
    return QueueNotificationTestRequestFromJSONTyped(json, false);
}

export function QueueNotificationTestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueNotificationTestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
    };
}

export function QueueNotificationTestRequestToJSON(json: any): QueueNotificationTestRequest {
    return QueueNotificationTestRequestToJSONTyped(json, false);
}

export function QueueNotificationTestRequestToJSONTyped(value?: QueueNotificationTestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestId': value['requestId'],
    };
}

