/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type QueuedIntegrationJobStreamPosition
 * Database cursor position, serialized as a string or number; null when absent.
 * @export
 */
export type QueuedIntegrationJobStreamPosition = number | string;

export function QueuedIntegrationJobStreamPositionFromJSON(json: any): QueuedIntegrationJobStreamPosition {
    return QueuedIntegrationJobStreamPositionFromJSONTyped(json, false);
}

export function QueuedIntegrationJobStreamPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueuedIntegrationJobStreamPosition {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function QueuedIntegrationJobStreamPositionToJSON(json: any): any {
    return QueuedIntegrationJobStreamPositionToJSONTyped(json, false);
}

export function QueuedIntegrationJobStreamPositionToJSONTyped(value?: QueuedIntegrationJobStreamPosition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

