/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SaveSheetWorkflowRequest
 */
export interface SaveSheetWorkflowRequest {
    /**
     * 
     */
    config: object;
    /**
     * 
     */
    connectionId: string;
    /**
     * 
     */
    label: string;
    /**
     * 
     */
    workflowId?: string;
}

/**
 * Check if a given object implements the SaveSheetWorkflowRequest interface.
 */
export function instanceOfSaveSheetWorkflowRequest(value: object): value is SaveSheetWorkflowRequest {
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function SaveSheetWorkflowRequestFromJSON(json: any): SaveSheetWorkflowRequest {
    return SaveSheetWorkflowRequestFromJSONTyped(json, false);
}

export function SaveSheetWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveSheetWorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'],
        'connectionId': json['connectionId'],
        'label': json['label'],
        'workflowId': json['workflowId'] == null ? undefined : json['workflowId'],
    };
}

export function SaveSheetWorkflowRequestToJSON(json: any): SaveSheetWorkflowRequest {
    return SaveSheetWorkflowRequestToJSONTyped(json, false);
}

export function SaveSheetWorkflowRequestToJSONTyped(value?: SaveSheetWorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'connectionId': value['connectionId'],
        'label': value['label'],
        'workflowId': value['workflowId'],
    };
}

