/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SheetWorkflow } from './SheetWorkflow.js';
import {
    SheetWorkflowFromJSON,
    SheetWorkflowFromJSONTyped,
    SheetWorkflowToJSON,
    SheetWorkflowToJSONTyped,
} from './SheetWorkflow.js';

/**
 * 
 * @export
 * @interface SheetWorkflowResponse
 */
export interface SheetWorkflowResponse {
    [key: string]: any | any;
    /**
     * 
     */
    workflow: SheetWorkflow;
}

/**
 * Check if a given object implements the SheetWorkflowResponse interface.
 */
export function instanceOfSheetWorkflowResponse(value: object): value is SheetWorkflowResponse {
    if (!('workflow' in value) || value['workflow'] === undefined) return false;
    return true;
}

export function SheetWorkflowResponseFromJSON(json: any): SheetWorkflowResponse {
    return SheetWorkflowResponseFromJSONTyped(json, false);
}

export function SheetWorkflowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetWorkflowResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'workflow': SheetWorkflowFromJSON(json['workflow']),
    };
}

export function SheetWorkflowResponseToJSON(json: any): SheetWorkflowResponse {
    return SheetWorkflowResponseToJSONTyped(json, false);
}

export function SheetWorkflowResponseToJSONTyped(value?: SheetWorkflowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'workflow': SheetWorkflowToJSON(value['workflow']),
    };
}

