/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SheetWorkflowPreviewRowsInner
 */
export interface SheetWorkflowPreviewRowsInner {
    [key: string]: any | any;
    /**
     * Input for the workflow capability, built from this spreadsheet row.
     */
    input: { [key: string]: any; };
    /**
     * 
     */
    rowNumber: number;
}

/**
 * Check if a given object implements the SheetWorkflowPreviewRowsInner interface.
 */
export function instanceOfSheetWorkflowPreviewRowsInner(value: object): value is SheetWorkflowPreviewRowsInner {
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('rowNumber' in value) || value['rowNumber'] === undefined) return false;
    return true;
}

export function SheetWorkflowPreviewRowsInnerFromJSON(json: any): SheetWorkflowPreviewRowsInner {
    return SheetWorkflowPreviewRowsInnerFromJSONTyped(json, false);
}

export function SheetWorkflowPreviewRowsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetWorkflowPreviewRowsInner {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'input': json['input'],
        'rowNumber': json['rowNumber'],
    };
}

export function SheetWorkflowPreviewRowsInnerToJSON(json: any): SheetWorkflowPreviewRowsInner {
    return SheetWorkflowPreviewRowsInnerToJSONTyped(json, false);
}

export function SheetWorkflowPreviewRowsInnerToJSONTyped(value?: SheetWorkflowPreviewRowsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'input': value['input'],
        'rowNumber': value['rowNumber'],
    };
}

