/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SheetWorkflow } from './SheetWorkflow.js';
import {
    SheetWorkflowFromJSON,
    SheetWorkflowFromJSONTyped,
    SheetWorkflowToJSON,
    SheetWorkflowToJSONTyped,
} from './SheetWorkflow.js';

/**
 * 
 * @export
 * @interface SheetWorkflowList
 */
export interface SheetWorkflowList {
    [key: string]: any | any;
    /**
     * 
     */
    workflows: Array<SheetWorkflow>;
}

/**
 * Check if a given object implements the SheetWorkflowList interface.
 */
export function instanceOfSheetWorkflowList(value: object): value is SheetWorkflowList {
    if (!('workflows' in value) || value['workflows'] === undefined) return false;
    return true;
}

export function SheetWorkflowListFromJSON(json: any): SheetWorkflowList {
    return SheetWorkflowListFromJSONTyped(json, false);
}

export function SheetWorkflowListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetWorkflowList {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'workflows': ((json['workflows'] as Array<any>).map(SheetWorkflowFromJSON)),
    };
}

export function SheetWorkflowListToJSON(json: any): SheetWorkflowList {
    return SheetWorkflowListToJSONTyped(json, false);
}

export function SheetWorkflowListToJSONTyped(value?: SheetWorkflowList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'workflows': ((value['workflows'] as Array<any>).map(SheetWorkflowToJSON)),
    };
}

