/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StartIntegrationOAuthRequest
 */
export interface StartIntegrationOAuthRequest {
    /**
     * 
     */
    authorizationServer?: string;
    /**
     * 
     */
    resourceUrl?: string;
    /**
     * 
     */
    returnPath?: string;
}

/**
 * Check if a given object implements the StartIntegrationOAuthRequest interface.
 */
export function instanceOfStartIntegrationOAuthRequest(value: object): value is StartIntegrationOAuthRequest {
    return true;
}

export function StartIntegrationOAuthRequestFromJSON(json: any): StartIntegrationOAuthRequest {
    return StartIntegrationOAuthRequestFromJSONTyped(json, false);
}

export function StartIntegrationOAuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartIntegrationOAuthRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizationServer': json['authorizationServer'] == null ? undefined : json['authorizationServer'],
        'resourceUrl': json['resourceUrl'] == null ? undefined : json['resourceUrl'],
        'returnPath': json['returnPath'] == null ? undefined : json['returnPath'],
    };
}

export function StartIntegrationOAuthRequestToJSON(json: any): StartIntegrationOAuthRequest {
    return StartIntegrationOAuthRequestToJSONTyped(json, false);
}

export function StartIntegrationOAuthRequestToJSONTyped(value?: StartIntegrationOAuthRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorizationServer': value['authorizationServer'],
        'resourceUrl': value['resourceUrl'],
        'returnPath': value['returnPath'],
    };
}

