/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
const reaconAdditionalPropertyCollisions = Symbol('reacon.additionalPropertyCollisions');
import type { CompanyListResultsInnerAddressesInner } from './CompanyListResultsInnerAddressesInner.js';
import {
    CompanyListResultsInnerAddressesInnerFromJSON,
    CompanyListResultsInnerAddressesInnerFromJSONTyped,
    CompanyListResultsInnerAddressesInnerToJSON,
    CompanyListResultsInnerAddressesInnerToJSONTyped,
} from './CompanyListResultsInnerAddressesInner.js';

/**
 * 
 * @export
 * @interface UpdateLeadRequestCompany
 */
export interface UpdateLeadRequestCompany {
    [key: string]: any | any;
    /**
     * 
     */
    addresses?: Array<CompanyListResultsInnerAddressesInner> | null;
    /**
     * 
     */
    foundedOn?: string | null;
    /**
     * 
     */
    industry?: string | null;
    /**
     * 
     */
    linkedin?: string | null;
    /**
     * 
     */
    location?: string | null;
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    numberOfEmployees?: number | null;
    /**
     * 
     */
    stock?: string | null;
    /**
     * 
     */
    twitter?: string | null;
    /**
     * 
     */
    type?: string | null;
    /**
     * 
     */
    website?: string | null;
}

/**
 * Check if a given object implements the UpdateLeadRequestCompany interface.
 */
export function instanceOfUpdateLeadRequestCompany(value: object): value is UpdateLeadRequestCompany {
    return true;
}

export function UpdateLeadRequestCompanyFromJSON(json: any): UpdateLeadRequestCompany {
    return UpdateLeadRequestCompanyFromJSONTyped(json, false);
}

export function UpdateLeadRequestCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLeadRequestCompany {
    if (json == null) {
        return json;
    }
    return {
        
            ...Object.fromEntries(Object.entries(json).filter(([key]) => !["addresses","founded_on","industry","linkedin","location","name","number_of_employees","stock","twitter","type","website"].includes(key))),
            ...{ [reaconAdditionalPropertyCollisions]: Object.fromEntries(Object.entries(json).filter(([key]) => ["foundedOn","numberOfEmployees"].includes(key))) },
        'addresses': json['addresses'] === undefined ? undefined : json['addresses'] === null ? null : ((json['addresses'] as Array<any>).map(CompanyListResultsInnerAddressesInnerFromJSON)),
        'foundedOn': json['founded_on'] === undefined ? undefined : json['founded_on'] === null ? null : json['founded_on'],
        'industry': json['industry'] === undefined ? undefined : json['industry'] === null ? null : json['industry'],
        'linkedin': json['linkedin'] === undefined ? undefined : json['linkedin'] === null ? null : json['linkedin'],
        'location': json['location'] === undefined ? undefined : json['location'] === null ? null : json['location'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'numberOfEmployees': json['number_of_employees'] === undefined ? undefined : json['number_of_employees'] === null ? null : json['number_of_employees'],
        'stock': json['stock'] === undefined ? undefined : json['stock'] === null ? null : json['stock'],
        'twitter': json['twitter'] === undefined ? undefined : json['twitter'] === null ? null : json['twitter'],
        'type': json['type'] === undefined ? undefined : json['type'] === null ? null : json['type'],
        'website': json['website'] === undefined ? undefined : json['website'] === null ? null : json['website'],
    };
}

export function UpdateLeadRequestCompanyToJSON(json: any): UpdateLeadRequestCompany {
    return UpdateLeadRequestCompanyToJSONTyped(json, false);
}

export function UpdateLeadRequestCompanyToJSONTyped(value?: UpdateLeadRequestCompany | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...Object.fromEntries(Object.entries(value).filter(([key]) => !["addresses","foundedOn","industry","linkedin","location","name","numberOfEmployees","stock","twitter","type","website"].includes(key))),
            ...((value as any)[reaconAdditionalPropertyCollisions] ?? {}),
        'addresses': value['addresses'] === undefined ? undefined : value['addresses'] === null ? null : ((value['addresses'] as Array<any>).map(CompanyListResultsInnerAddressesInnerToJSON)),
        'founded_on': value['foundedOn'],
        'industry': value['industry'],
        'linkedin': value['linkedin'],
        'location': value['location'],
        'name': value['name'],
        'number_of_employees': value['numberOfEmployees'],
        'stock': value['stock'],
        'twitter': value['twitter'],
        'type': value['type'],
        'website': value['website'],
    };
}

