/* tslint:disable */
/* eslint-disable */
/**
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VerificationResult
 */
export interface VerificationResult {
    [key: string]: any | any;
    /**
     * 
     */
    acceptsAll: boolean | null;
    /**
     * 
     */
    cached?: boolean;
    /**
     * Known values: live, 1d, 1w, 1m. Clients preserve future values.
     */
    cachePolicy?: string;
    /**
     * 
     */
    catchAll: boolean;
    /**
     * 
     */
    disposable: boolean;
    /**
     * 
     */
    mxHost?: string;
    /**
     * 
     */
    resolvedIp?: string;
    /**
     * 
     */
    score?: number;
    /**
     * Known values: deliverable, risky, undeliverable. Clients preserve future values.
     */
    status: string;
}

/**
 * Check if a given object implements the VerificationResult interface.
 */
export function instanceOfVerificationResult(value: object): value is VerificationResult {
    if (!('acceptsAll' in value) || value['acceptsAll'] === undefined) return false;
    if (!('catchAll' in value) || value['catchAll'] === undefined) return false;
    if (!('disposable' in value) || value['disposable'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function VerificationResultFromJSON(json: any): VerificationResult {
    return VerificationResultFromJSONTyped(json, false);
}

export function VerificationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationResult {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'acceptsAll': json['acceptsAll'],
        'cached': json['cached'] == null ? undefined : json['cached'],
        'cachePolicy': json['cachePolicy'] == null ? undefined : json['cachePolicy'],
        'catchAll': json['catchAll'],
        'disposable': json['disposable'],
        'mxHost': json['mxHost'] == null ? undefined : json['mxHost'],
        'resolvedIp': json['resolvedIp'] == null ? undefined : json['resolvedIp'],
        'score': json['score'] == null ? undefined : json['score'],
        'status': json['status'],
    };
}

export function VerificationResultToJSON(json: any): VerificationResult {
    return VerificationResultToJSONTyped(json, false);
}

export function VerificationResultToJSONTyped(value?: VerificationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'acceptsAll': value['acceptsAll'],
        'cached': value['cached'],
        'cachePolicy': value['cachePolicy'],
        'catchAll': value['catchAll'],
        'disposable': value['disposable'],
        'mxHost': value['mxHost'],
        'resolvedIp': value['resolvedIp'],
        'score': value['score'],
        'status': value['status'],
    };
}

